### ISSUE TITLE
Inline error messages for checkout validation

### ISSUE THREAD

**Issue by pippinsplugins** [awesomemotive/easy-digital-downloads#2222]
Our checkout errors aren't too great at the moment. I'd like to update them to show error messages inline with the fields that are invalid.

Errors that are not specific to a certain field can remain at the bottom.

**Comment by MelR** [comment]
Inline error messages would be great! I would like to request a generic message such as "Oops! Some required fields were not filled in." to the top with red background in case an inline error is below the scroll. We have had many confused customers because they missed the bottom error messages.

**Comment by DeysonOrtiz** [comment]
It seems Yoast already has added this to their checkout.  From what I can see it seems they use EDD:  https://yoast.com/checkout-field-validation/

Yoast also have other things they have added to their checkout process if you want to add more options to EDD in the future: https://yoast.com/checkout-page-improvements/

**Comment by pippinsplugins** [comment]
Yoast has made some significant customizations to their checkout (it is EDD).

Seeing what they've done is definitely going to be a good place for us to start.

**Comment by DeysonOrtiz** [comment]
Cool.  I think they did a great job customizing your plugin to make it their own.  One idea you may want to think is to add an option for EDD user for a sequential checkout.  Similar to what UI8 did:  https://ui8.net/

**Comment by michaelbeil** [comment]
Got a request for this.

**Comment by cklosowski** [comment]
We've already accomplished this with HTML 5 validation and inline error messages from the gateways.
