### ISSUE TITLE
Improve "Purchase Confirmation" page layout

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#2304]
_notes from @cklosowski_
I’ve updated this issue to be more about the design aspects of this. I’ve created #7603 to handle the actual splitting of the templates, so we can focus this issue specifically about improving the display and layout of them.

_original issue_

We need to look at renaming the `Purchase Confirmation` to `Receipt` or maybe `Purchase Receipt`.

We also need to build a way that viewing the receipt immediately after purchase has a different URL than viewing order details from the `Purchase History`.

This allows things like google analytics conversion tracking to only fire on the actual conversion, not reviewed receipts.

This would also solve #3391
Original issue:
> As begun in #1956 we should look at making the purchase confirmation page more intuitive. 
> 
> One of the ways suggested way splitting out some of the data, and rearranging some other data. Right now, the purchase confirmation page needs alot of work. 
>
>One of it's biggest weaknesses is that its original title "Purchase Confirmation" is a wording that by itself could either mean this is the confirmation of your purchase, or you need to click a button to finalize your purchase. This becomes even more confusing when translating that string to other languages. 
>
>While we can't change the name, we can look at ways of making the page's data better organized and enhance the "you're done" feeling (maybe change the "thanks for your purchase" to have a green background from the .edd_success CSS class).
>
>See https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/1956#issuecomment-43524608

**Comment by pippinsplugins** [comment]
Punting to 2.4

**Comment by pippinsplugins** [comment]
Any objections to slimming this issue down to just renaming the title from `Purchase Confirmation` to `Receipt`?

**Comment by cklosowski** [comment]
I'm good with that, but can we address #3391 along with it? It's nothing too major, just a different URL that loads the same template and is a much smaller scope.

**Comment by pippinsplugins** [comment]
Yeah let's do it, both for 2.5.

**Comment by cklosowski** [comment]
Related #3529

**Comment by sunnyratilal** [comment]
@pippinsplugins Is the goal here, for now, just to rename `Purchase Confirmation` to `Receipt`?

**Comment by cklosowski** [comment]
No this needs so much more. I'll outline it:
1) We need to build two different URLs, not just a single endpoint for both the purchase confirmation AND the view receipt link.
2) We need to rethink the phrasing on them

I believe that's what we're going for. The reason we need the two different url templates, is so we can allow things like conversion tracking and re-marketing pixels to only fire on the initial purchase confirmation, and not a follow up view of the purchase receipt.

**Comment by pippinsplugins** [comment]
We're too far into 2.7 to get this in. Moving to 2.8.

**Comment by maximejobin** [comment]
I'd like that feature to be completed. I think the "Purchase confirmation" page and the "Receipt" page are confusing as they are the same. @cklosowski 's suggestion seems really logical.

**Comment by cklosowski** [comment]
This is a long standing thing I want to fix, but I think there are two different scopes here we have to recognize.

- Improving the design/layout of the Purchase Confirmation
- Splitting the purchase confirmation and view receipt templates into two separate screens/URLs

I’m going to open a separate issue for the splitting of the two screens. Even if these do nothing but retain the same layouts, setting up the ground work for there to be two separate pages loaded will then let us complete ‘improving’ the layout.
