### ISSUE TITLE
Use EDD_Stats class in EDD_API for retrieving sales / earnings stats

### ISSUE THREAD

**Issue by pippinsplugins** [awesomemotive/easy-digital-downloads#2462]
Now that the `EDD_Stats` class has had some good real world testing (and has performed admirably), it's time to update the `EDD_API` class to use it as well.

This should allow us to completely remove the `get_dates()` method since the `EDD_Stats` class handles all of that automagically.

**Comment by cklosowski** [comment]
@pippinsplugins Where do we stand on this one? Do you have some work that needs to be committed still?

**Comment by pippinsplugins** [comment]
There is some work done in `issue/2462` but it's not complete.

**Comment by pippinsplugins** [comment]
Punting to 2.4

**Comment by pippinsplugins** [comment]
Punted to 2.6 as this is not critical and is simply a nice to have.

**Comment by pippinsplugins** [comment]
@cklosowski could you focus on this soon? Since we're adding EDD_API_V2 in 2.6, it'll be best to include this at the same time.

**Comment by cklosowski** [comment]
Closing as we've improved this dramatically in #9361
