### ISSUE TITLE
Payment History filter totals do not update after bulk edit

### ISSUE THREAD

**Issue by SeanTOSCD** [awesomemotive/easy-digital-downloads#2994]
Go to Downloads -> Payment History and selected a couple of downloads to bulk edit. Do something like change their payment status to pending. The page refreshes and the statuses change. But the quick filter links do not update their counts. It takes another manual refresh to update. Weird.

**Comment by cklosowski** [comment]
What happens if you then refresh the page?

I've seen this before where the WordPress bulk actions actually run after the post total calcualtions are run.

**Comment by sdavis2702** [comment]
*I updated my first post. I said some stuff wrong at first.*

After you refresh the page on your own, the totals simply update. I've seen this before too but was unable to replicate on the Manage Posts screen following similar steps. So I'm guessing it can be done.

**Comment by cklosowski** [comment]
Ok sounds good :) if core can do it, we can too, somewhere :+1:

**Comment by pippinsplugins** [comment]
We will need to force a refresh via javascript due to a limitation of the list table class.

**Comment by cklosowski** [comment]
That's what I was figuring.

**Comment by pippinsplugins** [comment]
I did it recently but am now forgetting where I did it . . .

**Comment by pippinsplugins** [comment]
I'm going to punt this to 2.6 since it's a very minor issue.

**Comment by cklosowski** [comment]
This is not an issue any more in EDD 3.0
