### ISSUE TITLE
Memory limits hit during download delivery

### ISSUE THREAD

**Issue by NateWr** [awesomemotive/easy-digital-downloads#3310]
Hi guys. I just debugged a memory limit issue I had delivering an `8mb` `.zip` file. When I dug into the code, it looks like you're [delivering 1mb chunks](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/process-download.php#L615-L646) rather than the full file. Does that make sense that I'd still hit the memory limit with a larger file?

I was under the impression that delivering a large file in chunks negated this issue. Is it possible that something in my server config is preventing the chunking from working properly?

**Comment by memtoko** [comment]
no the code not delivering you only 1mb, it does full reading to the file. The current implementations just read it 1mb per read (loop) until it hit EOF.

**Comment by pippinsplugins** [comment]
@NateWr what is your memory limit set to?

**Comment by NateWr** [comment]
Looks like it's at `32M` at the moment. I doubt it's changed since I ran into this issue in March. Just as a reminder, I resolved the issue with [this snippet](https://github.com/easydigitaldownloads/library/blob/master/extensions/software-licensing/increase-memory-limit-for-edd.php) so it's currently not a problem for me.

It sounds from @memtoko like maybe I don't understand how the file delivery chunking works, so maybe this isn't really an issue. If I recall, I just wanted to flag it for you in case it suggested something in the code wasn't working as intended.

**Comment by memtoko** [comment]
Ah, i glad it was just memory limit issue. but i found problem with the current implementation, if file can not be read or doesn't exist **fopen** function returns false, in that case the results is infinite loop. We should check that file pointer before using it, if it return false then dont process it, or just say error when open file or anything like that..

**Comment by memtoko** [comment]
ahh, its already checked though, but why silent it? no error reporting to user?

**Comment by pippinsplugins** [comment]
@memtoko By the time we get to `fopen` we have already verified the file exists.

**Comment by pippinsplugins** [comment]
I've seen at least two or three tickets about this recently.

Perhaps we could detect the available memory and then compare it to the fileize. If the filesize is close to or greater than the available memory, we automatically revery to a redirect download.

**Comment by cklosowski** [comment]
I think we'll have to do the redirect on memory limit. We should also account for thread overhead if we can. I'd say if the file being delivered is more than 75% of the memory limit we auto implement the redirect method for that. Thoughts on that @sunnyratilal and @pippinsplugins

**Comment by pippinsplugins** [comment]
I agree.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs We need some pretty good testing done on this. To verify it, upload a file that's larger than the memory limit of your site (you'll probably have to increase your PHP Upload limit before hand) and then purchase and download it, as well as items that are smaller than the PHP Memory limit.

**Comment by sunnyratilal** [comment]
Tested on multiple files over `100MB` and `500MB` with a memory limit set to `64MB` and worked as expected 👍

**Comment by SDavisMedia** [comment]
I **_cannot_** replicate the original issue. All I can do is confirm that it still works for me on `issue/3310`. :+1:

**Comment by pippinsplugins** [comment]
@sunnyratilal were you able to replicate the problem?

**Comment by cklosowski** [comment]
Is it possible to reach out to someone seeing this and see if this branch helps them out? Anyone know a ticket off hand? I did't see any linked above.

**Comment by sunnyratilal** [comment]
I too was unable to replicate the issue.

**Comment by pippinsplugins** [comment]
@memtoko @NateWr either of you able to reliably replicate it? If so could you test it?

**Comment by cklosowski** [comment]
If we want, we can push this to 2.7 to work on it there too. Since the last reports that @pippinsplugins had was in July, that tells me we're not seeing a lot of this, and I think the edge case is pretty high here. I'd love to get it in, but if we want full replication and testing, I think punting to 2.7 is a completely reasonable thing to do instead of pushing out something not fully tested.

**Comment by pippinsplugins** [comment]
Let's punt to 2.7.

**Comment by NateWr** [comment]
I tried to reproduce the original problem today. I couldn't. But I'm on a completely different server setup now (was Apache, now Nginx), so that's not surprising. Sorry to leave you hanging here!

**Comment by cklosowski** [comment]
No worries @NateWr. We'll leave it in 2.7 so we can get a wider breath of testing done on it.

**Comment by sunnyratilal** [comment]
@NateWr have you experienced this bug again since the last update?

**Comment by NateWr** [comment]
@sunnyratilal I use [this](https://github.com/easydigitaldownloads/library/blob/master/extensions/software-licensing/increase-memory-limit-for-edd.php) to get around it, so I haven't experienced it in a long time. I tried to reproduce the problem a while ago (17 Nov) by removing that plugin, but couldn't reproduce it at the time.

**Comment by pippinsplugins** [comment]
That's a nice approach. Maybe we should do that by default.

**Comment by cklosowski** [comment]
With the addition of doing partial requests and 'streamed' downloads I don't believe we've run into this in a long time. We've also created our S3 and Dropbox extensions specifically around large file delivery. Going to close this for now and we can re-open it if we run into it further.
