### ISSUE TITLE
Downloads with long titles get clipped in the discount add screen

### ISSUE THREAD

**Issue by mindctrl** [awesomemotive/easy-digital-downloads#3469]
Only happens during the add process. Edit screen unaffected.

Search for a download with long title:
![search](http://f.cl.ly/items/0U1r0w2C2P0F101U361N/Image%202015-06-02%20at%2012.20.21%20PM.png)

Select the download:
![selected](http://f.cl.ly/items/0r3Y0b3a401I3b3K0A1t/Image%202015-06-02%20at%2012.22.57%20PM.png)

**Comment by cklosowski** [comment]
We've moved to a chosen selector for this in 3.0, this is no longer an issue.
