### ISSUE TITLE
Purchase Confirmation: Square peg in a round hole

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#3529]
Right now, we use the purchase confirmation page for many things that it was never intended to do. For example, it handles the view for pending payments that come from the my account page. Even though the page says purchase confirmation, the order is pending and you can't actually finish it (something #2714 is about).

Purchase Confirmation is used for many more things than purchase confirmation, which is a problem. We need to make it so that the purchase confirmation is only used 1 time, for just completed purchases. Else it is confusing for users. We could even rename it "Thank You" or something.

I think there's a couple related changes that need to happen here.
- As suggested in #2714, eChecks and others should get a processing state.
- A new page should be made called order status.
  - The order status should take a url param called ?id=xx&cid=xx&&key=xx where id is the order ID, cid is the customer id and key is the payment key unique to the customer. If this id is not included, show a simple form that asks for an order number and payment key (both are on receipts) to see the status. Both the id, and key must be provided and the key must match the id in order to see the order information
    - If the order is processing (awaiting IPN callback from PayPal), show a waiting timer, where on timeout, show order status of pending
  - If the order is pending, show items in cart along with fees, and discounts and offer ability to pay for the item
  - If the order is abandoned, see pending
  - If the order is complete, show the totals, download links, etc. If a url param called "success" is present, show the thank you for purchasing notification
  - If the order is saved, see pending
- From the My Account page link to the order status page

The problem with "Purchase Confirmation" is we use it for many things where Purchase confirmation isn't actually a confirmation. This is confusing to people, particularly those who've added text to the page who think its only used for receipts.

Alternatively, we could introduce views on the my account page to handle complete, pending, saved, and abandoned, and views on the purchase confirmation page for processing and complete with success.

**Comment by pippinsplugins** [comment]
We definitely need to re-work how this all works.

I haven't thought about it too much yet, but initially I like the idea of an order status page.

**Comment by cklosowski** [comment]
This is the point of #3391 as well.

**Comment by pippinsplugins** [comment]
This and #3391 moved to 2.6

**Comment by pippinsplugins** [comment]
Too late in 2.6 cycle to get this.

**Comment by cklosowski** [comment]
Related #2304

**Comment by sunnyratilal** [comment]
Related #2304

**Comment by pippinsplugins** [comment]
We're too close to 2.7 beta to get this in.

**Comment by cklosowski** [comment]
This was just brought up again in #5681 by @KrashKartMedia. As part of our "polish" update for 2.8, I vote this makes it. I'll champion the migration of it.
