### ISSUE TITLE
Integration of a edd-language-pack-upgrader class

### ISSUE THREAD

**Issue by fxbenard** [awesomemotive/easy-digital-downloads#3605]
Based on WC class and what they do with their translations on Transifex, doing the same will be a great improvement for translations in EDD and an alternative for translate.wordpress.org for now.

https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-language-pack-upgrader.php
https://github.com/woothemes/woocommerce-language-packs

**Comment by pippinsplugins** [comment]
That would be awesome :)
