### ISSUE TITLE
Update password fields with password generator from WP 4.3

### ISSUE THREAD

**Issue by pippinsplugins** [awesomemotive/easy-digital-downloads#3732]
Better security for the win.

**Comment by pippinsplugins** [comment]
Note: this will probably make `Password Strength Meter` extension obsolete. Sorry @ghost1227

**Comment by chriscct7** [comment]
We should implement this in a way that's easy for extensions that also need to use it (FES or one of the membership/restrict plugins for example) can use at least some of EDD's code

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Relevant: http://uxmovement.com/forms/why-the-confirm-password-field-must-die/

**Comment by cklosowski** [comment]
@pippinsplugins with that in mind, should we just move #3794 into this one as a duplicate?

**Comment by cklosowski** [comment]
or should they both just be wrapped into 2.5?

**Comment by pippinsplugins** [comment]
Let's merge the issues into this one.

**Comment by mindctrl** [comment]
Something we may need to consider. Any page that displays the password meter loads a 700KB minified JS file from core (zxcvbn.min.js). Not sure what this will do to perceived load times, if anything.

**Comment by pippinsplugins** [comment]
@mindctrl Even if we use the one from core?

**Comment by mindctrl** [comment]
@pippinsplugins this file gets loaded: https://github.com/WordPress/WordPress/blob/master/wp-includes/js/zxcvbn.min.js

**Comment by pippinsplugins** [comment]
Got it.

**Comment by chriscct7** [comment]
There's also a little bit of CSS that goes with that. We can copy it to our stylesheet though

**Comment by pippinsplugins** [comment]
I think we should go ahead and punt this to 2.6 or 2.7.

**Comment by cklosowski** [comment]
We've done this with our new Registration Block:
https://a.supportally.com/i/aWQ3DE
