### ISSUE TITLE
Improvement - Extending reports

### ISSUE THREAD

**Issue by daigo75** [awesomemotive/easy-digital-downloads#3842]
Several customers asked to have the possibility of running reports filtered by currency (see example http://prntscr.com/8liaae). From a UI perspective, this is relatively easy, but the architecture of EDD reports doesn't seem to allow altering the data retrieved for the report. For example, method `EDD_Payment_Stats::get_earnings()` uses the following logic:
1. Retrieve all the payments in a date range.
2. Fetch the total for each payment.

Neither operation can be altered, due to the lack of filters. There is a filter for `edd_stats_earnings_args`, but that won't suffice, because order currency is bundled with the `_edd_payment_meta` and cannot be used retrieved a simple meta query.
## Proposed solution
1. Add a filter to allow manipulating the list of posts retrieved by `get_posts()`. This would mean retrieving all posts, like it's already done, then discarding the ones that don't match the selected currency, and it would not be super-efficient, but it would do the job.
2. Add a filter for the report's transient key, so that the currency can be taken into account. This is necessary to store a cached copy of each report, for each currency (and other data, if needed).
3. Add a filter to override the earnings retrieval, in order to return the data for the appropriate currency.

I prepared an example of how I would extend the method in this gist: https://gist.github.com/daigo75/25a00fdaa9507910cb28. I only modified `EDD_Payment_Stats::get_earnings()`, other methods would have to be reviewed and extended as well.
## Note

It seems that global function `edd_get_earnings_by_date()` is still used, despite its code documentation saying "_This is getting deprecated soon. Use EDD_Payment_Stats with the get_earnings() method instead_". If EDD reports are still going to use that function, then it would become necessary to modify it too, so that the same filters can be applied to the data it retrieves.

**Comment by pippinsplugins** [comment]
Thanks @daigo75! I'm sure we can get something in to make it more flexible.

**Comment by daigo75** [comment]
You're welcome. Please leave the UI as a lower priority, we can always render extra filters somewhere and "inject" them via JavaScript. The key would be to alter the data passed to the report renderer with the minimum amount of intervention.

In short, I would rather not copy/paste entire classes to rewrite bits and pieces of them, as that could cause countless headaches. Been there, done that (WooCommerce, as you might have guessed by now). :smile:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
EDD 3.0's reports and stats APIs fully support querying by currency.
