### ISSUE TITLE
Translations should have a priority system similar to templates

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#3858]
In #1717 we added a function that lists all the places to look for templates, and made it possible to filter that list and add, remove, or rearrange the order based on priorities.

With the new places we now have to start looking for translations, moving to this type of system for translations makes a huge amount of sense.

It would provide many additional advantages:
- We can easily add new places in the future to look
- It makes it easy for users to define a custom textdomain folder if they want (perhaps they want to keep all of their translation files in a single folder somewhere)
- It would allow extensions that would like to allow their users to have their plugin translation files in a different directory to be able to quickly check all of EDD's folders, which is particularly useful for plugins not listed on .org.

I've milestoned this for 2.5 for a couple reasons:
- Since we're going to have to go through all of the large extensions and update the 'edd' strings that are in them anyways, it would be nice to also be able to implement this in the larger extensions at the same time. 
- Some extensions already do this and this would allow them to reduce their loc, if they're already doing a big update soon (like FES)
- This is a really low impact item to do, but provides huge upside

**Comment by pippinsplugins** [comment]
Can't get this in 2.5, sorry. 2.6. It's a really nice to have but not critical.

**Comment by cklosowski** [comment]
EDD core has moved to just relying on WP Core translations for this and all bundeled translations have been removed in #9118 .
