### ISSUE TITLE
In EDD_HTML_Elements::customer_dropdown() placeholder does nothing

### ISSUE THREAD

**Issue by topher1kenobe** [awesomemotive/easy-digital-downloads#3888]
`EDD_HTML_Elements::customer_dropdown()` says it can take an array item of placeholder, and the default is `'placeholder' => __( 'Select a Customer', 'easy-digital-downloads' )` but it never gets used.  I'd like to see it get used as the first item in the drop down, of either chosen or the plain select field.

`EDD_HTML_Elements::product_dropdown()` does it properly.

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs Can anyone else replicate? I'm unable to.

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs Can someone run a quick test on this please? I'm unable to replicate.

**Comment by mintplugins** [comment]
@sunnyratilal Mine defaults to say "No Customer Attached"

<img width="325" alt="screen shot 2017-01-09 at 4 32 22 pm" src="https://cloud.githubusercontent.com/assets/1638128/21784382/46644cd4-d689-11e6-8ac7-c319b35685ea.png">

**Comment by mintplugins** [comment]
Actually, the true placeholder seems to be "Type to search all Customers" which comes from scripts.php when localizing the javascript. 
<img width="318" alt="screen shot 2017-01-09 at 4 33 39 pm" src="https://cloud.githubusercontent.com/assets/1638128/21784454/94058d40-d689-11e6-8460-c854b65243e9.png">

**Comment by mintplugins** [comment]
It does seem like the placeholder parameter is not being used - or at least is being overwritten by the localization. If I do this, the placeholder does not change from "Type to search all Customers":

```
echo EDD()->html->customer_dropdown( array(
		'placeholder' => 'Testing' )
	);
```

**Comment by cklosowski** [comment]
I believe this has to do with the way that Chosen writes up it's placeholders. I think it's a pretty low priority. I'm going to punt this.

**Comment by cklosowski** [comment]
We updated our chosen usage in EDD 3.0, closing as this is no longer an issue.
