### ISSUE TITLE
Build more robust unit testing practices

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#3909]
Right now many of our unit tests are testing multiple use cases in a single test method, we should audit our unit tests and make sure we're testing one use case per test method, and properly resetting data (when necessary) in the setUp and tearDown methods.

**Comment by JeroenSormani** [comment]
I'm a huge fan of using dataproviders for multiple tests of a single functions. Your thoughts on that?

I'd be happy to help refacting this if you need help. Just @ me ;-)

**Comment by cklosowski** [comment]
This issue was not specific enough or provided enough actionable requests. I'm going to close it as we have rebuilt the unit tests multiple times since this.
