### ISSUE TITLE
Allow forwarding of a purchase receipt to a different email address

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#3914]
We should enable a method for customers (and admins) to specify and email address and send a purchase receipt to that email address. This would allow people to make purchases and then send to the 'purchasing' department, or 'accountant' while still remaining data integrity between the customer and the payment.

**Comment by pippinsplugins** [comment]
I think this should happen on both purchase confirmation (for customers) and view order details (for admins).

**Comment by pippinsplugins** [comment]
Moving to 2.7.

**Comment by cklosowski** [comment]
This has been done in EDD 3.0 and in combination with #3755 we can now just send the purchase receipt to any email address associated with the customer record.

To do this, just add the email address as associated with the customer, and then resend the receipt.
![image](https://user-images.githubusercontent.com/1390124/186309538-509152c2-bc75-4ecd-bf76-a1f0fcf32778.png)
