### ISSUE TITLE
Restrict editing email on checkout for existing customers

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#3915]
When a customer is logged in on checkout, we should make the email field readonly. The user would then have to `click to edit` their email address, with a notice that then states this will update the email address for their customer record, This will coincide with #3914 to also allow a purchase receipt to be forwarded to a specific email address (via admin or front end for the customer).

The goal of this issue is to limit data drift between the customer record and the payment record, while still allowing customer's to easily send download links and purchase receipts to an additional email address of their choice.

**Comment by pippinsplugins** [comment]
I don't think this is necessary if we get #3755 completed.

**Comment by arielk** [comment]
I think that is really important, right now I have a lot of problems with this field: conflicts, customers that not connected to users, etc...

**Comment by pippinsplugins** [comment]
@arielk are your conflicts coming from logged in customers using an email that is different than what's on their account?

**Comment by arielk** [comment]
I think it's because of this, but i'm not sure. some times I found purchases without users recorded in the customer listing (of course "Require that users be logged-in to purchase files" checked).

Anyway many users feel confused with this input and it makes sense for me that users use in the same email address for all his purchases

**Comment by pippinsplugins** [comment]
I'd recommend using our Auto Register plugin: https://easydigitaldownloads.com/downloads/auto-register/

We have fixed a few bugs related to user account connections with customers. Are you seeing it with older customer records or new ones too?

**Comment by arielk** [comment]
Sincerely I don't remember when it was I'll try to track on this soon.

p.s. Auto Register plugin send to user the random password in the mail. I think that isn't secure because the WordPress stopped sending passwords in the email.

**Comment by pippinsplugins** [comment]
That email can be disabled from the settings screen.

**Comment by cklosowski** [comment]
With #3755, this is no longer as much of an issue.
