### ISSUE TITLE
Taxes for entire purchase deducted from revenue of one item in cart when shown in report

### ISSUE THREAD

**Issue by NateWr** [awesomemotive/easy-digital-downloads#4108]
While investigating a discrepancy in my reported revenue, I noticed an issue with the reports. A purchase of one of my products that is typically $20 was showing at $5.30 which couldn't be explained by one of my discount codes:

![edd-tax-assignment](https://cloud.githubusercontent.com/assets/2306629/12074838/98b1926e-b162-11e5-8e06-16461a2ba0d8.png)

Investigating this further, I noticed that the reported revenue matched the cost of the product minus the taxes on the purchase ($20 - $14.70 = $5.30):

![edd-tax-assignment-2](https://cloud.githubusercontent.com/assets/2306629/12074842/c84de108-b162-11e5-8abe-8f5e729ffe95.png)

It seems like the tax shouldn't be deducted from the $20 value, since tax was taken in addition to the price.

I'm using the Stripe addon as well as the Taxamo integration. I wondered if this is something you can reproduce with just EDD or if I need to look into the Taxamo addon. I may be able to find the time to run some tests in the next week or two if you'd like confirmation before looking into it.

Related issues: #3762 and #1490

**Comment by pippinsplugins** [comment]
Ah yes! You're absolutely right. When the `Exclude Taxes` box is checked, it's subtracting the total taxes from the amount instead of just the tax for that item.

We'll get it fixed.

**Comment by pippinsplugins** [comment]
@NateWr Would it be possible for you to var_dump() the value of `cart_details`?

```php
$payment = new EDD_Payment( $payment_id );
var_dump( $payment->cart_details );
```

**Comment by NateWr** [comment]
Sorry for the delay. Never enough time. :)

```
array(3) {
  [0]=>
  array(10) {
    ["name"]=>
    string(37) "MailChimp for Restaurant Reservations"
    ["id"]=>
    string(4) "2195"
    ["item_number"]=>
    array(3) {
      ["id"]=>
      string(4) "2195"
      ["options"]=>
      array(0) {
      }
      ["quantity"]=>
      int(1)
    }
    ["item_price"]=>
    float(20)
    ["quantity"]=>
    int(1)
    ["discount"]=>
    float(0)
    ["subtotal"]=>
    float(20)
    ["tax"]=>
    float(0)
    ["fees"]=>
    array(0) {
    }
    ["price"]=>
    float(20)
  }
  [1]=>
  array(10) {
    ["name"]=>
    string(41) "Custom Fields for Restaurant Reservations"
    ["id"]=>
    string(4) "8448"
    ["item_number"]=>
    array(3) {
      ["id"]=>
      string(4) "8448"
      ["options"]=>
      array(0) {
      }
      ["quantity"]=>
      int(1)
    }
    ["item_price"]=>
    float(30)
    ["quantity"]=>
    int(1)
    ["discount"]=>
    float(0)
    ["subtotal"]=>
    float(30)
    ["tax"]=>
    float(0)
    ["fees"]=>
    array(0) {
    }
    ["price"]=>
    float(30)
  }
  [2]=>
  array(10) {
    ["name"]=>
    string(43) "Export Bookings for Restaurant Reservations"
    ["id"]=>
    string(4) "7339"
    ["item_number"]=>
    array(3) {
      ["id"]=>
      string(4) "7339"
      ["options"]=>
      array(0) {
      }
      ["quantity"]=>
      int(1)
    }
    ["item_price"]=>
    float(20)
    ["quantity"]=>
    int(1)
    ["discount"]=>
    float(0)
    ["subtotal"]=>
    float(20)
    ["tax"]=>
    float(0)
    ["fees"]=>
    array(0) {
    }
    ["price"]=>
    float(20)
  }
}
```

**Comment by cklosowski** [comment]
this is interesting b/c the stats class does only subtract the taxes found for the specific cart item:
```
if ( ! $include_taxes ) {
	$earnings -= edd_get_payment_item_tax( $payment_id, $cart_key );
}
```

I'm not seeing any taxes on your cart items @NateWr, do you have a payment that does have taxes in the cart details?

**Comment by NateWr** [comment]
Thanks for looking into this @cklosowski. I'm confused as well. If you look at the screenshot you'll see it's showing taxes for this purchase (and I've double-checked that the `var_dump` represents this purchase).

 I'm using the Taxamo addon. Is it possible that the tax information is stored separately?

**Comment by cklosowski** [comment]
It's very possible that they are using the filter to return different tax
information than what is stored in our payment meta. I'll have to dig into
that further.

The screenshot proves that something is deducting incorrectly, just need to
figure out where that deduction is happening and fix it. I'll have to set
aside some time to dig into the integration more to see if it's an
integration issue.

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by NateWr** [comment]
I'm made a soft promise to Rhys to try and contribute to the maintenance of that plugin, so I will try to set aside some time to look into the issue. Because it's not part of my regular daily duties it tends to get ignored, but I have another bug with it I've been meaning to tackle so I'll add this on.

**Comment by cklosowski** [comment]
punting until we get some more feedback/replication on this.

**Comment by cklosowski** [comment]
We're still awaiting feedback. Going to punt.

**Comment by sunnyratilal** [comment]
Punting as we're still awaiting feedback here.

**Comment by cklosowski** [comment]
I'm closing this out, EDD 3.0 doesn't do the math this way anymore and has been rebuilt with the new tables. We can re-address/re-open later if we need tol
