### ISSUE TITLE
Better unit tests for dates and timezones of payment records

### ISSUE THREAD

**Issue by pippinsplugins** [awesomemotive/easy-digital-downloads#4180]
In 2.5 we inadvertently caused some bugs when we modified how the payment dates are created, resulting in some payments being given a date in the future. To better protect against this in the future, let's add improved unit tests for these scenarios.

**Comment by cklosowski** [comment]
With a 100% rewritten stats class, query class, and database structure, we can close this out as the unit tests surrounding reports and queries of dates are pretty substantial, and have better timezone support now that ED 3.0 does everything in the DB as UTC.
