### ISSUE TITLE
Update "Total Price" when processing a partial refund via PayPal

### ISSUE THREAD

**Issue by amdrew** [awesomemotive/easy-digital-downloads#4212]
When you process a partial refund via PayPal, EDD stores a note:

`Partial PayPal refund processed: 6JB969994H600144H`

It would be great if EDD could then update the `Total Price` to reflect the partial refund.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mintplugins** [comment]
I would propose we add a new Refund button beside each item. This way, if you want to remove an item from a user without refunding them you can click "Remove". If you want to process a refund, you can click refund and it will go to the payment gateway and process the refund for you as well.

![screen-shot-2016-10-27-at-1 26 22-pm](https://cloud.githubusercontent.com/assets/1638128/19778163/6b130cde-9c49-11e6-89de-02210e2f292b.jpg)

**Comment by cklosowski** [comment]
This is no longer an issue with EDD 3.0, as the refund API takes care of all this.
