### ISSUE TITLE
Keep data when switching payment methods at checkout

### ISSUE THREAD

**Issue by amdrew** [awesomemotive/easy-digital-downloads#4220]
Can't find an issue for it but when switching payment methods on the checkout page you shouldn't lose your details entered. Switching the payment method should only update the relevant input fields, no need to touch Personal Info etc.

**Comment by pippinsplugins** [comment]
Let's see if we can get this in 2.7

**Comment by cklosowski** [comment]
I love this idea, bugs me all the time when I'm testing, and could help improve conversion rates for sure.

**Comment by pippinsplugins** [comment]
This shouldn't be too difficult to do if we make it so switching gateways only changes out the payment fields instead of all fields.

**Comment by pippinsplugins** [comment]
This should be done along side #4195

**Comment by felixarntz** [comment]
For reference, #5036 proposes a temporary fix until an actual gateway rewrite happens. I'm not sure how long the latter will take, but it surely sounds like a time-consuming task to me, so maybe fixing the issue beforehand could be a good idea.

**Comment by pippinsplugins** [comment]
I agree that we should try and get this in without relying on the gateway rebuild.

**Comment by pippinsplugins** [comment]
Related #5082

**Comment by pippinsplugins** [comment]
Moving this to 2.7.5.

**Comment by mintplugins** [comment]
We should also make sure this works not just when changing payment gateways, but anytime the cart changes. 

For example, if there's an error in the cart after submission, all fields have to be re-filled by the customer.

**Comment by ciorici** [comment]
I see that this issue was assigned to version 2.9, but I still see this problem, even after 2.9 update. It can also be reproduced on https://easydigitaldownloads.com/checkout/ after you add a product in the cart.
Try to fill some fields in Personal Info (email, name), and if you change the payment method to PayPal, everything clears out.

**Comment by mintplugins** [comment]
@ciorici The milestone was changed to 3.1 for this issue.

**Comment by polevaultweb** [comment]
+1 for this to get fixed, super strange UX that's likely to put customers off purchasing if they change their minds about the method to pay and have to re-input all their data again

**Comment by dgoldak** [comment]
Noting that https://formidableforms.com/pricing/ appears to have a solution for this.

<img width="879" alt="Screen Shot 2020-10-23 at 10 26 46 AM" src="https://user-images.githubusercontent.com/30910807/97023363-02310780-151b-11eb-80f7-81da2da6611a.png">

I'm not sure if cart changes clear fields.

**Comment by cklosowski** [comment]
I'm going to remove this from 3.1, as we're working on a larger project to overhaul the checkout design/templates. We'll fix it within that.
