### ISSUE TITLE
Settings subsection ordering

### ISSUE THREAD

**Issue by mindctrl** [awesomemotive/easy-digital-downloads#4231]
Consideration for enhancement:

When viewing the extensions tab, having the subsections ordered alphabetically would make it a little easier to quickly find what you're looking for.

![image](https://cloud.githubusercontent.com/assets/1254870/12517857/0d598662-c103-11e5-91fb-ae2e6d04a9f6.png)

If we could order those alphabetically, but leave Main in the front, it would be nice.

I don't know if we want to consider this for other settings tabs, but with extensions specifically the order can change easily based on number of extensions active and it's harder to quickly scan.

**Comment by SDavisMedia** [comment]
I agree with the suggestion here.

**Comment by pippinsplugins** [comment]
I agree. That would be nice.

**Comment by michaelbeil** [comment]
That'd be great.

**Comment by cklosowski** [comment]
Closing this as we've vastly improved our settings menus to try and pull things out of the 'catch all' of extensions and put them in locations that make more sense, alongside core settings.
