### ISSUE TITLE
Downloads sold by date range

### ISSUE THREAD

**Issue by SeanTOSCD** [awesomemotive/easy-digital-downloads#4512]
It looks like there is no way to see how many of a specific download was sold in a specific date range and export the data.

Ticket: https://secure.helpscout.net/conversation/190715569/0/

@cklosowski Not sure if you were agreeing to the report itself or the export, or both. But we can adjust this issue as needed.

**Comment by pippinsplugins** [comment]
Would be nice to support this for sure.

**Comment by cklosowski** [comment]
EDD 3.0 supports this in the new Reporting API.
