### ISSUE TITLE
Functions related to "total earnings" can't take the currency into account

### ISSUE THREAD

**Issue by daigo75** [awesomemotive/easy-digital-downloads#4574]
Today I noticed on a customer's site (multi-currency) that the `edd_earnings_total` were increasing and decreasing in an unexpected way. After an investigation, I realised that the `edd_earnings_total` value is manipulated by functions that are not currency-aware, and also not context-ware.

Examples
1. `edd_get_total_earnings()`
This function fetches the total of each payment, adds it to a total, disregarding the currency, and stores the result to `edd_earnings_total`. 100 USD + 100 GBP + 100 EUR become "300".
2. `EDD_Tools_Recount_Store_Earnings::get_data()`
Same as n.1.
3. `edd_increase_total_earnings()` and `edd_decrease_total_earnings()`
These functions are invoked by passing a raw numeric value, without currency or context information. Such information also cannot be retrieved, as these functions can be invoked in several different cases.
## Proposed solution

Since the total earnings are expected to be in base currency, a filter should be added to process any value that is going to be used to alter them, passing as much context information as possible.
For example, for a payment total, the call should pass the payment currency, so that any filter would be able to determine which conversion should be performed.

**Comment by pippinsplugins** [comment]
I've closed the https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4575 PR as the proposed solution there won't work for performance reasons. We'll need an alternate proposal in order to do this.

**Comment by cklosowski** [comment]
With 3.0 we have currency aware database queries and conversions with the 'rate' column.
