### ISSUE TITLE
Move user address fields to customer meta

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#4622]
With the addition of #4311, we should look at moving all the `Address` information stored in `usermeta` over to `customermeta`, since this is a more customer based data set, which also allows us to remove it from the installation easier when we uninstall.

**Comment by pippinsplugins** [comment]
Yes!

**Comment by cklosowski** [comment]
As a note, we should test this with Auto Register. We've seen a few reports that customer address data isn't stored on the user during the first purchase when auto-register is used. I think using customer meta, we can do this more reliably since it doesn't require a logged in check.

**Comment by pippinsplugins** [comment]
@cklosowski preference for storing each address field in a separate meta row or combining them all together?

**Comment by pippinsplugins** [comment]
I'm voting for separate.

**Comment by DevinWalker** [comment]
How do you determine if the address you're moving over is in fact the actual customers' address? The billing details fieldset is developed to be representative of the address attached to the credit card. For instance, a developer who works for an agency may have used the company card and business address. Moving the address into that customers' record would be incorrect. 

How about adding a global checkout option to collect the customer's address at checkout then if enabled have a checkbox that asks if their billing address is separate. If it is, display the existing fieldset. If not, the same address can be used for both:

![screen-shot-2016-08-15-at-5 35 10-pm](https://cloud.githubusercontent.com/assets/1571635/17684468/c6070752-6310-11e6-9d4d-3e7cce14971f.jpg)

**Comment by cklosowski** [comment]
@DevinWalker raises some good points here. Going to punt this to 2.8 so we can look into some options here.

**Comment by cklosowski** [comment]
We can close this as with 3.0 we have specific tables for physical addresses.
