### ISSUE TITLE
edd_profile_editor not updating display_name on first save

### ISSUE THREAD

**Issue by metal450** [awesomemotive/easy-digital-downloads#4630]
EDD 2.5.16, WP 4.5.2, Digital Store (theme) 1.3.6.

Using the [edd_profile_editor], if you have the Display Name set to i.e. First Name, then you edit the First Name field and save, it doesn't actually update the display_name (as seen by the WP core) until the _second_ time you save.

To reproduce:
1) Create a user "Test Friend," & select Display Name as "Test."
2) Use edd_profile_editor to change First Name to "Test2," & save
3) edd_profile_editor now shows that Display Name has changed to "Test2," as expected.  However, if you visit the profile via the actual Wordpress admin panel, it still shows "Test" (and likewise any widgets which refer to display_name).
4) Without changing anything, save edd_profile_editor a second time.
5) Refresh the WP admin panel's profile page.  Now it shows "Test2," as it should.

Screen capture: http://screencast.com/t/iingBOwN

**Comment by pippinsplugins** [comment]
Thanks for the report! That should be pretty straight forward to resolve.

**Comment by sunnyratilal** [comment]
Updating your profile from the admin profile page works in the same way. The display name option isn't changed automatically when editing the first name. But we can add some JavaScript that will populate new options based on the text entered.
