### ISSUE TITLE
Restrict discount codes to products with a specific taxonomy

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#5015]
It would be nice to be able to restrict a discount code to products with a specific download category or tag. Think something like "Save 10% on a gateway extension" from the EDD site.

**Comment by SDavisMedia** [comment]
Nice! Maybe this could be built alongside #4583 since they're similar in nature.

**Comment by pippinsplugins** [comment]
Related #4066

**Comment by eugenesp** [comment]
+1 Please implement this. I am using EDD All Access Pass extension to implement a subscription service on top of regular EDD downloads. I want to give my customers discounts they can apply to anything except All Access pass/Membership products. Being able to limit a discount to a category with individual downloads would easily solve this problem

**Comment by cklosowski** [comment]
Closing this as we have a duplicate issue created to allow discounts to be limited to taxonomies.
