### ISSUE TITLE
Select field always shows "Type to search Downloads" even when given alternate data

### ISSUE THREAD

**Issue by brashrebel** [awesomemotive/easy-digital-downloads#5040]
When using the EDD HTML select field, it is possible to apply it in different use cases beyond just listing downloads by using the `options` argument. However, even when doing so, it still displays:

> Type to search Downloads

When you enter the field to search for a value.

```
EDD_HTML_Elements()->select( array(
                    'id'               => 'something',
                    'name'             => 'something',
                    'options'          => $some_array_of_arbitrary_values,
                    'multiple'         => true,
                    'chosen'           => true,
                ) );
```

Could we add another argument to alter that text?

**Comment by cklosowski** [comment]
We have done this for Customers and Countries. Have you looked at their implantation? ill double check but I  Bunk we have a way around this already.

**Comment by cklosowski** [comment]
This is resolved now that we've revamped the search in select boxes for 3.0
