### ISSUE TITLE
Convert addons feed from RSS to JSON

### ISSUE THREAD

**Issue by brashrebel** [awesomemotive/easy-digital-downloads#5121]
The extensions admin page in EDD core currently pulls from an RSS feed on easydigitaldownloads.com. It uses `wp_remote_retrieve_body()` [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/add-ons.php#L88) to get all the HTML from the page generated by the EDD Site theme [here](https://github.com/easydigitaldownloads/EDD-Site/blob/master/addons-feed.php). This is pretty efficient and has worked for a long time but it is also limiting.

In instances like #3733 it would be nice to be able to retrieve the data from easydigitaldownloads.com and then do something with it. In that example it would be checking the list of retrieved extensions and excluding ones that are already installed on the site from displaying so that there is room for others. But there could be other possibilities beyond just this where it is helpful to be able to modify the data or display in order to improve the experience for the site owner.

For this reason, I propose that we use a JSON endpoint as the point of access for EDD instead of an RSS feed. This would result in EDD core receiving raw JSON instead of a very large string of HTML and then handling the display within the plugin.
## Concerns
- Is there a performance hit for this? Right now we're heavily caching the feed page.
- Is there a drawback to moving the bulk of this into the plugin instead of handling the majority of it inside the theme?
- Is there an easier way that I'm missing to accomplish some of my concerns without changing to JSON at all?

Definitely interested in starting a discussion around this.

**Comment by sunnyratilal** [comment]
A counter proposal could be to send a `POST` request to `https://easydigitaldownloads.com/?feed=addons` with a list of all the EDD add-ons activated and just have the site serve up the pertinent HTML.

**Comment by pippinsplugins** [comment]
Our REST API provides a public endpoint in JSON, so that part's easy.

**Comment by brashrebel** [comment]
Thanks for the input. Ultimately I think it would be amazing if we could simply get to a point where we have more flexibility when it comes to the display of those addons. If we can make it so we're getting a list of items and their data instead of a full page of HTML we do creative things to improve the experience and increase our conversion rate.

We could exclude already purchased addons
We could add a "Recommended" tab based on the site's current setup
We could add a "Show more" button or some other mechanism to display even more addons to users who want to continue browsing past our current limit of 28 addons
We could (and this would be really cool) possibly run A/B tests to truly optimize the page for conversions
We could add a search feature
We could add our category filters

All of this is certainly much later but the point is, we can get creative if we're getting data instead of a page of HTML. I'm not certain whether @sunnyratilal's idea makes that easier or is much different in the end.

**Comment by pippinsplugins** [comment]
Having that flexibility would be stellar.

One downside, however, that should be noted is that moving the rendering into EDD removes our ability to make changes to the add-ons feed display without also releasing an update to the plugin. Right now we can change the items that are displayed, manually insert a banner ad, or anything else we want directly from the RSS feed and it will be shown in _all_ installs immediately.

**Comment by brashrebel** [comment]
That's a really important point. I'd like to get some input from @cklosowski too. There certainly appears to be a tradeoff between having tons of flexibility for displaying the content in the plugin vs. having flexibility from the site to make changes without releasing a new version. Both are obviously important. I'm not sure whether one trumps the other or if there is perhaps some compromise that could be made to address both concerns.

**Comment by cklosowski** [comment]
I'm closing this as we've already started some of this process in a mixture of other ways and this addons feed is going to be changed drastically in the near future.
