### ISSUE TITLE
Page display states

### ISSUE THREAD

**Issue by ghost** [awesomemotive/easy-digital-downloads#5133]
When a site is publishing more than 20 pages it can quickly become a task to remember which of them are used by a plugin and which are not.

I've created a quick plugin to keep them at bay, but instead I'd love to see this implemented into Easy Digital Downloads itself. Preferably visually identical to how WordPress already handles static front pages/blog pages.

Would this be a feature you might consider adding?

![2-11-2016 14-21-39](https://cloud.githubusercontent.com/assets/1499293/19930231/c25ecab0-a107-11e6-84df-de096a46163c.png)

```php
function prefix_display_post_states( $post_states, $post ) {
	if ( intval( edd_get_option( 'purchase_page' ) ) === $post->ID ) {
		$post_states['purchase_page'] = __( 'Checkout Page', 'easy-digital-downloads' );
	}
	if ( intval( edd_get_option( 'success_page' ) ) === $post->ID ) {
		$post_states['success_page'] = __( 'Success Page', 'easy-digital-downloads' );
	}
	if ( intval( edd_get_option( 'failure_page' ) ) === $post->ID ) {
		$post_states['failure_page'] = __( 'Failed Transaction Page', 'easy-digital-downloads' );
	}
	if ( intval( edd_get_option( 'purchase_history_page' ) ) === $post->ID ) {
		$post_states['purchase_history_page'] = __( 'Purchase History Page', 'easy-digital-downloads' );
	}
	return $post_states;
}
add_filter( 'display_post_states', 'prefix_display_post_states', 10, 2 );
```

**Comment by pippinsplugins** [comment]
I _really_ like this.

**Comment by SDavisMedia** [comment]
Yes please! Can we also include the **Login Redirect Page** if it's set?

**Comment by pippinsplugins** [comment]
Yes I think so
