### ISSUE TITLE
Better tooltips and descriptions for taxes

### ISSUE THREAD

**Issue by michaelbeil** [awesomemotive/easy-digital-downloads#5244]
It would be good to improve our tooltips and descriptions in the taxes tab.

Per https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4200#issuecomment-260743301 and https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4200#issuecomment-261361590.

**Comment by cklosowski** [comment]
Our Tax UI has been completely revamped since this was created, in 3.0+. Closing this so we can approach any adjustments to the tax settings in a new issue.
