### ISSUE TITLE
Introduce popular downloads feature

### ISSUE THREAD

**Issue by brashrebel** [awesomemotive/easy-digital-downloads#5264]
There are many instances in which stores wish to highlight their most popular products. I can't find a simple way to do this and believe it could be quite useful to have a way to either get a bunch of popular items or just order a query by popularity. Probably the most simple and usable solution would be to add `popular` as an accepted option for the `orderby` property in the [downloads] shortcode. Most likely this would simply get the number of sales for each download.

WooCommerce has a [best_selling_products] shortcode that basically does this.

**Comment by pippinsplugins** [comment]
A simple orderby on the sales meta key would work.

We could introduce a dedicated `edd_get_best_selling_downloads()` function and offer `sales` as an option for the `orderby` parameter` of `[downloads]`

**Comment by brashrebel** [comment]
That's pretty much what I was thinking.

**Comment by spencerfinnell** [comment]
Yep in Marketify we detect a custom `orderby=sales` in the shortcode attributes and order by `_edd_download_sales`. Would be great to see it in core.

**Comment by chriscct7** [comment]
I think it might also be interesting to offer `earnings` as well, given if you want to show "best sellers", if you order by sales, technically free sales are still counted as a sale in EDD so you'd want ot really order by earnings.

**Comment by brashrebel** [comment]
@chriscct7 if people do use the feature, excluding free downloads will absolutely come up. Either having a separate argument for earnings or somehow excluding free downloads would probably be necessary from the get go.

**Comment by chriscct7** [comment]
There's 3 variations I think
Sales with and without free downloads, and earnings

**Comment by cklosowski** [comment]
@robincornett Is this something we can add to the block you are working on for the downloads display? Sort by, and have revenue or sales?
