### ISSUE TITLE
Improve speed of unit tests

### ISSUE THREAD

**Issue by pippinsplugins** [awesomemotive/easy-digital-downloads#5457]
Unit test builds on Travis currently take more than an hour to process. This is far too long and should be able to be reduced to a few minutes.

@DrewAPicture recently introduced dramatic improvements to the unit tests in AffiliateWP that had really significant impacts on the run time. Let's make the same improvements here.

**Comment by cklosowski** [comment]
They don't actually take an hour, that's just the cumulation of all the runs we have. Since it's running 5 at a time, it's actually completing in 15-20 minutes.

**Comment by cklosowski** [comment]
Not saying we don't need to improve them, but it's a weird measurement they take for the 'time' that a build takes.

**Comment by pippinsplugins** [comment]
Ah! Good point. Still too long :)

**Comment by sunnyratilal** [comment]
I'll begin work on this shortly

**Comment by DrewAPicture** [comment]
@sunnyratilal @pippinsplugins asked me to put some time in on this this week so happy to take an initial stab at it f you already have a lot on your plate. :)

**Comment by DrewAPicture** [comment]
Started a PR: #5458

**Comment by DrewAPicture** [comment]
Definitely running into some road blocks after converting a few classes to use static fixtures. Probably the biggest culprit is overall test pollution and how some tests are seemly reliant on modifications made in adjacent or similar tests.

Each test should theoretically be decoupled from any others, or use PHPUnit dependencies if they truly dependent on other test methods passing. This is somewhat the purpose of the `setUp()` methods, and also part and parcel about doing clean up to restore the current state once a test is finished. Lots of work left to do.

As said in Slack yesterday, the good news is that the tests are failing _faster_ now :-)

**Comment by cklosowski** [comment]
Closing this out as it is not something we need to focus on at the moment. We've sped them up considerably considering how many more assertions we have in 3.0, and moving to BuildKite has made this a faster system to run the matrix of tests on.
