### ISSUE TITLE
Standardize placement of translation files in ecosystem

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/easy-digital-downloads#5486]
Knowing where to place your translation files in EDD and EDD Extensions can be a major pain point for customers.

EDD Core has it pretty well figured out because it looks in quite a few different places - with a priority on looking in the wp-content/languages/plugins/easy-digital-downloads/ directory - which is a really nice and organized place to put them.

**Proposal:**
Introduce a language loader function in EDD Core which can be used by extensions to find location files. It would accept the textdomain as a parameter and put a priority on looking in the directory mentioned above with fallbacks to other typical language directories and finally falling back to use the version in the plugin's language directory. Extensions would then be updated to use that core function to load their translation files.

**Comment by cklosowski** [comment]
Now that we've bumped our minimum version of WordPress we can use their system for languages by having them put into the `wp-content/languages/plugins` directory
