### ISSUE TITLE
Add set of classes to payment status labels

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#5570]
Add classes around output of payment status labels. A few things to note:
1) It should be able to be targeted by front end vs backend
2) All statuses should have a similar class like `edd-status-label` (as an example)
3) We should output the raw `post_status` as a class as well, in a `strtolower` method, so that a specific class can be targeted, even custom statuses registered by extensions.

**Comment by SDavisMedia** [comment]
@cklosowski what status output are you referring to? Everything from purchase receipts to payments table? Let me know the scope you had in mind here.

**Comment by cklosowski** [comment]
Yeah, I was thinking anywhere we output a payment status, it would make sense that someone could want to customize the status labels on the front end easily as well.

**Comment by cklosowski** [comment]
This was done in 3.0. In the admin and on the purchase history we've added the order status as a class.
