### ISSUE TITLE
EDD_Payments_Query doesn't work for filtering orders of non-published orders (and related issues)

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#5680]
EDD_Payments_Query (and subsequently edd_get_payments) allows for the passing of an array of downloads to search for orders containing that downloads. It also allows for the passing of an array of order statuses to filter for those.

If you try to search for orders containing a download or one of multiple downloads, the EDD Payments Query will return only the orders of published status (even if you use the status array to tell it more statuses) and even then, it will only give you some of the post statuses.

The reason for this goes to how EDD knows an order contains a product, in terms of querying. When EDD on the edit screen wants to know what products are in an order, it simply pulls it out of the order meta key and displays them.

However, when we go to do searching, meta key searching in WordPress already isn't performant, but its made even worse by the fact a long time ago we decided to put the download IDs inside of a double serialized array with other stuff. So when we made edd_get_payments, and later EDD_Payments_Query which it now wraps, using this meta wasn't an option for performance reasons.

When an order is completed in EDD, what we do is make a sales log, that is a post of post type `sales_log` with the post parent set to the download it goes to, for each download in an order. Let's say an order contains download ID 5 and 6. When the order is completed, along with the order post type item for the purchase, you'll find 2 new `sales_log` posts with a post parent of 5 and 6 respectively.

This allows us to do things like recount sales for a download (simply sum the number of rows) easily. 

It also lets us query shop orders and filter those containing only specific downloads, since we can simply radius the search by selecting the unique order ID's from the sales_log post items containing the post parent of the downloads we want, and then collecting the orders involved, and filter further on other parameters once those are collected.

The problem is right now, EDD only makes those sales_log post items, when an order goes from `pending` to `completed`. And if the order changes from `completed` the sales_log items for the order are deleted. 

What this means is, despite the fact we allow orders to be filtered by downloads and post status, we cannot find any orders containing 1 or more downloads outside of the completed post status. This hugely reduces the ability to use this query system quite a lot.

This wasn't always the case either. Restoring a very old version of EDD allowed me to see that when using edd_get_payments, this used to be possible. This also causes bugs. For example, if you want to view all of the orders containing a download, you cannot do so in the frontend, in the backend or programically.

This causes a ton of bugs within EDD's own experience.

For example, EDD allows you to search by download on the payments page using the syntax `#{download_id}`. If you make 2 orders (one published, one revoked), each with download ID (arbitrary but for example let's say) 28, and then try searching for `#28`, you'll 2 bugs:
- First, the revoked one won't show, regardless of what screen you are on. This means that you can't find these orders from either the all payment status, or even more weirdly, the revoked status filter screen
- Second, and possibly unrelated, the count for posts found on every status displayed is always 0

There are more issues (for example with exporting and the like), for example, the download stats claim a download is purchased 3 times, but can only find 2 instances: http://cloud.supportally.com/3C2B373A2k1G

Even worse, this means extensions that previously relied on this feature can't do so. For example, FES has a bug open where if an order is changed from complete to pending the vendor table has the wrong order. This was reported a while ago before a change occured.

At one point, EDD used to make logs regardless of status, but in the query, reflected any items with a log as a completed purchase. So in FES, this meant while it found every order correctly, EDD would label them all as complete on the order view table. On the edit screen, we pulled directly from the individual order meta so this wasn't an issue. However, this bug was indirectly fixed by this new  one.

**Comment by chriscct7** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5378

**Comment by chriscct7** [comment]
I should note, part of the reason it took so long to report this was because I assumed there was unit tests that would have covered this type of query, but there's not, and there really should be some, so tagging as such

**Comment by chriscct7** [comment]
https://github.com/easydigitaldownloads/edd-fes/issues/1189 has details of another addon for EDD that's run into this same issue

**Comment by pippinsplugins** [comment]
Let's see if we can get this fixed for 2.8.

**Comment by chriscct7** [comment]
I should've also noted, if you take an order from pending -> complete (normal order flow), you can occassionally (for some reason doesn't always 100% work) take the order back to pending and then to complete to get the meta. Thus, it's also probable there exists on most large EDD sites, orders which cannot be found because the sales_logs are not present. It might be advisable to investigate this, and also have a routine in the 2.8 upgrade path that goes through each order and ensure teh sales_logs exist, since that routine will need to be written anyway to correct the querying

**Comment by cklosowski** [comment]
Part of me thinks 2.8 could take this on, but part of me also thinks we can fix this VERY easily and more accurately with better performance with #4576. I was thinking about this the other day that with a payments table and payment tables item, we could VERY easily query all payments that contain an item regardless of status...and could even take it further wth the proper meta tables to have payments that contain a specific price ID of a specific Item.

I hate to put this a little further, but I think we can fix it 100% without a 'hack job' with custom tables, which should be in 2.9 (at least that's the current goal)

Thoughts @pippinsplugins @chriscct7

**Comment by pippinsplugins** [comment]
I'd rather wait to fix this until #4576 is complete.

**Comment by chriscct7** [comment]
I agree but we also need to consider the backwards compatible considerations of this. I am all for moving payments to a custom table. I definitely think its the future. That being said, do we have any thing or any extensions that use sales logs?

Now personally, I'm 100% for eliminating sales logs. But, we also need to consider the time until custom tables are a thing. Let's assume for arguments sake, the development takes a week, because most of the code required can simply be adapted from earlier work on custom tables and from there it's just wrapping calls. The real time is going to be testing this. This will need to be tested more than anything ever tested in EDD. Also for the time being we will keep having to do sales logs, even with #4576. Imagine someone uprading EDD and they run into some obscure bug, and then they download. Now all of their orders from the time between upgrade and downgrade will be lost. This is something we have to consider. We cannot, in the case of orders, which is mission critical and in the case of EU users, a legal obligation to maintain perfect records of, entertain the possibility this upgrade will be flawless. Do we and should we try to make it perfect? Yes, but this is one thing we must plan ahead and prepare for there being an issue. Hopefully nothing happens, but this risk cannot be ignored.

So my opinion is we should fix this at minimum for current orders being made, and then after we move to custom tables we won't really need to worry about doing a routine for previous orders.

**Comment by ashleyfae** [comment]
Closing this as it's solved in 3.0.
