### ISSUE TITLE
Feature Proposal: MCE Shortcode Builder with Live Previews

### ISSUE THREAD

**Issue by danieliser** [awesomemotive/easy-digital-downloads#5715]
I have gotten pretty much all of the major kinks out of this feature via my plugin Popup Maker. I have already ported quite a bit of the code into a more modular version that wouldn't be that difficult to adapt for EDD.

This module would add:

- [ ] New button on MCE editor toolbar to insert custom shortcodes without need to check docs.
- [ ] Live rendering in the editor including support for stylesheets. Supports static template & ajax do_shortcode rendering.
- [ ] Shortcodes are editable via a tabbed modal form that is 100% JS rendered and supports passing settings style field arrays from PHP making it extremely extendable. This all is built to match the existing admin UI.
- [ ] Edit / delete shortcodes just like galleries or media using the same modal forms.
- [ ] New EDD_Shortcode abstract class that each shortcode would extend.
- [ ] Already tested & used in over 60k installs.

Added benefits for me are that via your code reviews and beta testing I can make it even better.

Screenshots of the latest version (v1.6.1-beta) in action which includes ajax rendering. The rest existed since v1.4

![screenshot from 2017-05-08 02 21 45](https://cloud.githubusercontent.com/assets/847818/25792539/2b8cd37c-3395-11e7-932c-0924212761cd.png)
![screenshot from 2017-05-08 02 21 51](https://cloud.githubusercontent.com/assets/847818/25792540/2b98a5da-3395-11e7-8f57-18a2396877c6.png)
![screenshot from 2017-05-08 02 21 56](https://cloud.githubusercontent.com/assets/847818/25792541/2b9fc720-3395-11e7-86bd-6f494bad884a.png)

**Comment by pippinsplugins** [comment]
It's a really nice feature, but I have to ask: is there really that much benefit to this? While shortcodes are not the most user friendly feature in the world, this seems overkill for a plugin like EDD that does not depend on overly complex shortcodes with dozens or hundreds of options.

That may just be me and I'd welcome differing opinions.

**Comment by chriscct7** [comment]
I actually like (the inline part quite a lot) this as a user enhancement but given gutenberg is coming along, it'd be weird to add this and then have to remove it if/when they finish the block system for shortcodes. Might be worth waiting to hear State of the Gutenberg at WCEU before moving on this.

**Comment by danieliser** [comment]
@pippinsplugins - For users it makes it both incredibly intuitive to insert shortcodes, even when the options are simple or complex, and it allows the visual preview in the content, making it much quicker to create content without hving to check the draft previews.

For your team it serves another purpose, support reduction. If the builder does its job, you likely won't ever see support requests reguarding shortcodes again, with the exception of feature requests.

@chriscct7 - After playing with Gettenburg a bit, and having read all the news I could find, I'm not sure itss worth waiting for several reasons:

- It could still be a long time before it ever actually makes it into core, if it takes another 2 years, leaves a long gap to fill this need.
- Added benefit that the way this is already set up, it can easily support rempaping to Guttenburg with minimal work. To clarify if you install Popup Maker now, you not only get our shortcode builder, but if you have the Shortcake UI installed these same shortcode fields will work there as well. IE I define them once, and no matter which builder you decide to use, we can easily remap. For example see our core Shortcode class, which inits both builders if present:  [code](https://github.com/PopupMaker/Popup-Maker/blob/master/includes/class-pum-shortcode.php#L217-L302). Because of this, registering new modules for Guttenburg would be a similar process built of the existing work already done, making it a much easier transition when it does happen.

Though I would love to contribute the to your project, I understand if you opt out. That said my plan was to modularize this as much as possible when I ported it for EDD. In doing so it becomes a reusable library we can all use in our other plugins as well, I'm sure between PippinsPlugins, AffWP, EDD (with all its extensions) etc there would be a decent need for this.

**Comment by danieliser** [comment]
I will also add that since the modal, tabs, form & fields are all generated using JS templates, the underlying code for doing those renderings can easily be reused. For instance a new plugin I am working on has a single tabbed metabox rather than multiple metaboxes. That metabox is generated on page load rather than rendered with PHP. It was built using the same underlying _.js models and views as this is, so you could start re-using it elsewhere too.

**Comment by Basilakis** [comment]
@danieliser Have u worked more on that?

**Comment by danieliser** [comment]
@basilakis - if you mean the edd features described here no, not gonna do so without explicitly bribed asked to. Not sure @pippin and team are up for this currently.

If you mean the form JS library absolutely. Actually released a feature plugin to demo it and maintain the form lib itself. Find it here : https://github.com/danieliser/WP-JS-Form-Sample-Plugin

**Comment by danieliser** [comment]
@basilakis I will add that the lib is now in use for useahoy.com and Popup Maker. For PM v1.7 I'm using it for most popup post meta options, the plugins global settings page and the shortcode builder.

**Comment by cklosowski** [comment]
I'm going to close this as something we won't pursue as we are in the process of building blocks to handle this type of system.
