### ISSUE TITLE
Attempt to bust cache on file download URLs

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#5765]
As pointed out by @drodenbaugh in the Post Status eCommerce Slack, sometimes on WPE it takes a manual flush of cache in order to have file download links not give expiration notices. it was suggested he see if URLs with `eddfile=` in the string be excluded from cache, but we should see if we can bust cache in anyway as well, all while keeping the integrity of the file authorization.

**Comment by pippinsplugins** [comment]
I'm upping the priority on this. Anything we can do to mitigate file download failures is a high priority.

**Comment by cklosowski** [comment]
I've not heard anything about this in years since it was logged. I'm going to close it now, and we can revisit later.
