### ISSUE TITLE
Support for WordPress Gutenberg

### ISSUE THREAD

**Issue by SeanTOSCD** [awesomemotive/easy-digital-downloads#6225]
Make sure everything in EDD works with WordPress Gutenberg. 

Currently in plugin form: https://wordpress.org/plugins/gutenberg/

**Comment by scottbuscemi** [comment]
Is there progress on this?

**Comment by cklosowski** [comment]
We are continuing to monitor it, which at this time is still a moving target. Once we have a more 'this is going into core at this state' we can code to meet any needs.

**Comment by Joel-James** [comment]
This relevant now. Can we get priority here?

**Comment by cklosowski** [comment]
With the release of EDD 3.1, we've included our own blocks into EDD core that should satisfy this requirement.
