### ISSUE TITLE
Free purchases should not be classified as "Test payment" in a download purchase confirmation

### ISSUE THREAD

**Issue by bbstudio-dev** [awesomemotive/easy-digital-downloads#6227]
Free purchases made with the "Free Download" extension appear as "Test payment" in a download purchase confirmation. This is incorrect and looks annoying. Semantically this is not a "test payment". This should be renamed.

**Comment by cklosowski** [comment]
Related #6063

**Comment by cklosowski** [comment]
The problem here is that EDD's reference here is `manual` for the `gateway` of the payment, so in order to properly determine this we'd have to make a change in Free downloads or determine how it was submitted. We can add it to the 'todo' list but it's a lower priority for now.

**Comment by ashleyfae** [comment]
Closing this as it's been renamed to `Store Gateway` in 3.0.
