### ISSUE TITLE
Default new sale notification shows "Test Payment" instead of "Free Purchase"

### ISSUE THREAD

**Issue by brashrebel** [awesomemotive/easy-digital-downloads#6319]
Reported by [a customer](https://secure.helpscout.net/conversation/507574443/74316/), I've confirmed that for $0 purchases if the {payment_method} email template tag is used, "Free Purchase" is shown but the default email results in "Test Payment" being displayed which is not technically correct.

I've traced it to [this line](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/functions.php#L116). Right [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/emails/template.php#L210), the label is fetched but in that context, `$_GET['id']` is not set so back [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/functions.php#L118) the condition isn't met and the label is not overridden from "Test Payment" to "Free Purchase".

I didn't figure out exactly why it works properly [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/functions.php#L118) but it does.

**Comment by cklosowski** [comment]
It's due to the fact that this is an 'admin label' not a 'label'. The emails and front end do not use this function to swap that name out.

**Comment by pippinsplugins** [comment]
We've had a lot of people be confused by this. While it's technically not a bug, it's still unexpected behavior and I think we should fix it.

**Comment by nutsandbolts** [comment]
Making a note to notify this guy when this has been resolved: https://secure.helpscout.net/conversation/994905466/135837?folderId=2657915

**Comment by cklosowski** [comment]
This is no longer an issue, with the adjustments made for 3.0 to call anything that does not collect actual payments as the 'Store Gateway'.
