### ISSUE TITLE
Payment mode is not recorded for all payments

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/easy-digital-downloads#6326]
I haven't totally figured out why yet, but the payment mode (live/test) is not being stored for all payments. Specifically, renewal payments done through EDD Recurring do not always have the payment mode stored in the database (_edd_payment_mode). 

The only thing I can seem to see as a cause for this is that the "mode" must not be getting added to the "[pending](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/62a524c7b890d7daa57eab1921de938189d094f7/includes/payments/class-edd-payment.php#L866)" array in the EDD_Payment class. I haven't yet found where that is being missed for renewal payments though. Just wanted to log this while I am searching for it.

**Comment by mintplugins** [comment]
Affected Customer here:
https://secure.helpscout.net/conversation/504331870/74021?folderId=749231

I have also replicated that the _edd_payment_mode meta does not exist for renewal payments on my live testing site as well

**Comment by pippinsplugins** [comment]
Right now the `mode` is only set when running `edd_insert_payment()`.

EDD Recurring (where we're seeing this) is using EDD_Payment->save(), which triggers the private `insert_payment()` method.

To resolve the issue, we just need to move the `mode` logic from the global `edd_insert_payment()` function to the private `insert_payment()` method of `EDD_Payment`.

**Comment by cklosowski** [comment]
This is now happening in EDD 3.0.
