### ISSUE TITLE
Purchased Downloads on Customer details page shows downloads from Pending orders

### ISSUE THREAD

**Issue by ericnicolaas** [awesomemotive/easy-digital-downloads#6337]
We have a customer who has several Pending orders, and one Complete order. The Complete order was for our "Charitable Plus" product; most of the Pending orders are too, but one of the Pending orders was for "Charitable Recurring Donations".

Confusingly though, the Purchased Downloads is incorrectly listing both Plus and Recurring Donations as purchased items:

<img width="667" alt="screenshot 2018-01-30 11 32 05" src="https://user-images.githubusercontent.com/676582/35544321-40c3ad26-05b1-11e8-8ed6-5871a47fdf8c.png">

**Comment by SDavisMedia** [comment]
@ericnicolaas sorry for the delayed reply here but go ahead and open up a support ticket if you haven't already. https://easydigitaldownloads.com/support/

I did a quick test of a few different types of purchases that result in pending records and I couldn't replicate the behavior. So please allow support to troubleshoot with you and once you all have more details, we'll determine if there's a bug or not.

**Comment by SDavisMedia** [comment]
@ericnicolaas I'm sorry. I'm completely wrong. That's definitely a bug we'll get taken care of. I see no reason why pending purchases should display there. Thanks!

**Comment by SDavisMedia** [comment]
@ericnicolaas can you also share a screenshot of the **Recent Payments** section on that Customer Details page? I'm going to assume it shows one Completed payment of Charitable Plus and one Pending payment of Charitable Recurring Donations.

I'm seeing some odd behavior (not sure if it's intentional or not) where a new pending purchase literally hijacks the payment ID of a previous pending purchase. I'm willing to bet the customer just "created" a series of pending purchases and each one replaced the other... ending with Charitable Recurring Donations.

That still leaves the discussion on the table for whether or not we should even be showing a row in Purchased Downloads when the row is associated with a non-Complete purchases, though.

Thoughts, @cklosowski?

**Comment by ericnicolaas** [comment]
![screenshot 2018-02-05 15 04 46](https://user-images.githubusercontent.com/676582/35789801-3be7b6c4-0a86-11e8-840d-8e6b7d16dc3a.png)

494063 and 499306 were the Recurring Donations ones. It's worth noting that the later one (499306) happened six minutes before the successful payment for Plus.

**Comment by cklosowski** [comment]
I would vote the `Purchased Downloads` section should only output things that have been completed, not abandoned or pending payments.

By that point they have not _purchased_ it.

**Comment by SDavisMedia** [comment]
Agreed. :+1:

**Comment by SDavisMedia** [comment]
@cklosowski if we choose to only show Complete payments here, how do you feel about completely removing the Status column? I think it makes sense to remove it and maybe even change `Recent Payments` to `Completed Payments`. 

We should still only show the 10 most recent, but maybe add a link to view all payments by the customer, linking back to the payments table filtered by that customer.

**Comment by pippinsplugins** [comment]
The `Recent Payments` section should at least show `Refunded` and `Complete` purchases, not just complete, so I don't think that status column can be removed.

**Comment by SDavisMedia** [comment]
Yea I agree with that. Didn't even think about `Refunded`, considering it was `Complete` at one point.

Y'all good with just those two statuses? The main thing is getting some of these other records out of this view as they can be temporary, overwritten, or just cause confusion.

**Comment by pippinsplugins** [comment]
We need to also allow extensions, like Recurring Payments, to add additional statuses here.

**Comment by cklosowski** [comment]
Thanks @zkawesome
