### ISSUE TITLE
Add Yesterday and Estimates to the EDD Sales summary

### ISSUE THREAD

**Issue by chriscct7** [awesomemotive/easy-digital-downloads#6402]
One of the most common things I think a EDD user does if they're a daily user is log in and see how much money they made yesterday. The EDD sales widget on the dashboard includes numbers for current month, last month, and today, but doesn't include one for yesterday, which I think would be more common of a request.

To balance out adding a `yesterday` in terms of needing something for the right column, I would propose that EDD also adds an Estimates item, using the estimates of sales and total for this month, found already on the reporting page.

**Comment by cklosowski** [comment]
The estimates were removed from the reports in 3.0. We can look at adding it back possibly, but we're revamping the entire dashboard widget in the near future.

We'll look into the feasibility of an estimate, as we rebuild that.
