### ISSUE TITLE
Integrate [edd_login] with 2 factor plugins

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/easy-digital-downloads#6404]
A customer has requested that the [edd_login] shortcode be integrated to work with 2 factor authentication plugins like these. If this is possible, I'm not sure if each plugin needs to be integrated separately, or if a single change can make them all integrate. 

https://wordpress.org/plugins/miniorange-2-factor-authentication/ 
https://wordpress.org/plugins/two-factor-authentication/ 
https://wordpress.org/plugins/two-factor/

**Comment by mintplugins** [comment]
Customer Ticket:
https://secure.helpscout.net/conversation/531298252/77023/

**Comment by cklosowski** [comment]
Thanks @mintplugins

**Comment by cklosowski** [comment]
I'm closing this out. We are currently using a two-factor plugin on the EDD site, with the EDD Login block and they play nicely together as is.
