### ISSUE TITLE
Add release-focused Grunt tasks

### ISSUE THREAD

**Issue by SeanTOSCD** [awesomemotive/easy-digital-downloads#6476]
Continued from: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6439

The last issue was focused more on tasks that don't necessarily have to be tied to a release. This one will aim to add tasks that actually focus on the release.

**Comment by SDavisMedia** [comment]
Been working on this in my own personal repo, since it requires a bunch of real tests. https://github.com/SDavisMedia/grunt-bruh

Not having much luck at the moment but I'd say it's still coming along. Won't come back here until I have something solid working over there.

**Comment by cklosowski** [comment]
With 3.0 we've moved to a complete webpack and node build script based on the WP Scripts work. Closing this as we don't need to refactor at this time.
