### ISSUE TITLE
Search for partial information in Customer page

### ISSUE THREAD

**Issue by webzunft** [awesomemotive/easy-digital-downloads#6626]
## Enhancement Request

I would like to be able to search for partial information from customers on the customer page, e.g.

"example.com" should find users with an email address that includes "example.com".
"Thoma" should find clients with the name "Thomas" or email "thomas@example.com" as well

If that is not possible by default, maybe allowing "Thoma%" would be an option.

### Justification or use case

I get quite a lot requests from users who can’t remember who made the purchase or which email address they used. Being more flexible here would help a lot.

**Comment by cklosowski** [comment]
We have a very similar issue that should solve some partial name searches in #6774.

I'm going to mark this for 3.1, so we can come back to it in case the fixes in 3.0 don't completely cover the cases here.

**Comment by zackkatz** [comment]
This would be huge for me! I have to open up my DB application to search the customers table well.

**Comment by cklosowski** [comment]
As it stands due to the new DB class going into 3.0, there are major improvements to the search functionality just out of the box, which is why we'll re-assess this once 3.0 is shipped and see if there is more we can improve upon it.

**Comment by cklosowski** [comment]
This is working in EDD 3.0.2.1. You can search the following as requested:
1. `@domain.com`
2. Name search is full or partial (does not support first X characters or `%` queries)

We can look at further improvements in the future, but as it stands the customer search is far improved for partial searches.
