### ISSUE TITLE
Introduce [download_categories] shortcode

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#6659]
### Explain your enhancement (please be detailed)

Most popular eCommerce sites have categories listed usually on the homepage (or elsewhere on the site), usually with a thumbnail image, the title of the category, either within the image itself (overlaid) or under the image. Sometimes a short description is also included on certain sites.

This allows customers to easily navigate to a specific category quickly and have a good idea what's going to be included. WooCommerce already features this short-code and it makes a modification (enhancement) to the category taxonomies to include thumbnail support on a per-category basis.

If the thumbnail is not set it either pulls it from a product featured image within that taxonomy or displays a small grid of product images within the thumbnail in a 2x2 arrangement. I believe EDD should have something similar to this and I propose [download_categories] for this. It could accept different parameters that control the behaviour and look of the output.

Here are some examples for reference:

https://www.target.com/
https://www.walmart.com/
https://www.ebay.co.uk/

### Justification or use case

As per the above, it would be useful for building homepage layouts and featured product categories.

**Comment by davidsherlock** [comment]
Another for reference:

https://www.etsy.com/uk/

**Comment by cklosowski** [comment]
I think this could be useful, but I would suggest we wait until after we get through the Gutenbergification of EDD first. I'd like to not just support a shortcode but a block as well. We should hold of on new shortcodes until we can look at how blockification of things is done, so I'm going to leave a milestone off this for now.

**Comment by cklosowski** [comment]
Now that we've added a block for terms, we can close this, as we can now easily output a category or tag list.
