### ISSUE TITLE
Checkmark 'Test Mode' when using a filter to turn on test mode

### ISSUE THREAD

**Issue by scottbuscemi** [awesomemotive/easy-digital-downloads#6712]
### Explain your enhancement (please be detailed)

When using the `edd_is_test_mode` filter to enable test mode, the checkmark in Payment Gateways > General can still be toggled on/off. This checkmark should be disabled and showed as checked to show that the filter is in effect.

**Comment by cklosowski** [comment]
Combined with #7098, we could just do some QOL updates for developers and devops types here.

**Comment by cklosowski** [comment]
Going to fix this alongside #7098, but the only real way to do this is to know all the callbacks and we can't really check their conditions, so it will only detect if someone is using this filter:
`add_filter( 'edd_is_test_mode', '__return_true' );`
