### ISSUE TITLE
Allowed memory size using recount / reset earnings tools

### ISSUE THREAD

**Issue by boluda** [awesomemotive/easy-digital-downloads#6756]
### Expected behavior
When I run the reset / recount tools I expect them to work.

### Actual behavior
When I run the reset / recount tools I expect them to work they trigger this fatal error:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 524288 bytes) in /wp-includes/wp-db.php on line 2344
`
### Steps to reproduce the behavior
1) Run the "Reset store" or "Recount Store Earinings and Sales"
2) That's it. That triggers the error.
3) Same error Pippin got [here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3633#issuecomment-168235827)

### Information (if a specific version is affected):
Store with 10.000+ clients and 90.000+ payments
PHP Version: 7.0
EDD Version (or branch): 2.9.4
WordPress Version: 4.992
PHP MEMORY: 128MB

**Comment by cklosowski** [comment]
With the release of EDD 3.0 these tools no longer have to do massive queries that can reach these limitations as most of the hard work is done in MySQL.

I'm going to close this out for now, and if we run into any more issues with it, we can re-open and assess it from there.
