### ISSUE TITLE
edd_login redirect to page its placed on

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#6847]
### Expected behavior
When placing [edd_login] on a page, after i login i expect to be redirected back to the same page the shortcode is placed on as per the documentation

### Actual behavior
Instead it redirects to the purchase history page

### Steps to reproduce the behavior
1) In EDD General settings leave Login Redirect Page empty
2) Add [edd_login] to a page
3) Login using a user account and you are redirected to the purchase history page instead of the page where the short code is on

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): latest

WordPress Version: latest

Any other relevant information:

### Explain your enhancement (please be detailed)

Reported by a customer. A quick workarround is to use the redirect="" param in the short code but in his use case he has to make a bunch of short codes for his setup. It would be ideal if no redirect param is set and Login redirect page is empty to get back to the page you were logging in from.

**Comment by misulicus** [comment]
Related issue https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6847

**Comment by cklosowski** [comment]
We'll support this in the new block, but won't be adding it to the shortcode.
