### ISSUE TITLE
Feature: exclude_ids in downloads shortcode

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#6974]
### Expected behavior
Be able to exclude specific downloads when using the `[downloads]` shortcode by passing a parameter like `exclude_ids`

### Actual behavior
At the moment its not possible to exclude downloads based on ID

Any other relevant information:

### Explain your enhancement (please be detailed)

Customer requested here https://secure.helpscout.net/conversation/679783015/91670?folderId=180499 and i believe this has been raised before in the past.

**Comment by cklosowski** [comment]
This isn't too difficult of a change. Currently the `id` attribute is just directly converted to a `post__in`. We would just need to use whatever the exclude attribute is and map it to `post__not_in` and it should just work out of the box.

**Comment by cklosowski** [comment]
I'm going to close this, as we'll be moving towards adding new features in blocks. @robincornett, As we work on the new blocks for EDD, let's maybe consider this as a possibility for the downloads query?
