### ISSUE TITLE
Reorganize Reports Export and Import/Export Tools

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#7036]
I'm proposing we reorganize or rethink the location of some of the export tools. Some have duplicate purposes between Reports Export and Import/Export tools but causes confusion when they are not where they are expected. Which depends on how you are using the exports.

From the perspective of Exporting and Importing data from one site to another, Download Products and Orders are missing from `Tools > Import/Export`. It makes since that they are also considered a reports. It's just confusing that there is not reference to them in the Import/Export tools tab.

**Suggestions on how this could potentially be addressed:**
1) Move everything in `Reports > Export` to `Tools > Import/Export`. Keep the Export tab under Reports but have it link to `Tools > Import/Export` when clicked. 
2) Referece `Reports > Export` in the Import/Export tab so it's more easily accessible.
3) ~I would like to see Download Products moved to `Tools > Import/Export`. Since Order export could be used to import, it should be referenced via the Import/Export tab but linked to Reports since that's likely where it belongs.~ 

I'm thinking Option 1 would make the most since to place everything in one location and avoid having tools with duplicate purpose in the wrong location. This prevents confusing any customers who are use to the existing locations.

**Comment by cklosowski** [comment]
I'm going to close this, as I think we've done a bit better organizing things and moving just product/sales importers to the tools, and the only export on the tools is settings, which doesn't make sense in reports.
