### ISSUE TITLE
Feature request: Allow Test Mode to be activated in an environment via a constant in wp-config.php

### ISSUE THREAD

**Issue by planetahuevo** [awesomemotive/easy-digital-downloads#7098]
Hi, 

I would like to be able to put my shop in test mode when I am using the staging copy.

So far I have found this code: 
```
/**
 * Is Test Mode
 *
 * @since 1.0
 * @return bool $ret True if test mode is enabled, false otherwise
 */
function edd_is_test_mode() {
	$ret = edd_get_option( 'test_mode', false );
	return (bool) apply_filters( 'edd_is_test_mode', $ret );
}
```
But that means I need to install a custom plugin and activate it on my staging. Can be done but, 
would be possible to have an easier way to do this. 
For example, 2 suggestions: 
A) having a file (.maintenance or similar) on the edd plugin folder that when is there, the shop is considered "test mode". Removing the file will remove the test mode status. 
B) having a variable on wp-config, that will set the shop on test mode, with true or false. 
So it will be easy to add that to the staging creating process.

What do you think? 
Is this something that can be added in the future? 

Thanks

**Comment by cklosowski** [comment]
@planetahuevo Thanks for the suggestions, something I might suggest for now until we can look further into these as options would be a custom MU plugin. You mentioned that you can add something to the wpconfig on creation, is it also possible to create a single file in the `wp-content/mu-plugins` directory during stating creation?

If you can make a single file in that directory named `edd-test-mode.php` then all you'd need is the following in the contents:
```
<?php
add_filter( 'edd_is_test_mode', '__return_true' );
```
By adding that into a file in the `mu-plugins` directory, it will be automatically enabled as a must use plugin, and `edd_is_test_mode` will always return `true`.

As far as the suggestions, I think the best route in the future would be able to define a constant in the `wp-config.php` file like a `EDD_TEST_MODE` constant (much like `WP_DEBUG`).

While a maintenance file would be possible as well, it would pose some more risk over a constant in the wp-config.php. We can look into that one as well, it might just come at a later date.

I'm going to rename the issue and my suggestion is that we add a constant for `EDD_TEST_MODE` which overrides the setting at all times, however it will still pass through the filter.

**Comment by planetahuevo** [comment]
@cklosowski Thank you for the reply!
I will work with the MU plugin for now, and I agree with you that the constant is a better solution. 
Thank you for considering it! 
Happy new year. :)
