### ISSUE TITLE
"Download Log" action/link within Customer view table not properly filtering download logs

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#7151]
### Expected behavior
A customer (https://secure.helpscout.net/conversation/766574668/99688?folderId=1847245) reported an issue with the "Download Log" link on the customer's table not filtering the log view and showing the download log entries for all customers. I replicated this on one of my live sites also.

### Actual behavior
Clicking the "Download Log" on any customer (regardless of customer or if they have a WP user account) will show the download logs for all customers.

### Steps to reproduce the behavior
1) Click on the "Download Log" table view link/action for any customer on your website/store.
2) The "Easy Digital Downloads Reports" will show the file download logs for all customers.

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.11

WordPress Version: 5.0.3

**Comment by cklosowski** [comment]
We'll likely review this on 3.0 to see if that solves any issues.

**Comment by cklosowski** [comment]
Confirmed this is fixed in 3.0.
