### ISSUE TITLE
Add @property tags to classes which use __get to access private methods.

### ISSUE THREAD

**Issue by danieliser** [awesomemotive/easy-digital-downloads#7248]
Classes like EDD_Payment have tons of private properties that are expected to be directly accessed via magic __get methods.

Unfortunately this is breaking PHP Storm & other IDE inspections

![image](https://user-images.githubusercontent.com/847818/57322724-33710a00-70d2-11e9-8b35-b3ef4fff4f04.png)

Adding `@property array cart_details` to the `EDD_Payment` class comment resolves this correctly and also
- shows up for auto complete when you type `$payment->`
- alerts our IDE of what that property type will be, in this case an `array`

![image](https://user-images.githubusercontent.com/847818/57322773-62877b80-70d2-11e9-9bfc-1734006d796d.png)

![image](https://user-images.githubusercontent.com/847818/57322823-821ea400-70d2-11e9-922f-b8737261fc58.png)

Heavily suggest investing a minimal amount of time into adding property comments to each of the main EDD core classes.

Happy to submit a PR myself with them slowly over time, but you guys could probably do it in a half hour.

**Comment by spencerfinnell** [comment]
@ashleyfae I know you've been pushing some related code standards lately... my IDE and PHPStan are not enjoying these "protected" properties either. Happy to help with the effort to add this documentation to maybe sneak it in before 3.1. 😇

**Comment by ashleyfae** [comment]
@spencerfinnell Sure thing! I think `release/3.0` is actually looking pretty good here. https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L17-L59

I think all the new stuff is documented as well. We could just copy that over to 2.x.
