### ISSUE TITLE
Payment History discount search is not reliable for certain codes

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#7364]
### Expected behavior
Searching discount codes under Payment History should properly filter orders with the discount code being searched.

### Actual behavior
Discount code search has mixed results with generic terms.

For example, searching for the code `discount:50off` works as expected. On the other hand, searching for `discount:free` seems to result in any orders with the word free somewhere in the order.

Note, it appears `release/3.0` does not yet support the `discount:` search parameter. No mater what code I use, all order appear.

### Steps to reproduce the behavior
1) Create a discount code
2) Make an order using that discount code
3) Search Payment History for `discount:<CODE>`

### Information (if a specific version is affected):
PHP Version: 7.1

EDD Version (or branch): `master` & `release/3.0`

WordPress Version: 5.2.2

Any other relevant information:
https://secure.helpscout.net/conversation/919915466/126778?folderId=1847242

**Comment by dgoldak** [comment]
Replicated on test site. For example, if search for `discount:free`, there should be no results:
<img width="1487" alt="Screen Shot 2019-08-02 at 4 52 09 PM" src="https://user-images.githubusercontent.com/30910807/62400756-03f16280-b546-11e9-9c8d-d6f59a3ad564.png">

**Comment by cklosowski** [comment]
We can't solve this in 2.9.x since discount codes are part of the payment meta array, which is a serialized array of the order contents, which if a product contains the word 'free' or any mention of the word 'free' is in the order cart it will show. This is due to the fact that we ca only use a MySQL "LIKE" query.

I'll look into the 3.0 thing.

**Comment by dgoldak** [comment]
Confirmed this is not working for the `txn:` search in `release/3.0`.

Search results should only return one order, but my search contained  no filtered results. It appears all orders appeared in the search results.

**Comment by cklosowski** [comment]
@dgoldak I would not have expected it to work right away for 3.0. We’d have to rebuild the search functionality a bit.

**Comment by cklosowski** [comment]
Punting to a minor release after 3.0, since this is an existing bug in 2.9.

**Comment by cklosowski** [comment]
This appears to still be an issue in EDD 3.0.3. I tried searching for a non-existant discount code and got a standard filtered list of orders, however adding an existing discount code filters it just fine.
