### ISSUE TITLE
Unit tests not compatible with PHPUnit 7

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#7435]
### Expected behavior
I expect to be able to run PHPUnit tests locally with PHPUnit version 7.

### Actual behavior
Unit tests fail with the following error:

> Fatal error: Declaration of SpeedTrapListener::addError(PHPUnit_Framework_Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in C:\wamp\www\edd3\wp-content\plugins\easy-digital-downloads\tests\phpunit\speed-trap-listener.php on line 7

### Steps to reproduce the behavior
1) Use PHPUnit version 7.
2) Run EDD's unit tests.
3) See above error.

### Information (if a specific version is affected):
PHP Version: 7.3.7

EDD Version (or branch): both `master` and `release/3.0`

WordPress Version: 

Any other relevant information: It looks like our Travis config uses PHPUnit 5.7, and the unit tests were presumably written to be compatible with that. My guess is there's a compatibility issue and some stuff would need to change to be compatible with PHPUnit version 7. At some point it's worth updating our Travis config and tests to use PHPUnit version 7, as version 5 is no longer supported.

https://phpunit.de/supported-versions.html

PHPUnit version 7 EOL is February 7 2020, however WordPress core does not yet support version 8.

**Comment by cklosowski** [comment]
As a note, one of the reasons was WP core support. Since we run a matrix
from WP 4.4 (4.7 for 3.0), those older WP versions have limited PHPUnit
support.

**Comment by spencerfinnell** [comment]
Trac ticket for PHPUnit 8.x support: https://core.trac.wordpress.org/ticket/46149

Handbook recommends PHPUnit 7.x: https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/

If 3.0 is bumped to require WordPress 4.9.x is there a need to support the older versions? Is there an easy way to see which versions of WP are compatible with which versions of PHPUnit?

**Comment by cklosowski** [comment]
If we can move to PHPUnit 7.x that'd be awesome, would just have to rewrite a bunch of our framework I think.

**Comment by ashleyfae** [comment]
PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8180 makes tests pass with PHPUnit 7.x if you manually remove the speed trap listener.

**Comment by cklosowski** [comment]
Closing as we've handled this in a separate branch and have moved to PHPUnit 8.x
