### ISSUE TITLE
Investigate better locale handling when presenting money amounts.

### ISSUE THREAD

**Issue by mintplugins** [awesomemotive/easy-digital-downloads#7441]
## Enhancement Request
Since many countries share the same symbols for currency, indicating which currency the amount is in could be an important distinction. 

For example, Canada and the US both use the $ sign, but the value of $1 CAD is not the same as $1 USD. Also, the way a currency is written out can vary from country to country. Some might put that differentiator before (USD $1), and some will put it after ($1 USD). 

A customer has requested we look at doing this type of localization on the PHP side:
https://secure.helpscout.net/conversation/995136639/135849?folderId=2965028

Using something like:
https://github.com/predicthq/address-formatter-php

However, Javascript has a lot of functions built in for this such as [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) which would be worth considering as well. 

This isn't something I see happening in the near future, but I wanted to log it for consideration.

**Comment by cklosowski** [comment]
In EDD 3.0 we built an entire 'currency' [localization class](https://github.com/awesomemotive/easy-digital-downloads/tree/main/includes/currency) to handle this, when joined with our Multi Currency addon. EDD Core had to be currency aware for this add-on to work correctly.
