### ISSUE TITLE
Split Purchase Confirmation and View Receipt into 2 distinct templates

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#7603]
### Explain your enhancement (please be detailed)
Carried over from #2304, as a starting point we need to look at splitting our Purchase Confirmation and View Receipt pages into two actual separete pages. They may contain some of the same content sections, but they need to trigger a different template.

### Justification or use case
Many times it is ideal to load retargeting or conversion tracking pixels/code on the purchase confirmation, but the problem right now is EDD uses the same template for both the initial purchase confirmation, or for when a user looks at their receipt anytime after purchase, which can then fire off the retargeting pixel and create inaccurate tracking.

Over the years there have been a number of ‘hacks’ around this in a custom template, but it is time to support two different templates, further allowing these two different contexts to be treated differently.

**Comment by spencerfinnell** [comment]
Some other context: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3391, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3529, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5681

@cklosowski So the idea here is to introduce a completely separate/new page, setting, and shortcode? The shortcode will essentially duplicate `[edd_receipt]` for the first iteration?

**Comment by spencerfinnell** [comment]
Also related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6678

**Comment by cklosowski** [comment]
@spencerfinnell I'm not 100% sure if I want to rip the band-aid off yet, or not, but I feel like if we're going to do this, during 3.0 might be the time, possibly with some backwards compatibility for context.

I'm goign to try and code up what I think is the right solution, including backwards compatibility for this, then in 3.1 we can remove the back compat and move forward.
