### ISSUE TITLE
Logs - Download File Logs Adding Two Items

### ISSUE THREAD

**Issue by spencerfinnell** [awesomemotive/easy-digital-downloads#7768]
### Expected behavior

When I download a file, one log entry should be added to `wp_edd_logs_file_downloads`

### Actual behavior

Two rows are added to the table.

### Steps to reproduce the behavior
0) Set "Download Method" to "Forced"
1) Purchase a Download with one file.
2) Download one file.

`release/3.0`:
- Observe two rows added to `wp_edd_logs_file_downloads`

`master`:
- Observe two logs in Reports > Logs > File Downloads

### Information (if a specific version is affected):
PHP Version: `7.3.7`, `7.4.2`
EDD Version (or branch): `master`, `release/3.0`
WordPress Version: `nightly`

Any other relevant information:

Tested on two separate `release/3.0` installs, and `master`. Using Laravel Valet on all three installs.

**Comment by ashleyfae** [comment]
I can't reproduce this.

Before test (note **8 rows**):

![Screenshot from 2020-04-21 14-11-48](https://user-images.githubusercontent.com/6324272/79870072-4b709500-83da-11ea-8de2-bfa82c0e1640.png)

After test (note **9 rows**):

![Screenshot from 2020-04-21 14-13-15](https://user-images.githubusercontent.com/6324272/79870082-51667600-83da-11ea-905e-b1322b745a77.png)

**Comment by spencerfinnell** [comment]
I just reproduced on another install. I'll try to track something down.

**Comment by spencerfinnell** [comment]
@ashleyfae I only get it twice if using "Forced" Download Method.

**Comment by spencerfinnell** [comment]
Actually, this happens for me on `master` as well.

**Comment by ashleyfae** [comment]
Hm that's weird - I'm also using forced.

![Screenshot from 2020-04-21 14-40-32](https://user-images.githubusercontent.com/6324272/79872738-12d2ba80-83de-11ea-83ca-b426a92df02f.png)

Maybe there's another circumstance we're missing.

But if it's on master as well then we'll dig into this later!

**Comment by spencerfinnell** [comment]
@LisaCee @robincornett Are you able to reproduce this?

**Comment by robincornett** [comment]
It's not happening for me on 2.9 or 3.0; both sites are set to Forced for the download method.

**Comment by slr1979** [comment]
Just found a possible answer to this. I was also experiencing two log entries for every download with both download methods but had only clicked once. Turned out to be pjax.js which allows ajax page refreshing. I had failed to exclude the download link class from the script so the link was being triggered in jquery before the download started as well as onclick. Added the class to the excludes array and bingo, one click, one entry.

**Comment by cklosowski** [comment]
I've seen this happen before on sites that use preloading when hovering links, which makes a call to the URL in the JS console/network tab, to 'pre-cache' the page that is going to be clicked.

There isn't much we can do about situations like this, we see it happen with our Add to Cart links as well. If we can come up with a generalized solution that works for all of the performance optimizing plugins, we can look into it further.
