### ISSUE TITLE
Phase 1: Add template override information to system information file

### ISSUE THREAD

**Issue by shaynesanderson** [awesomemotive/easy-digital-downloads#7827]
## Enhancement Request
Add "template override information to the system information file provided through support requests. 
### Explain your enhancement (please be detailed)
It would be helpful to support to see any/all template overrides that are being applied by the user.

**Comment by cklosowski** [comment]
I think we should tackle this in two phases. This can be phase 1 with basic detection.

In this phase we will simply loop over the `edd_templates` directory of the active theme (child & parent), and list out the file names of the over-ridden template files:

Example:
```
-- Customized Templaes
shortcode-register.php
widget-cart.php
emails/body.php
```
