### ISSUE TITLE
3.0 - Improve report direct linking capability.

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#7911]
## Enhancement
In order to allow direct linking to reporting screens not only within the UI but between users, we should support direct links to filtered reports. Currently this data is handled in some session data, which is not shareable, or repeatable without someone entering in all the filter data again.

# Original Report
### Expected behavior

When I go to Downloads > Downloads and click on the `Earnings` link for that download, I expect to be taken to the report page that shows the overview for that download. It should be the equivalent of doing this manually:

- Go to Downloads > Reports.
- Clicking on "Downloads" tab.
- Changing the "All Downloads" dropdown to the specific download in question.
- Clicking "Filter".

### Actual behavior

I do get taken to the Downloads report page, but my filter settings are from whatever I'd last saved. So if I'd previously had this filter set to `All Downloads`, then clicking the earnings link just takes me to the report showing `All Downloads`. It seems like the `download-id=36386` query arg is just ignored.

### Steps to reproduce the behavior
1) First set your report settings. Go to Downloads > Reports > Downloads and set the download filter to `All Downloads`. Click `Filter` to save.
2) Go to Downloads > Downloads and click on the `Earnings` link for a specific download.
3) You'll be taken to the reports page, but `All Downloads` is still selected. It should have filtered to the specific download you clicked on.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
I think the Report filtering options being stored in transients causes more issues than just using a querystring in the URL. 

https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7645 added some data back to the URL to support legacy reports but I would be happy to see all filter options managed through the URL.

**Comment by ashleyfae** [comment]
> I would be happy to see all filter options managed through the URL.

I would be fine with that.

I see some benefits of storing in transients, but I think I agree it's causing more trouble than it's worth. We have too many other things going on that expect it to be in the URL, which means we have to add overrides, which means we're really doing everything twice now...

**Comment by robincornett** [comment]
One option to fix just this issue, without managing the larger query string question, would be to add an extra check to the [`get_filter_value`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/reports-functions.php#L376) method in reports-functions.php. This could be added just before the value is returned:

```php
	// Check if a specific download ID has been requested.
	if ( 'products' === $filter && 'all' === $filter_value ) {
		$download_id = filter_input( INPUT_GET, 'download-id', FILTER_SANITIZE_NUMBER_INT );
		if ( $download_id ) {
			$value = $download_id;
		}
	}
```

It resolves the immediate issue, at least, but I don't know if it is the best way to approach it.

**Comment by spencerfinnell** [comment]
@robincornett I think to @ashleyfae's point we might as well go all in:

> We have too many other things going on that expect it to be in the URL, which means we have to add overrides, which means we're really doing everything twice now...

I think trying to patch things in will get out of hand quickly.

**Comment by cklosowski** [comment]
@spencerfinnell I've updated the title and the scope of what this should do. Let me know if we need to change that or if that is what was discussed on the 3.0 triage meeting.

**Comment by spencerfinnell** [comment]
@cklosowski Looks good.

**Comment by spencerfinnell** [comment]
PR #8682 switches Report filter persistence from transients to URL. By default date and tax filters carry across reports.

To test:

1. Visit "Downloads" and click one of the earnings amounts under "Gross Revenue"

- Observe you are taken directly to the relevant Sales and Earnings report for the Download.

---

1. Visit "Reports"
2. Set the date filter

- Observe the reports reflect the set date filter

3. Refresh the page

- Observe the reports reflect the set date filter

---

1. Visit "Reports"
2. Toggle "Exclude Taxes"

- Observe report amounts exclude taxes

---

1. Visit "Reports > Downloads"
2. Filter by a single price Download

- Observe the reports reflect the selected Download

---

1. Visit "Reports > Downloads"
2. Filter by a variable price Download

- Observe the reports reflect the selected Download price.

---

1. Visit "Reports > Payment Gateway"
2. Filter by a specific payment gateway

- Observe the reports reflect the selected payment gateway

---

1. Visit "Reports > Taxes"
2. Filter the report by a selected Download

- Observe the reports reflect the selected Download 

3. Filter the report by a country/region

- Observe the report tile reflects the filtered location

**Note**: A bug currently exists on `release/3.0` that continues to show the "Total Tax Collected" tile and "Tax Collected by Location" table when viewing a specific location. 

---

1. Visit "Reports > File Downloads"
2. Filter the report by a selected Download

- Observe the reports reflect the selected Download

---

1. Visit "Reports > Discounts"
2. Filter the report by a Discount

- Observe the reports reflect the selected Discount
