### ISSUE TITLE
3.0 - Introduce report filter for "Exclude Refunded Orders"

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#7975]
### Explain your enhancement (please be detailed)

We should add a new filter to reports that allows the viewer to exclude refunded orders from the calculations. Similar to the tax filter.

![Screenshot from 2020-06-04 14-08-58](https://user-images.githubusercontent.com/6324272/83760538-ff696f00-a66c-11ea-86b7-9fbe378a7969.png)

Could also be the reverse ("Include Refunded Orders"). Not sure which is better.

Some discussion here: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7934

While we're here, we should also do two things:

1. Thoroughly comb through all amount calculations/graphs to make sure they're all using this new filter where appropriate.
2. Also consistently utilize the `edd_payment_stats_post_statuses` filter when building up a list of statuses we're using for querying.

### Justification or use case

Currently the Overview page intentionally includes refunded orders in its count after some Slack discussion. Shop owners should be able to see the full number of sales, then they can separately see the full refunds.

However, it might be nice to have some more flexibility and allow customers to toggle that.

**Comment by spencerfinnell** [comment]
This should likely happen after filter value getting/setting is updated in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7911

**Comment by robincornett** [comment]
Note: there was some discussion of creating a way to quickly access specific groups of statuses, using terms such as `net` and `gross` to easily differentiate, as we have multiple places where we are trying to work from specific sets of statuses (example: PR #7969).

**Comment by cklosowski** [comment]
With the release of 3.0 we ended up doing all base reporting in 'net' revenue types, with the explicit decision to later add 'gross' reporting.

With those two types of options, we shouldn't need another filter to 'remove refunds' as the reporting type provided will give you what you are looking for.
