### ISSUE TITLE
Changing currency affects past purchases

### ISSUE THREAD

**Issue by shaynesanderson** [awesomemotive/easy-digital-downloads#8189]
### Expected behavior
When currency is changed, it's expected to only change purchases moving forward.

### Actual behavior
When currency is changed, it updates all past purchases to new currency.

### Steps to reproduce the behavior
1) Ensure there are past purchases in EDD store
2) Change currency
3) Check Purchase History page and notice that all past purchases show updated currency

### Information (if a specific version is affected):
PHP Version: 7.4.1

EDD Version (or branch): 2.9.26

WordPress Version: 5.5.3

**Comment by ashleyfae** [comment]
We should test this against 3.0. I suspect it may not be an issue there, but we should confirm.

**Comment by robincornett** [comment]
I think this is an issue in both 2.9 and 3.0, but only in the `[purchase_history]` shortcode output. Looking at the orders list table/payment history in the admin, I see the correct currency on past purchases. Clicking the order details link in the purchase history shows the correct (historical) currency on the purchase confirmation screen in both 2.9 and 3.0. The currency appears to be correct in the admin edit order screen as well (both versions).

**Comment by ashleyfae** [comment]
So in the database it's still stored correctly, and is just a display issue?

**Comment by robincornett** [comment]
Yes, I believe that is the case. The currency is stored as part of the `edd_payment_meta` array.

**Comment by cklosowski** [comment]
@robincornett can we confirm this again on the final release of 3.0?

**Comment by robincornett** [comment]
In 3.0, the purchase history shortcode and receipt template are showing the correct currency.
