### ISSUE TITLE
3.x - Remove legacy compatibility code from variable pricing

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#8215]
## Enhancement Request
Remove the backwards compatibility PHP code for variable pricing, specifically:

- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L1459-L1515
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L509-L531
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/downloads/metabox.php#L410-L420

### Justification or use case
Per the discussion for #7136, we are removing the backwards compatibility code for the `edd_download_price_table_head` and `edd_download_price_table_row` hooks in three stages:
1. Formally deprecate the hooks (#8214) in 2.10
2. Remove the JS for Sandhills extensions in 3.0
3. **Remove the PHP code in 3.x (for third party extensions)**

**Comment by mihaijoldis** [comment]
Had this mentioned in .org about the deprecated notice coming from "edd_download_price_table_row". Just thought I'd mention it.

**Comment by cklosowski** [comment]
@robincornett are we at a point where we can remove these now do you think? have all of our extensions been updated to accommodate the deprecation/removal?

**Comment by robincornett** [comment]
All AM extensions have been updated, yes. If anyone is still seeing deprecation notices, they're from a third party extension or they need to update.

**Comment by cklosowski** [comment]
Sounds good. Just wanted to ensure we're all updated :+1: We can continue forward with this in 3.1.
