### ISSUE TITLE
Tax rate applying to entire country when country wide option not checked

### ISSUE THREAD

**Issue by brianleejackson** [awesomemotive/easy-digital-downloads#8271]
### Expected behavior
I'm using the [EU VAT plugin](https://barn2.co.uk/wordpress-plugins/easy-digital-downloads-eu-vat/) on my sites to charge VAT. Ran into an issue where there was a specific province that shouldn't be charged VAT: Las Palmas. This is located in the Canary Islands which is exempt from VAT ([source](https://ec.europa.eu/taxation_customs/business/other-taxes/turnover-taxes-canary-islands_en)).

In EDD, I went to the Tax Rates table and added Spain as the country and Las Palmas as the province. I then entered 0% for the tax rate. This means Las Palmas shouldn't get charged taxes, and Spain should resort back to what the EU VAT plugin is setting. 

![image](https://user-images.githubusercontent.com/186682/102111248-5ce83080-3df3-11eb-8e7e-1456b527bf71.png)

### Actual behavior

The problem is that now the entire country of Spain doesn't get charged tax. I can confirm the "Apply to whole country" box is **not checked**. This won't work since most of Spain is under EU law for VAT, it's just a few provinces that should be excluded. So it appears the option provided doesn't seem to work as expected. It seems to just be applying it to the whole country regardless. 

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version: 2.9.26
Easy Digital Downloads - EU VAT Version: 1.3.2

WordPress Version: 5.6

Any other relevant information:

I reached out to the [Barn2 Media](https://barn2.co.uk/) team first and they said this was most likely a bug with EDD.

**Comment by cklosowski** [comment]
We need to try and replicate this in EDD 3.0 with the new tax rate system and work @robincornett has done in #9294
