### ISSUE TITLE
Add an action hook for when PayPal IPN verification fails

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#8294]
### Explain your enhancement (please be detailed)

We should add an action hook when IPN verification fails.

### Justification or use case

Ticket: https://secure.helpscout.net/conversation/1362809542/172705/

A customer seems to be running into issues with the verification request timing out. That problem is on PayPal's end, but they'd like some way to email the site admin or something when this happens. An action hook would make that easily accomplished with custom code.

**Comment by cklosowski** [comment]
Since we have deprecated PayPal Standard in EDD core for new installs in favor of PayPal Commerce, we can close this.
