### ISSUE TITLE
Introduce edd_get_complete_order_statuses() function that contains all possible "complete" statuses

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#8416]
### Explain your enhancement (please be detailed)

We should introduce a function that returns a (filterable) array of all "complete" order statuses.

### Justification or use case

Use case: https://github.com/easydigitaldownloads/edd-invoices/pull/56 EDD Invoices shows a "Paid" image if the status is complete. It wasn't working because the plugin was checking for the `complete` status, but EDD 2.9 needed `publish`. We then also wanted to support Recurring, which meant hard-coding in `edd_subscription` as well.

We've also had similar checks in reports that do database queries for all "complete" orders.

We have functions for:

`edd_get_refundable_order_statuses()`
`edd_get_net_order_statuses()`
`edd_get_gross_order_statuses()`

Seems like `edd_get_complete_order_statuses()` would be a nice addition.

**Comment by cklosowski** [comment]
We did add this in 3.0 prior to the release.
