### ISSUE TITLE
Feature: Allow orderby post_modified in the downloads short-code

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#8417]
### Explain your enhancement (please be detailed)
Came as a question via .org https://wordpress.org/support/topic/when-updating-a-download-it-doesnt-show-up-as-new
It can be done with the edd_downloads_query filter but maybe we can add it directly in core to be a supported parameter

### Justification or use case
Comment from the user

Let’s say I have one Download which is Calendar. Right now on version 2.1.1
I want to push the update to version 2.2 so I go to the backend, upload the new version and remove the old one.
When I use the Gutenberg block, it does not appear on top of the list. I can order by Date Created but not by Date Modified.
Same with the shortcode [downloads orderby] where I can only use post_date but not post_modified.

If this is added we should also add it tot the blocks plugin https://github.com/easydigitaldownloads/edd-blocks

**Comment by cklosowski** [comment]
@robincornett might be another candidate for the new block?
