### ISSUE TITLE
Add hook to disable logging

### ISSUE THREAD

**Issue by stephywells** [awesomemotive/easy-digital-downloads#8450]
## Enhancement Request
I would really like to be able to use a hook to disable some logging, rather than updating the plugin and commenting it out after every update.

```
do_action( 'edd_pre_insert_log', $log_data, $log_meta ); // existing line.
if ( apply_filters( 'edd_stop_logging', false, $args ) ) {
return 0;
}
```

### Explain your enhancement (please be detailed)
Logs are a huge issue on our site, so several log types have to be completely disabled. It would be better to prevent them up front rather than just adding the option to delete them later:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7260

Would cover:
https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1044

Specifically, we are disabling sales, license activation, and license deactivation.

**Comment by ashleyfae** [comment]
Scheduling this for sometime after 3.0, as logging is significantly changed.

**Comment by cklosowski** [comment]
The original request was for things like sales, an software licensing activation and deactivation.

Sales are no longer stored in logs, and two filters exist for disabling activation/deactivation requests:
```
add_filter( 'edd_sl_log_license_activation', '__return_false' );
add_filter( 'edd_sl_log_license_deactivation', '__return_false' );
```

However, this allows disabling logging in the new EDD 3.0 logging system, and as extensions move their logs over, we'll be able to selectively filter them out by their object type.
