### ISSUE TITLE
3.0 - Dismiss "More" Filter in Orders

### ISSUE THREAD

**Issue by LisaCee** [awesomemotive/easy-digital-downloads#8478]
### Expected behavior
I expect to be able to dismiss the menu that shows after clicking "More" by clicking outside of that area

### Actual behavior
Clicking outside of the menu does not dismiss the menu.  Instead I have to click back on the "More" button to dismiss

### Steps to reproduce the behavior
1) Orders > More  (filter bar)
2) Try to dismiss the menu by clicking outside modal

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8259
