### ISSUE TITLE
3.0 - Customer table delete link does not work as expected

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#8706]
### Expected behavior
When you click the "Delete Customer" link on the customer's table, it takes you to the customer's view/edit screen instead of the delete custom tab. I believe this happens because the tabs are handled via JS, which requires a 'click' to make the content appear.

### Actual behavior
As per the above.

**Comment by davidsherlock** [comment]
This essentially happens...

<img width="254" alt="Screenshot 2021-06-16 at 17 45 16" src="https://user-images.githubusercontent.com/22668877/122240714-a7de2000-ceca-11eb-9001-0fb6f425b28e.png">

**Comment by ashleyfae** [comment]
Moved this to after 3.0, because although we should fix it, it's not a blocker to launch.

**Comment by cklosowski** [comment]
This was fixed in 3.0 #9201
