### ISSUE TITLE
Introduce custom AJAX endpoints/routes to improve performance for frontend requests

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#8717]
### Explain your enhancement (please be detailed)
At the minute, EDD is using by way of wrapper the admin-ajax.php file for all AJAX callbacks, this has significant overhead compared to a custom route like the WP Job Manager uses.  I propose we build a custom EDD specific endpoint called edd-ajax where each route (action) is defined in the URL as follows:

mysite.com/edd-ajax/get_tax_rate
mysite.com/edd-ajax/add_to_cart

In an ideal world, we would move ALL AJAX frontend requests to the WordPress REST API but due to the work required to achieve this, It should be done later and this will still provide performance benefits in the mean time.

### Justification or use case

Performance/scalability.

**Comment by ashleyfae** [comment]
I'm not sure I like the thought of switching it twice. I'd rather decide how we want to do it and do it that way once. (So if we want to move to REST API, I'd rather we move to REST API, rather than an interim change, followed by another change.)

**Comment by davidsherlock** [comment]
The REST API would open up a lot of opportunities for more dynamic React-based frontend stuff and the like on themes. At the minute the AJAX approach can be problematic in EDD for customization. I say go REST, but it's a lot of work to update all the EDD AJAX calls

**Comment by ashleyfae** [comment]
We don't necessarily have to update them all at once -- in fact it's probably better if we don't. We can update them slowly over a few major releases.

**Comment by davidsherlock** [comment]
Closing this because it makes more sense to use REST instead of the marginal performance benefits this would offer.

**Comment by davidsherlock** [comment]
.
