### ISSUE TITLE
3.0 - Privacy policy checkbox in admin is not alligned

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#8789]
Not a major issue but for me (laptop) the display of the checkbox to enable privacy policy in the admin side looks weird https://prnt.sc/1hmns7h

**Comment by ashleyfae** [comment]
The `Need help creating...` text is inside the `<label>` tag and it really shouldn't be. That should be a description instead, like the `Agreement` setting is:

![Screenshot from 2021-08-02 12-25-03](https://user-images.githubusercontent.com/6324272/127854474-c1d126e2-2400-4753-a32c-a8686eb2b56c.png)

**Comment by robincornett** [comment]
Just looked into this... EDD 3.0 adds a new settings field type of `checkbox_description` which allows a checkbox to show a label and then related description/help text. So in 3.0 we could switch this setting to the new type. The output needs to be adjusted somewhat as the description currently duplicates the text of the label.

**Comment by cklosowski** [comment]
I would say let's just put that in a post 3.0 release then, since the mechanism for a better display will exist. We can toss that into a minor release post final 3.0.

**Comment by cklosowski** [comment]
I'm going to actually close this one out. We'll be doing a full UI/UX overhaul in the near future of the admin and I think that is the best time to assess all of our inputs.
