### ISSUE TITLE
3.0 - Consider removing/adjusting caching on edd_get_total_earnings()

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#8869]
### Explain your enhancement (please be detailed)

See https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8809#issuecomment-919980113

The query results in `edd_get_total_earnings()` are cached because in EDD 2.x it's very expensive to get that information. In EDD 3.0, the query is a lot faster and we can consider removing the caching.

### Justification or use case

> They do cause some level of support tickets when they don't re-count.

**Comment by cklosowski** [comment]
As of 3.0.4 in #9361, this has been updated to use a 1 hour transients, and we've adjusted it to remove the transient with order changes happen and stats are recalculated. While it is a much better query, it is still a lot of data on larger stores, so we should at least cache it even if it is only for a short erm.
