### ISSUE TITLE
3.0 - Errors running migration CLI script

### ISSUE THREAD

**Issue by zackkatz** [awesomemotive/easy-digital-downloads#8933]
### Expected behavior
When I run `wp edd v30_migration`, I see a few errors during migration.

### Payment migration:

```
Notice: Undefined offset: 0 in /[…]/plugins/edd-software-licensing/edd-software-licenses.php on line 1130
```

```
Notice: map_deep(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "EDD_DB_Customers" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /[…]/wp-includes/formatting.php on line 4929
```

### Log migration:

```Notice: Undefined index: _edd_log_ip in /[…]/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-data-migrator.php on line 246```

### Steps to reproduce the behavior

I'm afraid I am not able to share my DB export due to sensitive data…but I do know I have products that are 7 years old with a `0` (zero) Price ID that may be at issue.

**Comment by robincornett** [comment]
I've set up a draft PR which should fix the log IP index notice (#8936), but will have to look more to see if I can replicate the others.

**Comment by robincornett** [comment]
Thanks, @zackkatz; I appreciate you testing again. Can you tell me what the new line number is from SL that's throwing the error? Line 1130 no longer exists in that file in 3.8.1, so if that's being triggered again, it should be coming from a different file.

Thank you for the detailed post meta information--will see what we can suss out from there.

**Comment by robincornett** [comment]
Weird question, but should that hook be running during migration? Or actions on that hook? Because the migration should not be changing order related information, just reorganizing it, right?

**Comment by ashleyfae** [comment]
I feel like none of our order creation/transition hooks should be running.

**Comment by robincornett** [comment]
Interestingly, I'm not seeing anything to remove actions during migration. We are currently implementing three transition hooks (well, two, but one of them twice):
- `edd_transition_customer_address_is_primary` which I think probably actually _should_ be allowed to run during the migration because 2.x doesn't have an address ranking system, so this is new data.
- `edd_transition_order_status` runs in two different functions:
    - `edd_record_order_status_change` adds a payment note indicating that the order status has changed.
    - Then we also have an [anonymous function](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/payments/actions.php#L286-L303) running, and I suspect this one is maybe at fault here, at least for the Software Licensing behavior. We added it to maintain backwards compatibility for extensions using the `edd_update_payment_status` hook.

I would guess, actually, that both functions running on `edd_transition_order_status` are problematic. I just checked the order notes for a migrated order and there are two "Status changed from new to Completed" notes--the original/first one, and then one run, I assume, during the migration, which isn't accurate.

So maybe we `remove_all_actions( 'edd_transition_order_status' );`, which would cover our current scenarios. If more functions are added to order transitions, we would have to add code to account for those, but maybe new functions would not be as potentially problematic as these.

**Comment by robincornett** [comment]
@zackkatz I've pushed an update to the `issue/8933` branch which removes all of the order status transition actions. It resolves the duplicate note issue for me, which was a more readily visible effect. If you have time, would you be willing to see if it sorts you out as well?

**Comment by robincornett** [comment]
Rats, I was hoping that one would magically have resolved itself! Are you running the entire migration, or just the orders at this point? If it's happening within orders, that helps me know where to look. Thanks again for your patience on this!

**Comment by ashleyfae** [comment]
Is it possible for you to get a stack trace for the `map_deep()` error? I don't think that's one we've seen before. I also just ran the migration with this PR + SL 3.6.12 and still didn't get it. It's going to be hard to fix unless we know more about where it's coming from. Though it's sounding like the `EDD_DB_Customers` class is serialized somewhere, which is weird..

You are missing a few orders. After migrating you could run this query to see which payment IDs didn't migrate:

```mysql
SELECT p.ID
FROM wp_posts p
         LEFT JOIN wp_edd_orders o ON p.ID = o.id
WHERE o.id IS NULL
  AND p.post_type = 'edd_payment';
```

You could then verify that the missing ones are "valid" orders. (If they look wonky/invalid then that's probably why they didn't migrate.)

You are missing quite a few logs. Do you do any custom logging? To start with, you could run this query which will tell us how many logs of each type you have, which may shed some light into which ones are missing:

```mysql
select count(p.ID), t.slug
from wp_posts as p
         left join wp_term_relationships AS tr ON (p.ID = tr.object_id)
         left join wp_term_taxonomy AS tt ON (tr.term_taxonomy_id = tt.term_taxonomy_id)
         left join wp_terms AS t ON (tt.term_id = t.term_id)
WHERE p.post_type = 'edd_log'
  AND t.slug != 'sale'
group by t.slug;
```

**Comment by ashleyfae** [comment]
I believe we are excluding sales logs already. From `EDD_CLI::migrate_logs()` : 

```php
$sql = "
	SELECT p.*, t.slug
	FROM {$wpdb->posts} AS p
	LEFT JOIN {$wpdb->term_relationships} AS tr ON (p.ID = tr.object_id)
	LEFT JOIN {$wpdb->term_taxonomy} AS tt ON (tr.term_taxonomy_id = tt.term_taxonomy_id)
	LEFT JOIN {$wpdb->terms} AS t ON (tt.term_id = t.term_id)
	WHERE p.post_type = 'edd_log' AND t.slug != 'sale'
";

$results = $wpdb->get_results( $sql );
$total   = count( $results );
```

We have a condition for `AND t.slug != 'sale'`
