### ISSUE TITLE
Connecting to new PayPal account still uses old account for new purchases 

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#8937]
### Expected behavior
After disconnecting from the current PayPal account and connecting to a new PayPal account, new purchases should use the new PayPal account.

### Actual behavior
The payments are still sent to the old PayPal account.

### Steps to reproduce the behavior
1) Go to Downloads > Settings > Payment Gateways > PayPal and "Disconnect from PayPal"
2) Connect to a different PayPal account
3) Test a purchase, confirm the payment is sent to the new account

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.11.2

WordPress Version:

Any other relevant information:
This is the 2nd customer that reported this type of issue.
https://secure.helpscout.net/conversation/1666603766/

**Comment by robincornett** [comment]
Confirmed--I disconnected from PayPal and connected with a separate account (that I had originally set up to test PayPal Pro). With dev tools open, I'm seeing hints that PayPal knows there is a mismatch:

```
buttonCorrelationID: "4af15d2d9e21f"
buttonSessionID: "uid_450c38b11a_mtk6mzm6mjk"
clientID: "AYX-UJpi0YDNFflQQQGAMPc97qxx7NyMUMoKuZTv3KWesdXr6aExbyQLHHr9QQn2kiFlvHILYR7qjeeF"
env: "sandbox"
referer: "www.sandbox.paypal.com"
sdkCorrelationID: "f387643dc3d4f"
sessionID: "uid_9e07518967_mtk6mzm6mja"
time: "1634672034046"
timestamp: "1634672034046"
token: "1C631851AL436510E"
user_id: "uid_450c38b11a_mtk6mzm6mjk"


Payee(s) passed in transaction does not match expected merchant id. Please ensure you are passing merchant-id=TL4VZ44FQCMJN or merchant-id=sb-catz13487703@business.example.com to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/
```

That `merchant-id` is tied to my original PayPal account; the new one is `sb-yzu8w6667787@business.example.com`.
