### ISSUE TITLE
edd_has_user_purchased() always returns false

### ISSUE THREAD

**Issue by shiraliali** [awesomemotive/easy-digital-downloads#8974]
### Expected behavior
`edd_has_user_purchased()` should return true for the user which purchased the file but always returns `false`

### Actual behavior
When i use `edd_has_user_purchased()` function to check purchase state for posted download id for a user as a value in JSON object no matter user has purchased or not, returned response is always `false`.

**I Tried like:**
```
$downloadID = $body->download;
 if(edd_has_user_purchased(get_current_user_id(), $downloadID)){
//...
}else{

die();
}

```

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 2.9.23 

WordPress Version:  5.5.3

Any other relevant information:
Note that when i use this function in theme functions it works fine but not in my custom `api.php`

**Comment by robincornett** [comment]
Hi @shiraliali! If the `edd_has_user_purchased` function is working in your theme functions, but not in your custom file, my guess would be that the `get_current_user_id()` function is not returning the active user's ID. I would suggest starting there for troubleshooting.

If you need further support, please [contact our support team](https://easydigitaldownloads.com/support/).

**Comment by shiraliali** [comment]
I have tested with manual giving id like `90` instead of function but still doesn't work.
**Like :**

```
 if(edd_has_user_purchased(90, $downloadID)){
       ...
}else{
      die();
}
```
