### ISSUE TITLE
Update EDD banner for repository

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#8981]
### Explain your enhancement (please be detailed)
Suggesting that we update our banner on the WordPress repository.

### Justification or use case
It looks okay on the repository itself (I think the logo looks pixelated maybe), but when I click "View Details" from the plugins list table, the logo and Edd's face are not visible:

![image](https://user-images.githubusercontent.com/4853066/140774594-355afb85-fa1f-41a4-acfb-807eb5d659ec.png)

**Comment by robincornett** [comment]
One possible revision would be to use a different Edd and move the logo, but otherwise keep the general look and feel of the current. It would look like this in WP:

![image](https://user-images.githubusercontent.com/4853066/140778055-a7781aba-a85c-47a3-8828-26fdc1fb63d6.png)

and this on the repo:

![image](https://user-images.githubusercontent.com/4853066/140778300-5ccc0817-8151-4cfe-9187-199f88e448ef.png)

(looks like Edd needs to move up a bit)

**Comment by ashleyfae** [comment]
I like it, but I think we need someone who's not a dev to chime in. :sweat_smile:
