### ISSUE TITLE
Consider refactoring edd_get_settings_tabs

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9001]
### Explain your enhancement (please be detailed)
I would like to consider refactoring the `edd_get_settings_tabs` function, mainly to not use the `edd_get_registered_settings` function.

### Justification or use case
I'd like to use the `edd_get_settings_tabs` function elsewhere to check if a tab exists (we are adding a new one for product education) and I can't because there are varying levels of errors that happen, if Reviews is active, or if the Amazon gateway is active. From what I can tell, the issue is because of calling the `edd_get_registered_settings` function, which also feels expensive.

I have pondered a couple of thoughts about how to tinker with this. One would be, instead of getting _all_ of the settings in order to see if there are settings registered for extensions or licenses, to replicate their individual `apply_filters` calls and just check for them:

```php
	$extensions = apply_filters( 'edd_settings_extensions', array() );
	if ( ! empty( $extensions ) ) {
		$tabs['extensions'] = __( 'Extensions', 'easy-digital-downloads' );
	}
	$licenses = apply_filters( 'edd_settings_licenses', array() );
	if ( ! empty( $licenses ) ) {
		$tabs['licenses'] = __( 'Licenses', 'easy-digital-downloads' );
	}
```
This feels a little more viable approach because those are the only two things that are being checked by pulling in the entire `$settings` array.

Another thought I had was to make a new function called `edd_get_default_settings_tabs` and have that return _just_ the array of EDD registered tabs, and then this function can pull in that array and do the extensions/licenses check and apply its filters as it does now. Then I could use the new function to check for the tab I want to find.

Personally, long term I would love to separate the arrays in `edd_get_registered_settings` into possibly separate views type files, maybe, or at least just get the long array of arrays out of the main register-settings.php file because I find it overwhelming...but setting them up as separate files, I could use an `include` to pull just the extensions and licenses arrays to add those tabs.

**Comment by ashleyfae** [comment]
> Personally, long term I would love to separate the arrays in `edd_get_registered_settings` into possibly separate views type files, maybe, or at least just get the long array of arrays out of the main register-settings.php file because I find it overwhelming...but setting them up as separate files, I could use an `include` to pull just the extensions and licenses arrays to add those tabs.

Still looking over your short term idea, but my eyes jumped to this and I like this long term plan. I agree the file is overwhelming.

**Comment by robincornett** [comment]
For the short term, I would probably like to consider combining/implementing both solutions--I could use `function_exists` to make sure I'm using a "safe" version of the code.

**Comment by ashleyfae** [comment]
What if we only filtered out the empty tabs at the last minute during display? (`edd_options_page()`)

**Comment by robincornett** [comment]
That would work, too, although wouldn't help with my immediate problem of wanting to be able to reliably use this function. But I think that makes sense and is probably tidier than my thoughts.

**Comment by ashleyfae** [comment]
If we definitely put this change into 2.11.4, you could do a version check before calling `edd_get_settings_tabs()`. I know it's a little gross, but I think I quite like the idea of just filtering them out in `edd_options_page()` purely in terms of organization.

**Comment by robincornett** [comment]
Okay, I can live with that--results in a version check either way but I would love to get this in now. I'll put together a PR.
