### ISSUE TITLE
3.0 - Consider storing file name and URL in edd_logs_file_downloads table for more accurate reporting

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9009]
### Expected behavior
I expect the file "name" (and URL) to be properly grandfathered and display within the File Downloads report, as per other log tables within EDD 3.0.

### Actual behavior
At the minute, because this table is relational with the file ID, if the file is changed (or name updated) on the product itself, it will be reflected on the file downloads log. Similarly if the file is deleted and that ID changes, it will show no file name at all in the admin table log. 

This does not (technically) make sense, as a lot of store owners will simply replace versions (or files) and it will show that this has already been downloaded when it hasn't (yet).

I propose we store the File Name and URL (as in EDD itself) in the file downloads table for data accuracy and reporting purposes. If not present (as per older versions), just use the lookup approach.

**Comment by ashleyfae** [comment]
I think this is the same as https://github.com/awesomemotive/easy-digital-downloads/issues/6623 so I'm closing as a duplicate. Feel free to add your +1 there.

Definitely a good idea.
