### ISSUE TITLE
Debug Log can cause 500 errors when it grows too large.

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#9019]
### Expected behavior
I expect the EDD Debug log to not cause performance issues on a store.

### Actual behavior
When the debug log is left on, it can cause logs to grow to large amounts, causing checkouts and actions on the site to slow down, due to having to open the debug log into memory for writing. Eventually this can cause memory issues and eventually 500 errors.

### Steps to reproduce the behavior
This is hard to 'reproduce' as it requires a large amount of data and a server configuration that runs out of memory. In the example I had, the debug log file was over 200MB.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 2.8.7+

WordPress Version: All

## Requirements
- [ ] #9056

## Other ideas that we may punt to later versions.
- Output debug log file size on the debug log view. This can help identify when your debug log file is increasing in size.
- Restrict Debug logging to only be enabled for a certain time? Auto deactivate after 24 hours? (Allow custom timeframes?)
- Rotate log file or automatically truncate after a certain file size.

@ashleyfae I'm really only requiring that first admin notice. The rest could be useful, but if we want, we can kick those to a later version of EDD Core.

I'd like to have this maybe go in a version after 2.11.4?

Possible wording for the admin notice:
"Easy Digital Downloads debug logging is enabled. It is not advisable to leave this running at all times, and should only be used when actively trying to solve a problem.  <view link>View Debug Log</view link> <link to disable debug logging>Disable Debug Logging</link to disable debug logging>"

We should make the link to disable debug logging actually disable it, instead of sending the user to the Misc Settings to then make 2 more clicks to uncheck the box and then save settings.

**Comment by ashleyfae** [comment]
> Rotate log file or automatically truncate after a certain file size.

Of the other ideas, I like this option.

The time frame one could be annoying for legitimate testing in sandbox mode. For example, I recently set up a PayPal subscription test on Friday and wanted to check the results Monday. I specifically wanted to see what webhooks came in and other things that would be noted in the debug log. Wouldn't have been able to do the test if it shut off after 24 hours.

**Comment by ashleyfae** [comment]
> Add a non-dismissible admin-notice when the EDD Debug Log is enabled.

Can we only show it in live mode?

**Comment by robincornett** [comment]
In 3.0, we have the store mode prominently displayed in the admin bar. What about adding a similar indicator if debugging is enabled (wouldn't have to show it at all if not)?

![image](https://user-images.githubusercontent.com/4853066/146005231-bc9ad852-a248-44dd-acfc-931b446ec9d5.png)

**Comment by cklosowski** [comment]
@robincornett Yeah I think only showing it during live mode is fine. If we can do rotating logs easily then lets go for it, but I think a good first step is just letting people know it is enabled (kind of like 3.0 has).

**Comment by mihaijoldis** [comment]
Given that sometimes having past logging is helpful when debugging, perhaps even longer than a few days I would maybe see it work like this:
Once the main debug log file reaches a memory size, say 5MB, archive it inside the wp-content/uploads directory say: `edd-debug-log-datestampwhencreated.log` and again for the next file if it gets to 5MB.

In addition to that on the Debug Log page if multiple (archived) logs exist show a Download Logged History button that maybe downloads all files or put them inside a .zip file

**Comment by spencerfinnell** [comment]
WooCommerce does what you all have described: starting a new log file once it has reached a certain size.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php

**Comment by ashleyfae** [comment]
Also I think really the main problem here is that we are loading the file into memory at all. We do not even need to be doing that.

We're essentially doing:

```php
$file = file_get_contents( $this->file );
$file .= $message;
@file_put_contents( $this->file, $file );
```

That first `file_get_contents()` is unnecessary.

**Comment by cklosowski** [comment]
Lets go ahead and close this issue, as it solves the primary issue of the 500 error due to the memory exhaustion. Combined with #9056 this should get us into a state where people know they have logging on and shouldn't have it on all the time.

We can follow up with rotation of logs later after we have a chance to get a UI scoped for it.
