### ISSUE TITLE
3.0 - New purchase email is sent after a refund

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#9025]
### Expected behavior
When I issue a refund, I do not expect to get a "new purchase" email. (The admin one.)

### Actual behavior
I'm pretty sure I received one.

### Steps to reproduce the behavior
1) Start with a complete order.
2) Refund that order.
3) See that you (the admin) received a new purchase notification email.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
Confirmed. Additionally, the new purchase receipt was sent to the customer.
