### ISSUE TITLE
EDD 2.11.4 incorrectly hides Recurring settings submit button

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#9042]
### Expected behavior
When I have the Recurring plugin installed and activated, I expect to see the submit button on the Recurring settings page.

### Actual behavior
It's not there.

![Screenshot from 2022-01-06 12-36-58](https://user-images.githubusercontent.com/6324272/148384090-a6de362e-f923-4315-959a-641ab3b6732f.png)

### Steps to reproduce the behavior
1) Be on EDD 2.11.4.
2) Install and activate Recurring.
3) Go to Downloads > Settings > Payments > Recurring Payments.
4) Note the lack of submit button.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.11.4

WordPress Version:

Any other relevant information:

The problem is here: https://github.com/awesomemotive/easy-digital-downloads/blob/2.11.4/includes/admin/extensions/product-education/class-recurring.php#L42
https://github.com/awesomemotive/easy-digital-downloads/blob/2.11.4/includes/admin/extensions/abstract-extension.php#L339-L343

That `hide_submit_button()` method needs conditionals to only execute if the card is also going to display.

The reason the submit button appears for Invoices is because the section ID is actually incorrect in product education. It's different from the one the actual Invoices extension uses, which means product education is only impacting the "fake" section it sets up and not the real one.

Invoices hooks in here https://github.com/awesomemotive/easy-digital-downloads/blob/2.11.4/includes/admin/extensions/product-education/class-invoices.php#L42 via `edd_settings_tab_top_gateways_invoices`. But the hook the real extension uses is: `edd_settings_tab_top_gateways_edd-invoices`.

**Comment by mihaijoldis** [comment]
This is also affecting the Reviews extension.

**Comment by mihaijoldis** [comment]
Just wanted to mention, but probably you guys know, this is also affecting the release/3.0 branch
