### ISSUE TITLE
3.0 - Change Debug mode checkbox description text

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9044]
On a fresh 3.0 release install I wanted to activate Debug mode but the description text next to the checkbox seems a bit too vague.
https://a.supportally.com/hYZGXN

I feel like we should rephrase that to say "Check this box to Enable Debug mode", or something like that.

**Comment by cklosowski** [comment]
Yes, I think "Check this box to enable Debug Mode" is fine for this.
