### ISSUE TITLE
3.0 - Order Admin View - Use decimal settings for order's currency

### ISSUE THREAD

**Issue by ashleyfae** [awesomemotive/easy-digital-downloads#9050]
See https://github.com/awesomemotive/edd-multi-currency/issues/29

In short:

- Say your site currency is set to USD.
- You have an order that was made using HUF (a zero decimal currency).
- You view that HUF order.
- You expect it to show no decimals, but it does show decimals because it's using the settings for the global currency instead of the current order. We can change this easily.

**Comment by robincornett** [comment]
Sorry, reopening as I've just discovered the refund modal needs to be updated as well.
