### ISSUE TITLE
3.0 - Unable to delete unused discount when calling edd_delete_discount due to incorrect operator usage 

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9062]
### Expected behavior
I expect to be able to delete a discount that has not been used by calling `edd_delete_discount()`.

### Actual behavior
The discount does not delete. This is due to incorrect operator logic here:

```
// Do not allow for a discount to be deleted if it has been used.
if ( $discount && 0 < $discount->use_count ) {
   return false;
}
```

We need to update the logic to > 0 to make it valid.

**Comment by ashleyfae** [comment]
That logic looks correct to me. It's preventing deletions if the discount's "use count" is greater than `0`. (In other words: If the discount has been used at least once, it cannot be deleted.)

Just tested myself and confirmed:

- I was unable to delete a discount with `1` use.
- I was able to successfully delete a discount with `0` uses.

**Comment by davidsherlock** [comment]
I might be missing something here, but it's using a `less than` operator. Based on this logic, if the user count is < 0 (i.e. more than 0) it will allow it to be deleted, when it shouldn't. At least this was my experience...

**Comment by ashleyfae** [comment]
`0 < $discount->use_count`

That's saying:

"If zero is less than the number of uses."

Which can also be reworded like this (with the exact same results):

"If the number of uses is greater than zero."
The PHP for that would be:
`$discount->use_count > 0`

What you're thinking of is:

`$discount->use_count < 0`

That would be: "The number of uses is less than zero". But that's not what's happening here.

**Comment by davidsherlock** [comment]
Closing due to non-issue.
