### ISSUE TITLE
3.0 - Currency report dropdown displays empty when store has no orders

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9072]
### Expected behavior
I expect to not see an empty dropdown select on the reports view(s).

### Actual behavior
When viewing reports on a store with no orders, the currency dropdown displays with no currencies populating the select/

### Information (if a specific version is affected):
PHP Version: 7.4.1

EDD Version (or branch): 3.0

WordPress Version: latest

Any other relevant information:

**Comment by robincornett** [comment]
Thanks for reporting this, @davidsherlock! I've confirmed and created a PR for it.

**Comment by davidsherlock** [comment]
Looks to be fixed now @robincornett, will close this!
