### ISSUE TITLE
View receipt email tag not loading properly

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9089]
### Expected behavior
Clicking a link generated by the {receipt_link} code should open the page properly.

### Actual behavior
It opens a page but it seems the page is not correctly rendered and the URL seems wrong?
URL looks like: https://www.localhost.com/edd/?payment_key=5bbc287faa05ea314d75cce1db101578&edd_action=view_receipt
Page: https://a.supportally.com/8fqBXp

### Steps to reproduce the behavior
1) Add {receipt_link} and make a purchase
2) Click the link in the email

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): master and release/3.0

WordPress Version: latest

**Comment by mihaijoldis** [comment]
@robincornett that was in Themedd. I tested with 2022 and it looks the same https://a.supportally.com/EKpTDD

If its supposed to look this way then my bad. You can close this.
I assumed it was supposed to look like a normal Purchase Confirmation page

**Comment by cklosowski** [comment]
This is working as expected. Since we don't have have an 'account area' registry and we cannot guarantee that the receipt page exists and contains the proper shortcode (we can  only know a setting exists), we make our own endpoint to load the receipt, which doesn't load the styles.
