### ISSUE TITLE
PayPal error when closing prior to completing purchase

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#9092]
### Expected behavior
No unexpected, non-customer facing errors if existing PayPal window prior to completing purchase.

### Actual behavior
"document.getElementById(...) is null" is displaced on the EDD checkout page

### Steps to reproduce the behavior
1) Checkout with PayPal
2) Exist window before completing purchase
This does not occur every time so it might be difficult to reproduce.

### Information (if a specific version is affected):
PHP Version:  7.3.33

EDD Version (or branch): 2.11.5

WordPress Version: 5.8.3

Any other relevant information:
Mihai was able to replicate but existed process was unknown.

**Comment by robincornett** [comment]
I'm going to guess this is related to changes we made to solve #8883. If that's true, it should be possible to replicate with auto register enabled and beginning, but cancelling, a purchase as a new user. I suspect that there is something else possibly at play here as the list of IDs to update are retrieved from the enabled gateways--the error suggests that we are trying to update a gateway selector that doesn't exist.

I'll look more tomorrow, but making notes here for myself. I think we can fix this by only setting the element attribute if the element was actually found ([source](https://github.com/awesomemotive/easy-digital-downloads/blob/master/assets/js/paypal-checkout.js#L165)). We're assuming that the list of enabled gateways will match what's actually on the screen but I'm suspecting that it somehow does not.

**Comment by davidsherlock** [comment]
@robincornett This may be (somewhat) related, but on the EDD site itself if you click on the PayPal buttons then close the dialog a few issues happen:

1. You get a bunch of EDD errors about fields being incorrect (for example if you have not filled in any of the fields at the checkout).
2. You get an endless spinner/error that does not go away until you change gateways again.

**Comment by robincornett** [comment]
@davidsherlock thanks for noting that--it is currently behaving as designed (except for the spinner, which should be hidden automatically), but looking at the PayPal docs, I think it's possible for us to finesse the experience a little bit. I'll copy the information and open a new issue as a feature request.
