### ISSUE TITLE
3.0 - Request for completed hook in edd_add_manual_order

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9105]
It would be great to have a hook in the `edd_add_manual_order` process to trigger actions that need to happen when an order is complete, but currently there isn't a hook in that function.

The `edd_build_order` function has a final action hook for `edd_built_order` which has the new order ID and the order data as the parameters. The manual order should have the same, or at least a similar, hook.

For example, this would make inserting a new user during the manual order process easier in Auto Register.

**Comment by cklosowski** [comment]
Let's go ahead and modify the `edd_add_manual_order` function, renaming `$data` > `$order_data`

And use this hook right before the redirect: `do_action( 'edd_post_add_manual_order', $order_id, $order_data);`
