### ISSUE TITLE
Remove translation files from core and rely on .org

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9118]
### Explain your enhancement (please be detailed)
Some, if not all of our translations might be out of date anyway and we should rely on the translations from .org https://translate.wordpress.org/projects/wp-plugins/easy-digital-downloads/ 

3.0 might be a good time to do this since many strings will be changing anyway. There was a small discussion here https://github.com/awesomemotive/easy-digital-downloads/issues/9016

This could close https://github.com/awesomemotive/easy-digital-downloads/issues/3605

**Comment by cklosowski** [comment]
I'm going to merge this pull request in, but leave the issue open so we make sure to communicate that this is happening and make sure we do a call for translations once we push this to `trunk` on .org so that it can be worked on in the Translate system on .org.
