### ISSUE TITLE
Custom edd_checkout_error_checks validation ignored when checking out via Stripe or PayPal

### ISSUE THREAD

**Issue by jamieburchell** [awesomemotive/easy-digital-downloads#9119]
### Expected behavior
It should be possible to add custom validation to the checkout form, like this:
https://library.easydigitaldownloads.com/checkout/limit-purchase-total.html

### Actual behavior
The custom validation works with the test gateway, but is ignored when using the Stripe or PayPal gateway.

### Steps to reproduce the behavior
1. Add custom `edd_checkout_error_checks` hooks such as the example provided above
2. Enable a live Stripe or PayPal gateway
3. Enter valid details on the checkout form, including valid card details
4. Custom validation is ignored

### Information (if a specific version is affected):
PHP Version: 7.4.28

EDD Version (or branch): 2.11.5

WordPress Version: 5.9.2

**Comment by mihaijoldis** [comment]
Hey @jamieburchell 

I just tested with the code snippet below that requires a minimum order of $150 and it blocked the purchase correctly
```
function pw_edd_limit_total_purchase( $valid_data, $post_data ) {
	
	if( edd_get_cart_total() < 150 ) {
		edd_set_error( 'too_low', 'Minimum order 150.' );
	}

}
add_action( 'edd_checkout_error_checks', 'pw_edd_limit_total_purchase', 10, 2 );
```

Can you post the snippet that you are testing with?

**Comment by jamieburchell** [comment]
Strange, I cannot get this to work outside of the test payment method.

I'm using the Snippets plugin to register this:

```
add_action( 'edd_checkout_error_checks', function ( $valid_data, $post_data ) {
    $options = get_option( 'custom_options' );
    $minimum_spend = ! empty( $options['edd_minimum_spend'] ) ? (float) $options['edd_minimum_spend'] : 0;
    if( edd_get_cart_total() < $minimum_spend ) {
        edd_set_error( 'minimum_spend_required', 'There is a minimum spend of £' . number_format( $minimum_spend, 2 ) );
    }
}, 10, 2 );
```

The snippet is set to run on site front-end at priority 10.

**Comment by jamieburchell** [comment]
> Can we consider this a non issue and close this?

Absolutely, sorry for the noise.
