### ISSUE TITLE
3.0 - Order Stats class does not account for price IDs correctly 

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9122]
### Expected behavior
I expect to be able to run order stats for variably priced products which include a price ID of `0`.

### Actual behavior
The Orders Stats class uses check like `empty`, rather than checking whether a value is null or numeric for price IDs. Example:

https://github.com/awesomemotive/easy-digital-downloads/blob/c441740dd998c3fbe651534aac2f4e51a3057975/includes/class-stats.php#L577-L579

The above will not query for the `0` variation of a product.

### Steps to reproduce the behavior
1. If you start with the EDD demo content, you'll have a product with a `0` price ID.
2. Create orders for that product/price ID.
3. Check the Reports > Downloads screen. The price label will not be correct, for example, but I expect the stats to be incorrect in places as well.

### Information (if a specific version is affected):
PHP Version: 7.4
EDD Version (or branch): release/3.0
WordPress Version: 5.9.2

Any other relevant information:
Encountered this while reading through the class code when working on #9080.

**Comment by cklosowski** [comment]
Initially I was going to mark this for 3.0.5 (our catchall for fast follow for release, but being that we're an older store that is going to need to see this data to verify some things, we should fix it in the final 3.0 release.
