### ISSUE TITLE
3.0 - Rename "Privacy" to "Policies" in Settings

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9136]
### Expected behavior

I expect "Privacy" to contain only privacy related options.

### Actual behavior
Not technically a "bug", but "Privacy" does not make much sense when it also contains terms, erase options, etc. I believe renaming it to "Policies" makes more semantic sense.

**Comment by cklosowski** [comment]
Since we're about to enter a 'string lock' for 3.0 so we can get translators on board, we'll get this in.
