### ISSUE TITLE
3.0 - Move customer emails/addresses to tabs on customer details screen

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9148]
### Explain your enhancement (please be detailed)
We should register new tabs for customer addresses and (I think) emails on the customer details screen.

### Justification or use case
For a store which does not collect customer addresses at all, it's been reported that it seems off to display physical addresses above recent orders. Even for a storefront which does collect addresses (taxes), that's not necessarily "primary" information.

Since every customer does have an email address, that's maybe less important to move; however, the primary address is already displayed at the top of the main details screen. Additionally, creating an Emails tab would be consistent with the order details tabs:

![image](https://user-images.githubusercontent.com/4853066/164296840-4199e89c-2797-47b6-bdf2-edd1cc7a43bf.png)

**Comment by cklosowski** [comment]
Marking this for 3.0 so we can get it in with String lock approaching.
