### ISSUE TITLE
3.0 - Add action to edd_destroy_order

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9156]
### Expected behavior
I expect to be able to 'hook' into the delete/destroy order action and remove anything custom added via third-party integrations (in this case - term associations).

### Actual behavior
No action/filter is provided, other than hooking in early to `edd_delete_order` (not ideal) and hoping for the best.

While this really should be a BerlinDB abstraction with custom actions added to the `delete_item` and other methods, etc. To keep things simple, having an action at the bottom of this function keeps things simple.

**Comment by davidsherlock** [comment]
Doh...must have missed that one (I am usually always up to date as well...).

Not to derail this issue, but can you consider merging these ones: #9116 and #8934

I am building a collection of commercial third-party EDD plugins for the 3.0 release and these would help me a lot! Have 8 plugins ready to go already using the new architecture (custom tables, multi-currency support, new reports, etc).

**Comment by robincornett** [comment]
No worries, it's a pretty recent update!

I'll follow up with Chris on those two and see what he says. Thank you!

**Comment by davidsherlock** [comment]
@robincornett Any word on getting this one merged? Would help me a lot! I will make the changes needed

**Comment by robincornett** [comment]
@davidsherlock The action hooks have been merged:
- [edd_pre_destroy_order](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/orders/functions/orders.php#L245-L251): runs before the order is removed from the database
- [edd_order_destroyed](https://github.com/awesomemotive/easy-digital-downloads/blob/release/3.0/includes/orders/functions/orders.php#L305-L312): runs after the order is removed from the database (second parameter is the result of whether it was successfully deleted)

**Comment by davidsherlock** [comment]
@robincornett my bad, commented on the wrong issue!

The discount one (for additional content)?

**Comment by davidsherlock** [comment]
This one: https://github.com/awesomemotive/easy-digital-downloads/issues/8934
