### ISSUE TITLE
Email Reviews to Vendors

### ISSUE THREAD

**Issue by matt70** [awesomemotive/easy-digital-downloads#9158]
### Explain your enhancement (please be detailed)
Notify Easy Digital Downloads Frontend Submission vendors by email when their product is reviewed
### Justification or use case
Nobody can check their products everday, just to see, if there is a new review...
So please put this feature into the reviews extension.
I'm waiting for this feature for more than three years now.
I know you are working on the release of 3.0, but there must be a progress in your extensions, too.

Today I'm asking again for this feature, cause I saw, that @davidsherlock already wrote some code for this.
https://arraypress.com/notify-vendors-by-email-when-their-product-is-reviewed/
Unfortunately the code does not work anymore :-(

**Comment by davidsherlock** [comment]
Did you enable the reviews in the settings? It works fine here on my testing.

**Comment by davidsherlock** [comment]
@matt70,

Copy and paste this into your child theme functions.php file:

```
/**
 * Maybe notify the vendor about the submitted review.
 *
 * @param string $email_body  Body of the email.
 * @param int    $review_id   Review ID.
 * @param array  $review_data Review Data.
 *
 * @return string $email_body Body of the email.
 * @since 1.0.0
 *
 */
function ds_maybe_notify_vendor( $email_body, $review_id, $review_data ) {
	$post_author_id    = get_post_field( 'post_author', $review_data[ 'comment_post_ID' ] );
	$post_author_email = get_userdata( $post_author_id )->user_email;

	$from_name  = edd_get_option( 'from_name', wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES ) );
	$from_email = edd_get_option( 'from_email', get_bloginfo( 'admin_email' ) );

	$subject = edd_get_option( 'edd_reviews_settings_emails_subject', sprintf( __( '[%1$s] New Review: "%2$s"', 'edd-reviews' ), get_bloginfo( 'name' ), $review_data[ 'review_title' ] ) );
	$subject = wp_strip_all_tags( $subject );

	$headers = "From: " . stripslashes_deep( html_entity_decode( $from_name, ENT_COMPAT, 'UTF-8' ) ) . " <$from_email>\r\n";
	$headers .= "Reply-To: " . $from_email . "\r\n";
	$headers .= "Content-Type: text/html; charset=utf-8\r\n";

	$emails = EDD()->emails;
	$emails->__set( 'from_name', $from_name );
	$emails->__set( 'from_email', $from_email );
	$emails->__set( 'headers', $headers );
	$emails->__set( 'heading', __( 'New Review', 'edd-reviews' ) );

	$emails->send( $post_author_email, $subject, $email_body );

	return $email_body;

}

add_filter( 'edd_reviews_review_notification', 'ds_maybe_notify_vendor', 3, 10 );

```

I have removed the need for the option for you

**Comment by matt70** [comment]
Thanks for the fast change. I test it...

**Comment by matt70** [comment]
Cool the plugin sends the email to the vendor, too.
The only problem. The subject is the same as in the noticfication to the admin "new comment to admin"
Is there a way to change it for the vedor email, to just "new comment" ?

**Comment by davidsherlock** [comment]
I haven't used the reviews plugin for a while, but the title for the emails is set in the settings for the email that goes out.

I set it here:

`$subject = edd_get_option( 'edd_reviews_settings_emails_subject', sprintf( __( '[%1$s] New Review: "%2$s"', 'edd-reviews' ), get_bloginfo( 'name' ), $review_data[ 'review_title' ] ) );`

You change it to what you want here:

`$subject = sprintf( __( '[%1$s] You have a new product review: "%2$s"', 'edd-reviews' ), get_bloginfo( 'name' ), $review_data[ 'review_title' ] );`
