### ISSUE TITLE
3.0 - add a filter for customer row actions

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9161]
### Explain your enhancement (please be detailed)
We should allow the customer row actions to be filtered.

### Justification or use case
It's been [requested for our developer tools extension](https://github.com/awesomemotive/edd-dev-tools/issues/13). Additionally, this would make the customer row actions consistent with what we already provide for discounts, API keys, and orders.

Note: we have three customer tables (customers, email addresses, and physical addresses).

**Comment by cklosowski** [comment]
This has a PR just needs to be refreshed.
