### ISSUE TITLE
3.0 - Customer Orders link in the Logs section shows all orders

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9169]
### Expected behavior
Clicking on the Customer Orders when viewing an Order > Logs should show me just orders for that customer

### Actual behavior
I see all orders on the site

### Steps to reproduce the behavior
1) Open an order go to Logs then click on Customer Orders

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): 3.0

https://a.supportally.com/lANrCB clicking the Customer Orders shows https://a.supportally.com/oIDAnt

**Comment by robincornett** [comment]
Closing as it was actually fixed in commit 695218a.
