### ISSUE TITLE
3.0 - Create an order item helper method to indicate that the file(s) can be downloaded

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9179]
### Explain your enhancement (please be detailed)
We should add a method to the `Order_Item` class to indicate somehow that files, for example, for an order item, can be downloaded.

### Justification or use case
Making a helper method will allow us to be consistent in applying the logic. For example, our download history template right now checks if an order item status is `complete` or `partially_refunded`, but the order item template for the order details screen just checks if the status is `complete`, and will not show links for partially refunded items.

This code works but `is_downloadable` is likely not the language we want long term:

```php
	/**
	 * Checks the order item status to determine if it is downloadable.
	 *
	 * @since 3.0
	 * @return bool
	 */
	public function is_downloadable() {
		return in_array( $this->status, array( 'complete', 'partially_refunded' ), true );
	}
```

**Comment by cklosowski** [comment]
After some discussion, we decided to go with the verbiage `is_deliverable` to determine if an order item is at the point where it can be provided to a customer.
