### ISSUE TITLE
3.0 - Bundle downloads failing with Error 102: You do not have permission to download this file

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9182]
### Expected behavior
I expect to be able to download all the files from bundle purchases, but in the recent 3.0 branch these are failing.

### Actual behavior
I get the following error:

`Error 102: You do not have permission to download this file`

This does not happen with normal downloads, just bundles. I wil

### Steps to reproduce the behavior
1) Create a bundle product. In my case I had two products assigned
2) Make sure each product has a single file associated with it (or multiple).
3) Purchase the bundle and try to download the files. You should see the above error.

### Information (if a specific version is affected):
PHP Version: 8.0.0

EDD Version (or branch): 3.0 (latest)

WordPress Version: 5.9

Any other relevant information:

**Comment by mihaijoldis** [comment]
I was able to replicate this on the same release/3.0 branch too.

**Comment by robincornett** [comment]
Confirmed: looks like `edd_order_grants_access_to_download_files`, which is a function new to 3.0, needs to be updated to account for bundle files.
