### ISSUE TITLE
3.0 - Delete Customer link in customer list table doesn't go to the correct tab

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9201]
### Expected behavior
If I click a link in the customer list admin table, I expect it to go to the tab to delete the customer.

### Actual behavior
The link:
```
https://edd.local/wp-admin/edit.php?post_type=download&page=edd-customers&view=delete&id=79
```

The link should really be:
```
https://edd.local/wp-admin/edit.php?post_type=download&page=edd-customers&view=overview&id=79#edd_general_delete
```

### Steps to reproduce the behavior
1. Visit Downloads > Customers.
2. Click the "Delete" link for a customer.

### Information (if a specific version is affected):
PHP Version: 7.4
EDD Version (or branch): release/3.0
WordPress Version: 6.0-RC2

**Comment by davidsherlock** [comment]
Here is it: #8706

**Comment by robincornett** [comment]
Whoops, thanks @davidsherlock!
