### ISSUE TITLE
v2.11.4 breaks custom setting tabs

### ISSUE THREAD

**Issue by leewillis77** [awesomemotive/easy-digital-downloads#9225]
### Expected behavior
Extension settings page implementation continues to work upgrading from EDD v2.11.3.1 to latest version.

### Actual behavior
After upgrading to any release after v2.11.4, the example settings code below fails to render a settings tab.

### Steps to reproduce the behavior
1) Install EDD v2.11.3.1
2) Add the following code to your site
3) Confirm that the "Foo" settings tab is displayed, and rendered correctly

```php
add_filter( 'edd_settings_tabs', function ( $tabs ) {
	$tabs['foo'] = 'Foo';
	return $tabs;
} );

add_filter( 'edd_settings_sections', function ( $sections ) {
	$sections['foo'] = array(
		'bar' => 'Settings',
	);
	return $sections;
} );

add_filter( 'edd_registered_settings', function ( $fields ) {
	$fields['foo'] = [];
	return $fields;
} );

add_action( 'admin_init', function() {
	add_settings_section(
		'edd_settings_foo_bar',
		__return_null(),
		'__return_false',
		'edd_settings_foo_bar',
	);

	add_settings_field(
		'edd_settings[foo_bar_intro]',
		'Text here',
		'test_render_intro',
		'edd_settings_foo_bar',
		'edd_settings_foo_bar',
		array(
			'id'      => 'foo_bar_intro',
			'desc'    => 'Foo',
			'name'    => 'Bar',
			'section' => 'foo',
		)
	);
} );

function test_render_intro( $args ) {
	echo 'Foo';
}
```

The same code running on EDD v2.11.4 or above fails to render the settings tab

**Comment by cklosowski** [comment]
@robincornett can we look into this please?
