### ISSUE TITLE
3.0 - every order should have a currency assigned

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9239]
### Expected behavior
When I create an order, I expect it to always have a currency assigned, even if the order is free.

### Actual behavior
When using the Free Downloads extension with email verification enabled, that extension creates a pending payment (not an order), and no currency is assigned, even when the order is completed.

### Steps to reproduce the behavior
1. Activate Free Downloads and make sure that the user has to confirm the download "purchase" by email verification.
2. Generate some free download orders.
3. Check the database. There are no currencies assigned.

### Information (if a specific version is affected):
PHP Version: 8.0
EDD Version (or branch): release/3.0
WordPress Version: 6.0

Any other relevant information:
Although we could fix this in Free Downloads by explicitly setting the currency for the pending payment there, it's still possible to use the EDD Payment class to create an order with no currency assigned. I think that where the order queries class extends the BerlinDB `add_item` method, we should enforce the currency.

Some properties are already being enforced by the payment class, either by default (gateway always defaults to manual) or dynamically (the IP and payment key); we may want to consider moving those to the order queries class, if possible.

**Comment by mihaijoldis** [comment]
Would this need to be tested with the multiple currency extension too?

**Comment by robincornett** [comment]
@mihaijoldis yes we would definitely want to test with that, but I doubt it will affect it. This should just be the final fallback if no currency is explicitly set when the order is added to the database.
