### ISSUE TITLE
3.0 - Adding more than one additional customer email in admin causes issues

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9254]
### Expected behavior
I expect to be able to add more than one additional email address while on the customer edit/screen.

### Actual behavior
While this is not a "common" workflow, if you try and add more than 1 additional email on the customer edit/view screen (under the emails tab), when you get to the second one it does not add until refreshed and infinitely "spins" without refreshing the page. This can be resolved by physically refreshing the browser but somewhat confusing for non-technical users.

### Steps to reproduce the behavior
1) Goto a customer then the "Emails" tab
2) Add an email (don't make it primary), just an additional address.
3) It should add fine.
4) Now don't refresh and add another one, it breaks...

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): latest (3.0)

**Comment by cklosowski** [comment]
@davidsherlock The page should refresh on it's own. If it is not then something else is going on:

```
if ( true === response.success ) {
	window.location.href = response.redirect;
} else {
```

When it is done 'adding fine'. the page should refresh with the messaging that it was successfully added.
<img width="370" alt="Screen Shot 2022-06-28 at 5 01 02 PM" src="https://user-images.githubusercontent.com/1390124/176323847-4e2034f7-7de4-4cde-9f54-bc08deee7001.png">

If your site is not reloading the page, then something is likely causing output of an error in the JS on the page.

**Comment by cklosowski** [comment]
Are you saying that it is after the refresh, that it takes another refresh to add?

**Comment by mihaijoldis** [comment]
Just tested this and the page reloads itself after adding the new email.
Latest 3.0 branch and a bunch of other extensions installed.

**Comment by davidsherlock** [comment]
Add a second email right after adding the first one (don't refresh).

**Comment by davidsherlock** [comment]
It gets stuck, see here...

<img width="2144" alt="Screenshot 2022-06-29 at 18 31 36" src="https://user-images.githubusercontent.com/22668877/176476501-39eb8c8e-5dad-4262-ab00-cc263183bc89.png">

**Comment by davidsherlock** [comment]
Yeah, it breaks it for sure. I don't like relying on reloads, so my solution (for my own EDD add-on) was to send back the HTML row with the JSON and append it to the table. I can put forward a PR for that later (to fix this issue), or if someone wants to look into this issue, it should be fixable...

**Comment by cklosowski** [comment]
I think this is kind of an edge case, so we'll tackle it in a post-3.0 release. The use case of adding multiple email addresses in a row for a customer is pretty low.

**Comment by davidsherlock** [comment]
I agree tbh, just do it later, it's not crucial.
