### ISSUE TITLE
Fatal error in structured data if download cannot be retrieved

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9279]
### Expected behavior
I expect to not have a fatal error when generating the structured data.

### Actual behavior
Reported by a customer (logs):
```
[14-Jul-2022 11:42:35 UTC] PHP Fatal error: Uncaught Error: Call to a member function get_sku() on null in /wp-content/plugins/easy-digital-downloads/includes/class-structured-data.php:140
Stack trace:
#0 /wp-content/plugins/easy-digital-downloads/includes/class-structured-data.php(98): EDD\Structured_Data->generate_download_data(NULL)
#1 /wp-content/plugins/easy-digital-downloads/includes/class-structured-data.php(249): EDD\Structured_Data->generate_structured_data()
#2 /wp-content/plugins/easy-digital-downloads/includes/class-structured-data.php(276): EDD\Structured_Data->encoded_data()
#3 /wp-includes/class-wp-hook.php(307): EDD\Structured_Data->output_structured_data('')
#4 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /wp-content/plugins/easy-digital-downloads/includes/class-structured-data.php on line 140
```

### Steps to reproduce the behavior
Honestly not sure, but I assume that `edd_get_download` did not return a full download object. (Interesting that lines 134-135 in the same file did not throw an error, unless they did and were just not included in the report.)

### Information (if a specific version is affected):
PHP Version: unknown
EDD Version (or branch): main (3.0)
WordPress Version: unknown

Any other relevant information:
If the download object can't be retrieved at the beginning of this method, it seems logical for it to return early, rather than just assuming that `edd_get_download` worked.

**Comment by dgoldak** [comment]
Update from customer:
Hi the quick fix seems to have worked.

This was a result of commenting out this line:
\easy-digital-downloads.30\includes\class-structured-data.php
line 36 which is "$this->hooks();"
