### ISSUE TITLE
Searching the orders table no longer works as it used to

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9280]
### Expected behavior
Searching for orders by ID/Purchase key and other variables should work

### Actual behavior
Right now searching by order ID or purchase key does not return any data for me.

### Steps to reproduce the behavior
1) Go to Downloads > orders 
2) Enter an order ID or the purchase key and try a search

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
In 2.x version and in our in admin help text and docs we list the possible search terms below:
```
This search accepts:

    The purchase ID
    The 32-character purchase key
    The customer’s email address
    The customer’s name or ID prefixed by user:
    The Download ID prefixed by #
    The Discount Code prefixed by discount:
    A transaction ID prefixed by txn:
```
I feel like if possible we should allow all of those terms and if not clarify exactly what can be searched.

**Comment by dgoldak** [comment]
Another customer noticing this isn't working in 3.0:
https://secure.helpscout.net/conversation/1949665667/2051857?folderId=5762528

**Comment by mihaijoldis** [comment]
Anoter report of searching by discount code is not working. https://secure.helpscout.net/conversation/1953125312/2057907?folderId=5747299
