### ISSUE TITLE
Earnings in reports are not showing correct numbers for refunded orders

### ISSUE THREAD

**Issue by zkawesome** [awesomemotive/easy-digital-downloads#9286]
### Expected behavior
When I place two orders for 5 USD each, and then I refund one, my `Earnings` in the `Overview` report should show 5 USD.

### Actual behavior
It's showing 0 USD earnings.

### Steps to reproduce the behavior
1) Place two orders and complete them
2) Refund one order
3) Go to `Reports` -> `Overview` and check the graphs and `Earnings` tile.

EDD Version (or branch): `3.0`

<img width="620" alt="image" src="https://user-images.githubusercontent.com/108748561/179226598-209b7f6f-cbea-4f8f-ba34-cf3fbbcfdacf.png">

**Comment by robincornett** [comment]
Zan and I chatted some on Slack and I'm currently agreeing with him that net queries on orders should actually use the same array of order statuses as gross queries, but include the refund `type`....so essentially net order queries shouldn't modify the status query, but the type query.

**Comment by cklosowski** [comment]
@zkawesome @robincornett Okay let's see how that approach looks. Essentially instead of pulling only 'net' order statuses on the queries, we'd pull gross statuses for the type of 'sale' and query orders with the type of 'refund' as the negation.

Am I reading this right?
