### ISSUE TITLE
Decrease discount usage count when order is deleted

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9299]
At the moment if you create an order with a discount code the `use_count` is incremented and as such the discount can no longer be deleted.

If it was a test order on your website for example and you place the order in the Trash and then actually delete it we should consider decreasing the use_count which will set it back to 0 in this example and the discount could now be deleted.

This was brought up via https://secure.helpscout.net/conversation/1953125312/2057907?folderId=5762562

**Comment by cklosowski** [comment]
As a note, we already allow deletion of a discount, so long as it hasn't been used, so I suspect that making sure we reduce the count on a discount that has a deleted order should solve the deletion issue.
