### ISSUE TITLE
3.0 - Add Custom Checkout Fields and Data saving failure

### ISSUE THREAD

**Issue by sunbbon88** [awesomemotive/easy-digital-downloads#9304]
### Steps to reproduce the behavior

According to the official tutorial, the Add Custom Checkout Fields code ( via:https://easydigitaldownloads.com/docs/custom-checkout-fields/) was added to the theme's functions.php file, and the "Phone" field was successfully added to both the "Checkout" page and the "View Order Details" page.
However, the "Phone" field data submitted in the Checkout form on the Checkout page is not saved to the database, resulting in the value of the "Phone" field on the "View Order Details" page being **none**.

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0.1

WordPress Version: 6.0.1

**Comment by cklosowski** [comment]
@sunbbon88 I've updated that code snippet to reflect the use of the new order functions and meta, please review that and give it a try. Thanks!

**Comment by sunbbon88** [comment]
Thank you very much, the latest code is valid now. 
This saves a lot of time for people like me who need to extend the Checkout Form functionality.
