### ISSUE TITLE
JavaScript error when cancelling a transaction and PayPal is the only gateway

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9305]
At the moment in 3.X version if you click the PayPal button to pay, the modal windows pops up and then you close it you get a weird error message displayed on the page above the button: https://a.supportally.com/lHzTgx

This was reported here https://secure.helpscout.net/conversation/1954893974/2062354?folderId=5747299 and saw another similar one earlier today.

_Originally posted by @mihaijoldis in https://github.com/awesomemotive/easy-digital-downloads/issues/9094#issuecomment-1190785795_

Specifically, the message is:
```
Cannot read properties of null (reading 'setAttribute')
```
The changes made in #8883 need to be updated to make sure that the `setAttribute` only runs if there is something to update.

**Comment by mihaijoldis** [comment]
I get the same thing with 2 gateways active, Stripe and PayPal for example.
In this isnstance the error message is `document.getElementById(...) is null`

**Comment by mihaijoldis** [comment]
Also perhaps related to this error. When the modal window opens you have a Cancel and rerturn link at the bottom. Clicking that should redirect you to the URL on the link `https://www.localhost.com/edd/checkout/transaction-failed/?payment-id=9&token=9AM07440AF001231A` but that does not happen. You are left on the Checkout page and again the same message shows `document.getElementById(...) is null`
