### ISSUE TITLE
Edit Order - form is not saving the fields

### ISSUE THREAD

**Issue by zkawesome** [awesomemotive/easy-digital-downloads#9311]
### Expected behavior
In administration, when I change order details (billing address) and save, new details should persist and save.

### Actual behavior
Billing address fields are reset when I submit the form (Save order).

### Information:
PHP Version: 7.4

EDD Version (or branch): `release/3.0.2`

WordPress Version:  6.0.1

**Comment by sunbbon88** [comment]
I had the same problem and it still exists in the latest update, version 3.0.2.

**Comment by cklosowski** [comment]
The root cause here is that when you don't have an address already on the order, the `order_address_id` being passed in is `0` and that cannot be used to update an order address.
