### ISSUE TITLE
3.0 - $edd_logs->get_log_count doesn't work for file download logs

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9313]
### Expected behavior
When I use this legacy code, I expect it to return accurate results:

```php
global $edd_logs;
$download_id = 942;
$count       = $edd_logs->get_log_count( $download_id, 'file_download' );
```

### Actual behavior
It returns the count of all file download logs, not just the one for that download ID.

### Steps to reproduce the behavior
Run the code above, which works in EDD 2.11 but not 3.0.

### Information (if a specific version is affected):
PHP Version: 8.0
EDD Version (or branch): main (3.0)
WordPress Version: 6.0.1

Any other relevant information:
Looking at the `get_log_count` method, the `$object_id` parameter is set up as the `object_id` in the array of parameters used to query logs, but there isn't an `object_id` column in the file download logs table--I think that should be `product_id` instead. I think the same problem exists for the API requests logs table, but I'm not sure what the queried object ID might be there...looking at the method in 2.11, the object ID is the `post_parent` for the logs, but looking at our migration, the `post_parent` isn't migrated for API logs.

**Comment by cklosowski** [comment]
@robincornett , how frequently are we using this legacy method to get logs?

**Comment by robincornett** [comment]
I don't know that we are using it but I've encountered two different users with custom code who were. I've pointed them to the new code to use. As we have updated extensions we have updated them to use EDD 3.0 functions.
