### ISSUE TITLE
3.0 - Guest customers for existing users are not connected to the user

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9344]
### Expected behavior
When an existing user who is not already a customer makes a purchase, I expect the customer to be attached to the user by `edd_connect_guest_customer_to_existing_user`.

### Actual behavior
That function is hooked into `edd_customer_post_attach_payment`, which is not running during the normal checkout process in EDD 3.0.

### Steps to reproduce the behavior
1. Make sure that guest checkout is enabled.
2. Make a purchase with an email address which belongs to a registered user who is not already a customer. This _should_ link the new customer automatically to the existing user, but it does not.

### Information (if a specific version is affected):
PHP Version: 8.0
EDD Version (or branch): 3.0 (main)
WordPress Version: 6.0

Any other relevant information:
Looking at the customer `attach_payment` method, that's where this hook is registered. However, it never fires because there is an early return if the order is already attached to the customer, and the way the orders are created in 3.0, the customer ID is assigned to the order before this method is even called. It also might mean that the customer stats are not updated, but I'm not seeing that happen elsewhere, so I think they are being updated during the purchase process, just not here.

Not sure if the early return needs to be updated (I assume it was present in 2.x but with the improved order creation process it's not working the same way), or if the function needs to be connected to a different hook, but marking this as a regression.

**Comment by cklosowski** [comment]
Need to re-open this and further improve it, turns out this makes auto register force a user verification process.

I'll take a slightly different approach to it.
