### ISSUE TITLE
3.0 - Enabling Automatic Updates causes "Invalid data. No selected item." error 

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9346]
### Expected behavior
i expect to be able to enable automatic updates on EDD without seeing an error on the plugins screen.

### Actual behavior
When I enable automatic updates on EDD, I see this error:

`Invalid data. No selected item.`

This error does not show when enabling automatic updates on any other plugins.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0.2.1

WordPress Version: latest

**Comment by davidsherlock** [comment]
Seems to originate from here: https://developer.wordpress.org/reference/functions/wp_ajax_toggle_auto_updates/

**Comment by cklosowski** [comment]
I'm able to both enable and disable automatic updates of EDD on the specified version of EDD. Since EDD is from .org there is no special handling of the automatic updates for core itself.

**Comment by davidsherlock** [comment]
Discovered source of this issue was another library being loaded by another plugin. Will close.
