### ISSUE TITLE
Additional fields not stored for PayPal payments

### ISSUE THREAD

**Issue by raneri** [awesomemotive/easy-digital-downloads#9348]
_Hi, I'm posting this issue that [I reported on the WordPress Plugin Repository](https://wordpress.org/support/topic/additional-fields-not-stored-for-paypal-payments/) support forum, but without getting a solution (by now):_

Since we upgraded to 3.x our custom fields (they were added since several years, following the example here: https://easydigitaldownloads.com/docs/custom-checkout-fields/ ) stopped working. They are asked to the user during the checkout, but nothing is stored: the entire “payment_meta” row in the table “wp_edd_ordermeta” is missing.

**It seems to happen only with PayPal payments**: if someone pays with Stripe (or if I try to send a free order with a 100% discount coupon) everything works correctly.

**Comment by cartoonsmart** [comment]
I was able to replicate the issue. Nothing saved with a real Paypal payment, but it does get saved with a discount coupon of 100%). For the Paypal order meta_value is only a:0:{}

**Comment by cartoonsmart** [comment]
I think I answered my own question there as I noticed that documentation link that @raneri referenced was updated for a post EDD3 world (thanks to Chris probably!).  So @raneri I've tested this on my end and it works with a real Paypal order. The code commented with "legacy stuff" stores the payment meta the old way of doing things in a big fat array. The **edd_add_order_meta** puts a unique row in the new database **wp_edd_ordermeta** for just that one piece of meta data. Which is awesome (again, thanks Chris). 

```
function sumobi_edd_built_order( $order_id, $order_data ) {

	 if ( 0 !== did_action('edd_pre_process_purchase') ) {   

	 	$payment_meta = edd_get_payment_meta( $order_id ); //legacy stuff

	 	 if ( isset( $_POST['edd_phone']) == true ){

            edd_add_order_meta( $order_id, 'edd_phone', sanitize_text_field($_POST['edd_phone']) ); //post EDD 3.0 world
            $payment_meta['edd_phone'] = isset( $_POST['edd_phone'] ) ? sanitize_text_field( $_POST['edd_phone'] ) : ''; //legacy stuff

        }


	 	edd_update_payment_meta($order_id, "payment_meta", $payment_meta);  //legacy stuff


	 }



}

add_action( 'edd_built_order', 'sumobi_edd_built_order', 10, 2);
```

**Comment by raneri** [comment]
Thank you so much @cartoonsmart this seems to solve the issue. I modified your suggested function to make it work also in backward compatibility, storing an array into the "payment_meta" metafield, instead of saving the single fields in separate rows in the wp_edd_ordermeta table: this will show the filled fields in the order, just like it worked in the past:

`
function sumobi_edd_store_custom_fields( $order_id ) {

	if ( 0 !== did_action('edd_pre_process_purchase') ) {
		$domain = isset( $_POST['edd_domain'] ) ? sanitize_text_field( $_POST['edd_domain'] ) : '';
		$companyname = isset( $_POST['edd_companyname'] ) ? sanitize_text_field( $_POST['edd_companyname'] ) : '';
		$vat = isset( $_POST['edd_vat'] ) ? sanitize_text_field( $_POST['edd_vat'] ) : '';
		$sdi = isset( $_POST['edd_sdi'] ) ? sanitize_text_field( $_POST['edd_sdi'] ) : '';
		$pec = isset( $_POST['edd_pec'] ) ? sanitize_text_field( $_POST['edd_pec'] ) : '';

		edd_add_order_meta(
			$order_id,
			'payment_meta',
			[
				'domain' => $domain,
				'companyname' => $companyname,
				'vat' => $vat,
				'sdi' => $sdi,
				'pec' => $pec,
			]
		);
	}

}
add_filter( 'edd_built_order', 'sumobi_edd_store_custom_fields');
`

**Comment by cartoonsmart** [comment]
No problemo. Since you don't have a lot of custom fields, you might want to store both the old-school array as well as the individual fields, like...  edd_add_order_meta($order_id, 'vat', $vat ); 

Just so you have the best of both worlds going forward. Glad to help!

**Comment by cklosowski** [comment]
Fantastic! thank you @cartoonsmart and @raneri! So to confirm before I close, the updated code snipped that I adjusted right after the 3.0 release fixes things and works as you expect?

**Comment by raneri** [comment]
Yes, for me it's fixed. Thank you very, very much!
