### ISSUE TITLE
Update receipt template check/modification

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9354]
### Explain your enhancement (please be detailed)
We should review the `update_receipt_template` method.

### Justification or use case
A customer has reported that it's running more than it ought. Looking at the code, it looks like it might be updating the template file even if it doesn't need to (if it's already been done). We should consider changing that so that it doesn't run if the strings to replace are not found; additionally, maybe this should run on a cron event hook.

Alternatively, this could be run as an upgrade routine and only run once. The concern there is if a store updates the template to revert back to using `get_post` instead of `edd_get_payment`, that the receipt template will be broken.

**Comment by cklosowski** [comment]
@robincornett Lets do this on the first admin page load we fine, mark it somewhere in the DB (not as an upgrade routine) and then we can run it on a cron every day on the EDD Daily events process.

**Comment by cklosowski** [comment]
We can follow up with a 3.1 issue to remove the cron event.

**Comment by cklosowski** [comment]
Looking at this, it's not actually changing the template every time, just finding the file, and running a strpos on it. However, I don't think we need to over-engineer this. I'm just going to use a transient to check it once a day.
