### ISSUE TITLE
Remove/repurpose "EDD 3.0 Beta" issue template

### ISSUE THREAD

**Issue by JJJ** [awesomemotive/easy-digital-downloads#9376]
See: e0065c0e9f412df95a00e45d8d62670b40c1d235

![jjj-on-2022-08-21-at-16-23-55@2x](https://user-images.githubusercontent.com/88951/185811590-c0637892-dc36-4e8f-923a-a528224cbc69.png)

**Comment by cklosowski** [comment]
Thanks @JJJ I'll remove that now :)
