### ISSUE TITLE
v3 CLI Migrations Memory Usage

### ISSUE THREAD

**Issue by pgibson1-godaddy** [awesomemotive/easy-digital-downloads#9390]
### Expected behavior

Use a reasonable amount of memory or provide tooling to batch and resume the upgrade via CLI. It seems like for large sites, the CLI is the [recommended method of upgrading](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/admin/upgrades/upgrade-functions.php#L267-L281) but there seem to be large expectations about available resources.

### Actual behavior

When using the CLI to process the migration to custom tables on EDD v3 (even when processing the steps individually), memory usage is growing with every loop iteration to a point that it grinds to a halt or gets killed.

For example, on a site that has approximately 1 million order notes (`comment_type = "edd_payment_note"` in `comments` table), running this:

```
wp edd migrate_order_notes
```

Results in around 15GiB of memory usage when the process is only 20% completed, this usage seems to keep growing indefinitely until the process ends, meaning we would need approximately 75GiB to complete the process.

### Steps to reproduce the behavior
1) Have a large amount of orders/order notes/etc.
2) Run `wp edd migrate_order_notes`

### Information (if a specific version is affected):
PHP Version: 7.4.30

EDD Version (or branch): 3.0.3

WordPress Version: 6.0.1

Any other relevant information:

We only had this problem (so far) with order notes, likely because there are a lot of them, however I'd expect this problem to occur for the other steps in the migration process as well if the tables were large enough.

**Comment by cklosowski** [comment]
We have an open PR on this already, just haven't been able to run it through it's paces to ensure it solves the problem: #9282

**Comment by cklosowski** [comment]
The attached PR actually looks at doing this for `logs` not notes.

**Comment by pgibson1-godaddy** [comment]
This migration was able to pass the `logs` stage without much incident I think - but to confirm the issue keeps growing for order notes, it's currently at 43% complete and up to ~31.5 GiB of memory usage, so it's definitely still tracking as expected in the opening note in the issue.

**Comment by cklosowski** [comment]
@JJJ what are your thoughts on this if you don't take a mind looking? and maybe adjusting the PR to suite that and make the queries more efficient?

**Comment by JJJ** [comment]
@cklosowski I do not mind, at all 💟💟

Adjusting the PR is the least we can do, and I'm happy to get that done.

I believe the strategy in the PR is better-enough to be employed for all steps/components. I'll start with Notes so @pgibson1-godaddy has what he needs.

Do you want separate PRs, or one monolithic one?

**Comment by cklosowski** [comment]
Let's just do it all in one if possible. That will make testing far easier.

**Comment by cklosowski** [comment]
This is going to make it into EDD 3.1 @pgibson1-godaddy and @JJJ Thanks for your help!
