### ISSUE TITLE
Sprintf warning for admin bar menu item

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9394]
I don't know how to replicate it as I was unable to but the warning message states: 

`Warning: sprintf(): Too few arguments in /home/customer/public_html/wp-content/plugins/easy-digital-downloads/includes/admin/admin-bar.php on line 114`

It is visible on the admin area and front-end when you are logged in. The customer said she deactivate all plugins and it is still visible.
I don't know much about how this work but maybe we don't need the %1 in that code as there is only one replacement?

**Comment by cklosowski** [comment]
after some looking this was due to a bad translation file. There isn't a lot we can do about someone who translates a string incorrectly
