### ISSUE TITLE
Logging in from the {receipt_link} page simply refreshes the login form

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9414]
### Expected behavior
When I view the {receipt_link} page as not logged in I am presented with a login form. When entering my credentials the page should log me in and show the receipt page.

### Actual behavior
The login form simply refreshes and I am not logged in.

### Steps to reproduce the behavior
1) Add {receipt_link} to your purchase receipt and make a purchase.
2) From the email, make sure you are not logged in and access that link
3) enter your login details on the form

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
Reported on .org here https://wordpress.org/support/topic/login-for-view-receipt-not-working/
I replicated it locally and the page simply refreshes. The functionality is in the 'edd_receipt_shortcode' from line 702. I also think the `$edd_login_redirect = edd_get_current_page_url();` code might not be right as that for me returns `https://www.localhost.com/edd/` instead of the full receipt view URL

**Comment by cklosowski** [comment]
@mihaijoldis Do we know if this receipt link is using the block or the shortcode?

**Comment by mihaijoldis** [comment]
When I tested this it was using the short-code. We did not have Blocks at that time. I think he was using the same thing.

**Comment by cklosowski** [comment]
@mihaijoldis This is ready for some testing.

**Comment by cklosowski** [comment]
@robincornett and I had a call about this as it does alter the behavior a bit.

Currently: After logging in, you are provided a stripped down view of the receipt
On the issue branch: you are redirected to a full page in the account.

There is a reasonable expectation that if you are being asked to login, you have a reasonable expectation that you end up in your account area where you can continue to manage your account and I'm okay with this.
