### ISSUE TITLE
Download Report Tiles and Download settings sales and earnings are not accurate

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#9424]
Update get_order_item_count and get_order_item_earnings to be more consistent with dashboard reports.

Both sections should match in this screenshot:
![Markup on 2022-09-07 at 16:09:58](https://user-images.githubusercontent.com/30910807/188981293-bc9bd3d3-5916-4c85-affa-39602129fefa.png)

https://secure.helpscout.net/conversation/2000520514/2149135?folderId=5747299

**Comment by cklosowski** [comment]
@robincornett @zkawesome I think we have a situation here that we ran into with the Overview tiles.

See here where these `EDD\Stats->get_order_item_earnings()` calls have only a single `status` set, and other missing logic that we've added to the other `get_order_earnings()` methods:

https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/class-stats.php#L919-L925
