### ISSUE TITLE
Deleting customer does not delete customer's email address

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#9425]
### Expected behavior
Deleting a customer should deleting the associated email address from the customer email address table.

### Actual behavior
Customer is deleted but the email address still exists in the email addresses table with no ability to delete it.

### Steps to reproduce the behavior
1) Delete a customer (results the same regardless of "Delete all associated payments and records?" being checked or not).
2) Confirm email address does not exist in Email Addresses tab/table

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0.3

WordPress Version: 6

Any other relevant information:
Reported by customer: https://secure.helpscout.net/conversation/1999327110/2146743?folderId=5762528

**Comment by robincornett** [comment]
I think we can close this one as fixed by #9420, which was in the 3.1 release. It changed the customer deletion to use `edd_destroy_customer`, which deletes associated addresses as well as the customer object.
