### ISSUE TITLE
3.0.4 - Bundle downloads failing with Error 102: You do not have permission to download this file

### ISSUE THREAD

**Issue by maaprote** [awesomemotive/easy-digital-downloads#9427]
### Expected behavior
Download all the files from bundle purchases, but in the recent 3.0.4 version these are failing.

### Actual behavior
I get the following error:

Error 102: You do not have permission to download this file

This does not happen with normal downloads, just bundles.

### Steps to reproduce the behavior
Create a bundle product.
Make sure each product has a single file associated with it (or multiple).
Purchase the bundle and try to download the files. You should see the above error.

### Information (if a specific version is affected):
PHP Version: 8.0.0

EDD Version (or branch): 3.0.4

WordPress Version: 6.0.2

Any other relevant information:
I believe it is happening since 3.0.0
Same issue from here (https://github.com/awesomemotive/easy-digital-downloads/issues/9182). It was marked as closed/resolved, but it seems it isn't

**Comment by cklosowski** [comment]
We've been trying to replicate this but I'm coming up short. Bundles and free downloads with 100% discount codes are working fine on my end.

 @plugin-republic @maaprote I just did a compare of EDD 3.0.3 and 3.0.4 and nothing changed related to the file download process.

Can you both verify that the customer ID on the order, and the customer ID that is reporting the issue matches? 3.0.4 fixed some issues where we couldn't find customers based on 'secondary' email addresses.

If you can't find anything specific, can you please submit a support ticket so we can have a more 'specific' talk about your sites that might require asking for details we might not want to include in the public GitHub environment.

https://easydigitaldownloads.com/support

**Comment by plugin-republic** [comment]
Thanks @cklosowski - I'll raise a ticket. Just to clarify, I upgraded from 2.x direct to 3.0.4 so I don't know that a compare with 3.0.3 would necessarily show anything. The customer IDs matched.

**Comment by cklosowski** [comment]
@plugin-republic Okay, the other thing you might check (and support may ask) is if you've made template overrides in your theme for the EDD core shortcodes. There were some modifications in there to handle bundles more efficiently.

**Comment by plugin-republic** [comment]
@cklosowski - okay, by chance I discovered that the error seems to occur when downloading from the purchase_history shortcode, but not from the download_history shortcode. I don't have any theme overrides.

**Comment by maaprote** [comment]
Thank you @cklosowski ! In our case the problem was the template files that needed to be updated with new EDD 3.0 templates. The templates in question was 'history-downloads.php' and 'shortcode-receipt.php'. Thanks for your help. But we are still having a no-critical issue with the orders 'Copy Download Links' in the admin area, which seems to be not working with bundled downloads. As it is not related with the same issue initially opened here, I will open a new github issue about that.
