### ISSUE TITLE
Tax rate table is limited to display 30 items only

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9432]
### Expected behavior
The tax rates table to show more rates/all or paginate

### Actual behavior
It seems to be limited at 30 by default

### Steps to reproduce the behavior
1) Create more than 30 tax rates in your store

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
Reported by a customer here https://secure.helpscout.net/conversation/2006868523/2161040?folderId=5747299

Notes from Slack:
we should maybe look into that being something we can extend out?
This all stems from the query class base having a limit of 30 to prevent instance defaults.

**Comment by robincornett** [comment]
I think if we update the [`edd_tax_rates_callback`](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/admin/settings/register-settings.php#L2690) to pass a number to the `edd_get_tax_rates` function, this will work, eg:

```php
$rates = edd_get_tax_rates( array( 'number' => 9999 ), OBJECT );
```
