### ISSUE TITLE
Stats API is crashing the site when Time zone is UTC +

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9435]
### Expected behavior
Accessing the API via /edd-api/stats?type=earnings&date=range&startdate=20220905&enddate=20220906 to work

### Actual behavior
The website/database crashes. Stuck in a constant loading.

### Steps to reproduce the behavior 
1) In your WordPress settings change Timezone to anything UTC +. It can be +30 or +9
2) Check the API endpoint as above

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
Issue discovered in a ticket here https://secure.helpscout.net/conversation/2004134129/2156206?folderId=5762562
Reverting back to EDD 3.0.3 seems to work.

**Comment by mihaijoldis** [comment]
Forgot to mention, the website crashes when the code execution reaches this block:
https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/api/class-edd-api.php#L1273-L1297

**Comment by cklosowski** [comment]
Based on the details here, it is likely that our issue is that the while loop never hits the end of the loop due to the timezone adjustment here.

**Comment by mihaijoldis** [comment]
Another report for this issue. Timezone is set to UTC +2

**Comment by mihaijoldis** [comment]
From the same customer I last reported:
```
I inspected the API functions and I found you are converting dates in UTC before to query the DB but the times in DB are already saved using the timezone of WP settings.

In the file:

/easy-digital-downloads/includes/reports/reports-functions.php (around rows 676-680)
you convert by default the dates to UTC

if ( $convert_to_utc ) {
// Convert the values to the UTC equivalent so that we can query the database using UTC.
$dates['start'] = edd_get_utc_equivalent_date( $dates['start'] );
$dates['end'] = edd_get_utc_equivalent_date( $dates['end'] );
}
So in the function get_stats() in file:

/easy-digital-downloads/includes/api/class-edd-api.php (around rows 1382 and 1404)

I had to pass the "false" value to the third param so:

$dates = EDD\Reports\parse_dates_for_range( null, null, false );
So the parse_dates_for_range() function doesn't touch the hours of range.

This solution is working for our case, but I don't know if there was a specific reason for the UTC conversion (maybe for timezone far from UTC).
```

**Comment by cklosowski** [comment]
There is a specific reason for the conversion here. Dates in the DB are in UTC. The store is not in UTC, so we are adjusting the dates to be the UTC time equivalent to their timezone
