### ISSUE TITLE
Shop Worker cannot create Downloads when site is translated

### ISSUE THREAD

**Issue by dgoldak** [awesomemotive/easy-digital-downloads#9437]
### Expected behavior
User with Shop Worker role should be able to create Downloads

### Actual behavior
After clicking Add New, the follow permission error occurs: 
Lo siento, no tienes permisos para acceder a esta página.

In English:
Sorry, you do not have permissions to access this page.

This works when site language is set to English.

### Steps to reproduce the behavior
1) Create user with role set to Shop Worker
2) Create a new Download as Shop Worker
3) Change site language to Espanol
4) Create a new Download under the Shop Worker account

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0.4

WordPress Version: 6.0.2

Any other relevant information:
https://secure.helpscout.net/conversation/2010986914/2169726?folderId=5747299

Replicated issue on test site.

**Comment by robincornett** [comment]
A coworker reported to me in Slack that they were having issues with the Shop Accountant role.

Mihai also reported something similar and solved it for his site:

> Got a new one that I want someone else to test. Have a user on your site, non admin and give him the Shop Worker use role. See if you can then log in and edit an order in the admin.
> For me it did not work. I got the access denied. I installed the members plugin and viewed the Shop Worker role. everything is allowed but not working https://a.supportally.com/VQqJYu
> I unchecked that box and checked it back and now it works
> can it be some missing assignment of the actual capability ?
> when I went to the shop worker role in Members plugin to view All capabilities it did not list the edit_shop_payments after I resaved it it did

**Comment by mihaijoldis** [comment]
Also related perhaps, if I have a user with the Shop Worker role, they will not show in the box to be assigned a Download: https://a.supportally.com/n0R1Rh
In that screenshot both admin and mihaitest users are Administrators. When I change `mihaitest` to be a Shop Worker they no longer show in the selection.

**Comment by cklosowski** [comment]
The issue stems from this part of the page load in `wp-admin/includes/plugin.php`
```
function user_can_access_admin_page() {
	global $pagenow, $menu, $submenu, $_wp_menu_nopriv, $_wp_submenu_nopriv,
		$plugin_page, $_registered_pages;

	$parent = get_admin_page_parent();
```

On EDD 2.X, the `$parent` has the value `post-new.php?post_type=download`
On EDD 3.x, the `$parent` is`NULL`

This is due to the way we're removing the 'Add New' item from the Admin Menu. We need to not remove the submenu for Add New, and instead hide it with CSS.
