### ISSUE TITLE
Double item entries in orders when using products with variable pricing and updating payment meta.

### ISSUE THREAD

**Issue by mario-toursprung-com** [awesomemotive/easy-digital-downloads#9442]
### Expected behavior
Only one item per product should be added to the order.

### Actual behavior
Two items are being added in the order for each product.
One item listing just the Product name and an additional item listing the Product name concatenated with the Option Name

### Steps to reproduce the behavior
1) Vanilla install of WordPress & EDD
2) Create a test product with variable pricing e.g.

-    TEST-Product - Simple
-    TEST-Product - Extended
-    TEST-Product - Custom

3) Add a hook for **edd_built_order** in which a call to **edd_update_payment_meta** is made
4) Order the Test product and select one of the variants e.g. _Custom_
5) In the order details for this order there will be two items:
 -  TEST-Product
 -  TEST-Product - Custom
![edd-double-items](https://user-images.githubusercontent.com/2580403/190919213-8293de81-ce7d-43e8-9015-17bb44bd3b12.png)

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0.4
 
WordPress Version: 6.0.2

Any other relevant information:

We are adding some custom information to the payment meta utilizing the **edd_built_order** action hook:

```php
function edd_store_custom_fields( $order_id, $order_meta ) { 
        $order_meta['custom_field'] = 'This-is-a-custom-field-value';
        edd_update_payment_meta( $order_id, '_edd_payment_meta', $order_meta );
}
add_action( 'edd_built_order', 'edd_store_custom_fields', 10, 2 );
```

We managed to track down the issue to the following calls:
In [includes/orders/functions/orders.php:892](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/orders/functions/orders.php#L892) you are concatenating the **product name** with the variable pricing  **option name** when preparing the order data.

Later in [includes/payments/class-edd-payment.php:2306](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/payments/class-edd-payment.php#L2306), which gets called by our meta update, you look for the item in the DB using also the product name, but without concatenating the variable pricing  option name, which leads to the item not being found and subsequently being added as a separate item to the order.

I hope I managed to explain the issue. If you need any more details or information I will be glad to provide these.

**Comment by cklosowski** [comment]
@mario-toursprung-com In 3.0 you can adjust this to just use the `edd_add_order_meta` function.

`edd_add_order_meta( $order_id, $meta_key, $meta_value, $unique = false ){...}`

**Comment by mario-toursprung-com** [comment]
Hi, thanks for the clarification, we will move away from the **payment_meta** and save the custom data in a separate **meta_key**
