### ISSUE TITLE
edd_get_item_discount_amount assumes discount options have price IDs

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#9443]
### Expected behavior
When I migrate a discount code that has product restrictions, I expect the `edd_get_item_discount_amount` to not throw an error.

### Actual behavior
Because we added `price ID` support to the product restrictions in discounts in 3.0, a code that was migrated for a product that has variable prices doesn't contain the price ID options for the products.

### Steps to reproduce the behavior
1) Migrate a discount that has a product restriction for a product with variable prices.
2) Attempt to use the discount code ensuring it runs through `edd_get_item_discount_amount`
3) See a notice.

`Undefined index: options in easy-digital-downloads/includes/discount-functions.php on line 1125`

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 3.0

WordPress Version: All

Any other relevant information:

**Comment by StephenGravitt** [comment]
line 1125 assumes there is an 'options' array with the cart item in question and we're using this array as a means to grab the download price_id.

easy-digital-downloads/includes/discount-functions.php:1125
`$i_amount = edd_get_price_option_amount( $i['id'], $i['options']['price_id'] );`


However, I've notice many examples within the EDD plugin that look to the 'item_number' array as the location for the 'options' array and 'price id'. Here are a couple of those examples:
- easy-digital-downloads/includes/admin/reporting/class-export-payments.php:143
- easy-digital-downloads/includes/admin/upgrades/v3/class-data-migrator.php:937 

One potential fix would be to throw a conditional and attempt an alternate method as a backup. Not sure if the original line should just be replaced or if there is a use case for grabbing the price_id from either array or not:

```
if( isset($i['options']) ){
	$i_amount = edd_get_price_option_amount( $i['id'], $i['options']['price_id'] );
}else{
	$i_amount = edd_get_price_option_amount( $i['id'], $i['item_number']['options']['price_id'] );
}
```

many ways to fix this and we could get a little more crazy with the isset statements to make this even more safe. However, I think this fix is clean, readable, and will handle 99% of the issues.

Cart Management Table Before
![image](https://user-images.githubusercontent.com/47453180/198156383-3b9d30b5-5c88-4a86-bd21-5c1fa8278d77.png)

Cart Management Table After
![image](https://user-images.githubusercontent.com/47453180/198156470-532ffa55-a7e2-4779-acda-301203dfc8aa.png)

**Comment by robincornett** [comment]
> Issue reported https://secure.helpscout.net/conversation/2051676194/2255319?folderId=5747299
> 
> From the Barn2 team:
> 
> The reason this fails is due to the edd_get_cart_discounts_html function, used in the checkout_cart.php template. edd_get_cart_discounts_html calls "EDD()->cart->get_contents_details()" to retrieve the cart and pass it into edd_get_item_discount_amount, but this function does not include an 'options' index on cart items. edd_get_item_discount_amount accounts for this scenario with the $item parameter, but not $items.
> 
> The solution is very simple, change line 1125 of discount-functions.php to something like,
> 
> $i_amount = edd_get_price_option_amount( $i['id'], $i['options']['price_id'] ?? $i['item_number']['options']['price_id'] );
> 
> Unfortunately due to a lack of actions and filters in this function stack, I could find no way to work around this bug and had to patch EDD myself to get our site working properly. I would appreciate an expedient response to this issue that breaks a critical function of our store.
(from #9540)
