### ISSUE TITLE
Increase width of "Number" column in payments table for a more comfortable layout

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9451]
### Expected behavior
This is more of a _tweak_ than an actual bug, but I expect the "actions" of the order table number row to fit nicely into the column/field. At the minute everything is limited by the width.

### Actual behavior

I see this:

<img width="443" alt="Screenshot 2022-09-22 at 02 34 51" src="https://user-images.githubusercontent.com/22668877/191628180-ca1ffaff-b4c0-431e-939b-2698f14fb976.png">

Changing the CSS to this:

```
.wp-list-table.orders th.column-number {
    width: 200px;
}
```

Gives it more breathing space and looks a lot better:

<img width="841" alt="Screenshot 2022-09-22 at 02 37 45" src="https://user-images.githubusercontent.com/22668877/191628287-d3a9d84b-f76d-4c7f-9f0c-8e5985e9c620.png">

**Comment by robincornett** [comment]
I'm inclined to agree with this being an issue, especially with an extension like Invoices being active, and when #9415 is merged in, there will be another link. I think I would vote to just not set a width on this column and let the width manage itself.
