### ISSUE TITLE
Migration ended up with a never disappearing message that it supposedly never completed.

### ISSUE THREAD

**Issue by nextgenthemes** [awesomemotive/easy-digital-downloads#9453]
### Expected behavior
Migration to complete, message to disappear.

### Actual behavior
Stuck with the message.

### Steps to reproduce the behavior
1) I updated lots of things WP to 6.0, EDD to 3.0.4 among other plugins and PHP to 8.1. Do you even support PHP 8.0 and 8.1? I saw this [#](https://github.com/awesomemotive/easy-digital-downloads/issues/9274) and its concerning that you seem not even run unit tests for it.
2) Did the migration with WP-CLI, actually tested this in my staging site, and it went fine, at the end when asked to delete the old data I did so.
3) Did the migration on my production site without actually ever visiting the site after updating everything if that matters. Migration with WP-CLI went fine so it seemed. 
4) But after the migration I got a message that the order data needed to be migrated. But it never gave me any finished message, the process bar went to 100%, and then it got stuck there. Redoing it went much faster, like it already did it, probably did nothing. Again 100% process no finished message.
5) Downgraded PHP from 8.1 to 8.0, and then I could actually finish the order migration and got the finished message finally.
6) Only to now end up with this message 

> Easy Digital Downloads needs to complete a database upgrade that was previously started, click [here](...wp-admin/index.php?page=edd-upgrades&edd-upgrade=recurring_update_order_item_status&step=1&custom=0&steps=0) to resume the upgrade.

When clicking the link I can quickly see the update text appearing, and I get immediately redirected to `index.php?edd_action=recurring_update_order_item_status&step=1&total=0&custom=0`

With the same message showing up again. Again on my sating site that uses pretty much the same setup this did not happen. This seems is bugged now. Because the old data is deleted, and my orders show up, and I already made sales since then I can not restore and old database to retry this.

It seems to be fine, I guess I could just manually tell it that everything went OK to make the message disappear? How would I do that? But you should look into this. Especially because it kind of moved forward with PHP 8.0.

### Information (if a specific version is affected):
PHP Version: 7.4 currently after downgrading out of concern that PHP 8+ causes issues.

EDD Version (or branch): 3.0.4

WordPress Version: 6.0.2

Any other relevant information:

**Comment by mihaijoldis** [comment]
Hey @nextgenthemes 
The upgrade routine you mentioned in the link is an upgrade for the Recurring Payments extension.
It's a small visual bug and will be fixed in the 2.12 release of recurring. You can ignore that message for now as the upgrade was completed correctly.
