### ISSUE TITLE
Tax rates table fixed at 30 rows.

### ISSUE THREAD

**Issue by ToBeOnline** [awesomemotive/easy-digital-downloads#9465]
### Expected behavior
I would like a paginated table at the Tax Rates settings page to be able to edit all my tax rates

### Actual behavior
When I have more than 30 tax rates listed not all the rates are shown in the Tax Rates settings page.

### Steps to reproduce the behavior
1) Go to he Tax Rates settings page.
2) Add more than 30 rates.

### Information (if a specific version is affected):
PHP Version: 8.1.9

EDD Version (or branch): 3.0.4

WordPress Version: 6.0.2

Any other relevant information:

**Comment by robincornett** [comment]
Thank you for the report! We've fixed this as part of #9432 and it will be in the next EDD release.
