### ISSUE TITLE
Dashboard reports wrong currency in recent orders

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9484]
The WP Dashboard widget's recent orders reports the purchased currency in the default currency.
For example, a purchase for $55 USD gets reported as £55. Should be £40.

Expected to show the default, converted amount, OR purchased currency. In this case, $55 or £40.
![widget](https://user-images.githubusercontent.com/30910807/192355794-1e8e5089-362f-4e0d-9c38-42245d6f0d16.png)

Second report on .org forums here https://wordpress.org/support/topic/wrong-currency-shown-in-sales-summary-widget/

From @robincornett 
This is actually an issue in EDD core, in the edd_load_dashboard_sales_widget function. It uses edd_currency_filter() without defining the second parameter, which would be the order currency.

Issue transferred from the Multi-Currency repo.

**Comment by cklosowski** [comment]
![image](https://user-images.githubusercontent.com/1390124/194709560-15ddd326-5068-457f-8cd5-12c7dea71488.png)

**Comment by cklosowski** [comment]
While working on this I identified this bug in Multi Currency: https://github.com/awesomemotive/edd-multi-currency/issues/56
