### ISSUE TITLE
Reconsider the usage of guid in the get_product_data API response.

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9488]
The code we have now and forever https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/api/class-edd-api.php#L1159 uses the guid field in the table.

In some cases that field could be the direct link to a download with no permalinks applied. We should look at using the actual permalink of the product as some users could be using the API to output data in other places.

**Comment by cklosowski** [comment]
@mihaijoldis Was there an issue that was presented here that should encourage us to change?

I believe it was that the domain name changed, and GUIDs don't change when the domain does, correct?

**Comment by mihaijoldis** [comment]
Yes that is correct. The customer in question is pulling the data via the API to output info in some other places and after the domain change the links were still showing a really old one.

**Comment by cklosowski** [comment]
If we change how the `link` is output, it could be considered a breaking change, but I've added a new `permalink` element to the data, which is using the actual permalink.

**Comment by cklosowski** [comment]
We'll need to update this doc with the new element:
https://easydigitaldownloads.com/docs/edd-rest-api-products/

**Comment by cklosowski** [comment]
@mihaijoldis with this merged, we'll need to get a doc update scheduled. I'll add it to the Asana board for you.
