### ISSUE TITLE
Cart Block - When running any AJAX that returns new cart HTML, the cart is showing the blocks based cart, not the shortcode based cart.

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#9491]
### Expected behavior
When using the existing checkout shortcode and I change taxes or add a dicscount code, I expect them to be applied to the cart and the cart contents updated.

### Actual behavior
When using the existing checkout shortcode, and I adjust my country/region with taxes enabled or try and apply a discount, the cart HTML is replaced with the blocks cart HTML

### Steps to reproduce the behavior
1) Enable taxes.
2) Add a product to the cart and use the existing shortcode for checkout.
3) Apply a discount or adjust your address so the trigger for recalculating taxes is run.
4) See your cart get replaced.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 3.1

WordPress Version: All

Any other relevant information:

**Comment by cklosowski** [comment]
We'll have to tackle this issue in the blocks repo, and when finished it will be included in the final build. Will leave this here for tracking purposes and changelogs.

**Comment by cklosowski** [comment]
We'll have to make a change to the recalculate tax AJAX call here as well as there is a case where, if you have both a shortcode checkout and a block checkout (as separate pages) whatever the default is set to in your EDD settings, will be the cart contents that shows. We can fix that by passing in the `current_page` ID into the POST request and it will become fully context aware.

**Comment by flowdee** [comment]
Thanks for the quick fix guys & @cklosowski
