### ISSUE TITLE
edd_is_checkout function does not check for checkout block

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9496]
### Expected behavior

I expect `edd_is_checkout` to return true if the checkout block is on the page.

### Actual behavior

The `edd_is_checkout` function does not check if the block is present, only the short-code which results in it failing.

**Comment by cklosowski** [comment]
@davidsherlock The blocks code does do some of these checks and filters the result of this function, but a change made for a fix on taxes resulted in this not working as expected. We'll get this resolved.

**Comment by davidsherlock** [comment]
Thanks Chris, it actually breaks this function (`edd_get_checkout_uri`) due to the call here:

if ( edd_is_checkout() ) {
		global $post;
		$uri = $post instanceof WP_Post ? get_permalink( $post->ID ) : NULL;
}

// If we are not on a checkout page, determine the URI from the default.
if ( empty( $uri ) ) {
$uri = edd_get_option( 'purchase_page', false );
$uri = isset( $uri ) ? get_permalink( $uri ) : NULL;
}
