### ISSUE TITLE
Product selector does not show "all price options" choices for variable products

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/easy-digital-downloads#9499]
### Expected behavior
I expect to be able to set up bundles in 3.x the same way I did in 2.x.

### Actual behavior
In 2.x, the product selector shows the variable product as a general item (A Music Album) and shows each price ID:

![image](https://user-images.githubusercontent.com/4853066/195134309-626b34ef-bd6c-47b5-ade3-5f9da6ed8d00.png)

In 3.x, only the variations show:

![image](https://user-images.githubusercontent.com/4853066/195134546-891c2afd-1fa5-48ac-93a3-21633db79166.png)

### Steps to reproduce the behavior
1. Create a bundle product and attempt to add a variable product to it.

### Information (if a specific version is affected):
PHP Version: 7.4
EDD Version (or branch): main
WordPress Version: 6.0.2

Any other relevant information:
Related: #7786

**Comment by cklosowski** [comment]
So ideally we can't revert how the dropdown works. If we're bundling a variable priced product, we have to be able to pick the variation as that will drive many decisions made later like:
* License activations possibly
* access to specific files.

While this was a change, it was the right change as a variable based product can have many decisions made based off price ID and not adding the price I can limit what we show/hide/provide later.

I think the main issue is that this product HAD the main product assigned to the bundle, before the shift to not include it.

**Comment by robincornett** [comment]
License activations stem from the parent license. I think your point about different file options is valid, but that was supported in EDD 2.x because the user could select either the product in its entirety, or select a single price option. Yes, if different files are attached to different price IDs, it is necessary to select the price ID, but we made that available before and still do.

For users who selected an entire variable product, I'm concerned that this is a breaking change, and I can see valid reasons for selecting the entire product over a variation.

**Comment by cklosowski** [comment]
My question then @robincornett, is what happens if you pick the 'entire product', but that product has variable prices, and no files attached to 'all', they are all defined as part of a variable price? Do you get none of the files, all of the files?

**Comment by robincornett** [comment]
I'm thinking that in that scenario, no files would be included as none met the criteria, but that would be a correct way to handle the situation and I would not consider it a failure.

I'm not sure why one would want to include a variation with no files in a bundle, but if the child product is set up that way and the store owner selects the entire product, that's a configuration issue.

A scenario that I feel like is more likely, and which 2.x supported and this would bring back, is:
- I create Product A with three variations, but the variations are related to licensing/activations, not the files, so there is only one file, and other than licensing, the variations are identical.
- I create Bundle B with three variations and want to include Product A in it. How do I choose which variation of Product A to include? The only difference between the variations is the licensing/activations and Bundle B is handling that.
- I don't want the order confirmation/receipt to show a variation for Product A; I just want it to show that Product A is included in the bundle. To my mind, this is a likely standard scenario and a reason why we would want to allow users to continue to select the product in its entirety, rather than a variation.

**Comment by WildeWebMarketing** [comment]
How does this work now when the bundle itself has variations? I used to be able to select the non-variation version of the downloads and, from the looks of it, the correct licensing for those files was selected based on the bundle's licensing. Now we're forced to choose one of the licensing options for the bundled files, but what happens if the customer buys the bundle with the other licensing option?
