### ISSUE TITLE
"Last quarter" showing wrong dates in the reporting

### ISSUE THREAD

**Issue by zkawesome** [awesomemotive/easy-digital-downloads#9502]
### Expected behavior
If I select the `Last Quarter` period in the reports, I should be getting the correct quarter dates.

### Actual behavior
It should show July 1 to September 30, but instead I am getting:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/108748561/195153997-47735fb5-2448-41cd-9115-92c716404c63.png">

**Comment by cklosowski** [comment]
As a note, I believe this is limited to timezones in the + direction of GMT. I cannot replicate it on anything that UTC+0 or negative values.
