### ISSUE TITLE
Wrong Variation Showing Up in Orders and Customer Dashboard After Purchase

### ISSUE THREAD

**Issue by WildeWebMarketing** [awesomemotive/easy-digital-downloads#9516]
## Bug Report

Customer bought Variation #2, but the backend order and frontend customer dashboard is showing Variation #1. Correct price is showing for Variation #2.

Why would this occur and is there any way to fix these without having to refund the order? I used to be able to edit the order after the fact, but now it seems like that functionality was removed, for whatever reason.

**Comment by cklosowski** [comment]
@WildeWebMarketing Depending on what version of EDD you migrated to, we had a bug in migrating orders with Price IDs where the index and the price ID didn't match, or a price ID had been removed in the past.

We crated this tool to help mitigate the issue: https://a.supportally.com/f/nAS4g0

With this plugin enabled, when viewing an order in the admin, there is a new Modify Order Items section in the Order Details area that will allow you to assign the correct Price ID to an order item.
