### ISSUE TITLE
Backwards compatibility for "_edd_payment_total" payment meta

### ISSUE THREAD

**Issue by scarabcoder** [awesomemotive/easy-digital-downloads#9518]
### Expected behavior
When attempting to retrieve a payment total using Payment::get_meta("_edd_payment_total"), it no longer returns the payment value (it now returns null/false). It appears that the payment total meta does not have backwards compatibility, and I am unable to find the new method for retrieving a payment total from EDD. 

EDD Version (or branch): 3.1.0.1

WordPress Version: 6.0.3

**Comment by robincornett** [comment]
In EDD 3.0, the orders are stored in custom tables so the total is no longer metadata. [Some examples of the changes are in a development blog post](https://easydigitaldownloads.com/development/2021/02/16/edd-3-0-beta1/#payments-changes).

You can use `edd_get_payment` to get the `EDD_Payment` object, which will look similar to how the same function has worked in EDD 2.x, or you can use `edd_get_order` to get the order object directly. So getting the total can look like this:

```php
$payment = edd_get_payment( $payment_id );
$total   = $payment->total;
```

Or:

```php
$order = edd_get_order( $payment_id );
$total = $order->total;
```

If you need support, feel free to [reach out to our support team](https://easydigitaldownloads.com/support/).
