### ISSUE TITLE
Editing a bundled product takes 15-30 seconds to open product editor

### ISSUE THREAD

**Issue by WildeWebMarketing** [awesomemotive/easy-digital-downloads#9522]
## Bug Report
When I click to edit a product bundle, it takes between 15-30 seconds to load the editing page, some even timing out, whereas I need to click edit again and hope it opens.

To rule out conflicts. I tested multiple times to compare on two different servers.  I disabled every single plugin except EDD and the problem persists. I then created a new bundle product only containing a single product and the result was the same. Funny thing is, all the regular products load just fine as expected. Nothing new has been added to these sites, besides updates.

Testing In a new installation, bundled products load as expected. This seems to happen with sites created before version 3.0.

Also, I'm not on shared hosting, the servers are DigitalOcean and Vultr servers and everything else besides the bundles is still fast. I also increased my droplet resources to see if there was a difference and there was not. Identical, long loading time.

**Comment by WildeWebMarketing** [comment]
UPDATE: I went through and downgraded Easy Digital Downloads to every previous version and it started working correctly again with version 2.11.7.

**Comment by mihaijoldis** [comment]
Hey @WildeWebMarketing 

If you are comfortable with making code changes could you try and apply the changes in PR https://github.com/awesomemotive/easy-digital-downloads/pull/9527/files and see if that helps?

**Comment by WildeWebMarketing** [comment]
@mihaijoldis is there a way to just download the finished files and drop them in? If not, as long as this is going to be fixed moving forward, I will just try to avoid editing my bundles until then.

**Comment by cklosowski** [comment]
@WildeWebMarketing This is slated to go into 3.1.0.2, which should be released this week.

**Comment by WildeWebMarketing** [comment]
@cklosowski Thank you! You guys are awesome!
