### ISSUE TITLE
Limit of 10 discounts when running edd_has_active_discounts can produce inaccurate display of discount field at checkout.

### ISSUE THREAD

**Issue by DannyCooper** [awesomemotive/easy-digital-downloads#9526]
## Bug Report
In [includes/discount-functions.php:395](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/discount-functions.php#L379) the code loops through the 10 most recent discount codes to decide whether the discount form should be shown on the checkout page. The problem is that if the most recent 10 discount codes have all expired, it won't look for any more and won't show the discount code field.

https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/class-edd-discount.php#L1648

### Steps to reproduce the behavior
1) Create a working discount code
2) Create 10 more discount codes, with expiry dates in the past
3) Visit the checkout page

### Any other relevant information:

This could be solved in numerous ways. For example, increasing the sample size from 10, or excluding expired codes from the initial query.

**Comment by cklosowski** [comment]
In reality all we need to do here is see if there is a single discount code that is able to be used (not specifically with the cart contents) but in general.

**Comment by cklosowski** [comment]
At this time we're limited in the query available, so I've taken the approach of using a 5 minute transient (that is filterable). By default the function will still only check 10 discount codes, however any time one of the following actions is taken, the sample size will be pushed to 50, and the transient will be refreshed:
* Admin adds a discount
* Admin edits a discount
* Admin deletes a discount
* Admin deactivates a discount
* Admin activates a discount
* After Payment Actions are processed (this runs in Cron, not in the user space, so the limit of 50 should not have an impact on the checkout process)

**Comment by cklosowski** [comment]
I'm going to punt this, we still have some things to work out and we need to get 3.1.0.3 out sooner than this can be validated and tested. It'll go in the next release.

**Comment by cklosowski** [comment]
We took a pretty deep approach to this, but we've fixed this in EDD 3.2.0 by rewriting the query from the ground up.
