### ISSUE TITLE
Undefined notice when using discount with multiple variable items in the cart

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/easy-digital-downloads#9540]
### Expected behavior
Adding a discount code to a cart with variable items to not show a notice

### Actual behavior
It does show a notice

### Steps to reproduce the behavior
1) Create a fixed amount discount code and add a few items to your cart which are variable priced.
2) apply the discount code

```
[28-Oct-2022 19:20:19 UTC] PHP Warning:  Undefined array key "options" in D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\discount-functions.php on line 1125
[28-Oct-2022 19:20:19 UTC] PHP Warning:  Trying to access array offset on value of type null in D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\discount-functions.php on line 1125
```

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
Issue reported https://secure.helpscout.net/conversation/2051676194/2255319?folderId=5747299

From the Barn2 team:

The reason this fails is due to the `edd_get_cart_discounts_html` function, used in the checkout_cart.php template. `edd_get_cart_discounts_html` calls "EDD()->cart->get_contents_details()" to retrieve the cart and pass it into `edd_get_item_discount_amount`, but this function does not include an 'options' index on cart items. `edd_get_item_discount_amount` accounts for this scenario with the `$item` parameter, but not $items.

The solution is very simple, change line 1125 of discount-functions.php to something like,

```
$i_amount = edd_get_price_option_amount( $i['id'], $i['options']['price_id'] ?? $i['item_number']['options']['price_id'] );
```

Unfortunately due to a lack of actions and filters in this function stack, I could find no way to work around this bug and had to patch EDD myself to get our site working properly. I would appreciate an expedient response to this issue that breaks a critical function of our store.

**Comment by robincornett** [comment]
I'm going to copy the issue content to #9443 and close this as a duplicate.
