### ISSUE TITLE
Switching gateways when resuming a payment, assigns incorrect value to gateway column.

### ISSUE THREAD

**Issue by cklosowski** [awesomemotive/easy-digital-downloads#9541]
### Expected behavior
When a user resumes an abandoned order, but changes the gateway from the original one selected, it should reflect that in the order details.

### Actual behavior
When a user resumes an abandoned order, but changes the gateway from the original one selected, the original gateway value is still stored as the 'gateway' for the order.

### Steps to reproduce the behavior
1) Have PayPal and another gateway enabled.
2) At checkout, start the purchase process but click the 'cancel and return' link.
3) Go to your order history, click the link to 'complete this order'.
4) Choose a different gateway than you originally tried completing the order with.
5) on your purchase confirmation, see that the gateway is that of the original order attempt

### Information:
PHP Version: All

EDD Version (or branch): 3.0+

WordPress Version: All

Any other relevant information:
While the data is all correct related to the transaction, this does pose a problem for reporting as well as clicking links to the transition from the order details in the admin, as that is built off the gateway column.

**Comment by robincornett** [comment]
Payment recovery uses the `edd_insert_payment` function. In EDD 2.x, that function merges the existing payment data with the checkout parameters and updates the payment object accordingly.

In EDD 3.x, that function passes the data over to `edd_build_order`, which handles the existing payment slightly differently. The payment is retrieved and saved with some updated information (date, download and customer handling), but then everything switches over to handling the order. The function uses `edd_add_order` if this is a new purchase, but it does not use `edd_update_order` to update an existing order, and I think that is not correct. I think it's possible that any order data which is set in the `$order_args` array (which may be different from what was saved to the payment object) could be lost, including a change of customer, currency, IP, etc.
