### ISSUE TITLE
EDD Confirmation block: Your purchase session could not be retrieved

### ISSUE THREAD

**Issue by dashkevych** [awesomemotive/easy-digital-downloads#9599]
## Bug Report

I have a Purchase Confirmation page. Initially, it uses a shortcode to "View Details and Downloads": `[edd_receipt]`.

It works as expected. 

When clicking on "View Details and Downloads" link from EDD Order History block, it redirects to the page with information about the purchase.

However, when I replace shortcode with EDD Confirmation block, the page displays: "Your purchase session could not be retrieved."

I expect that EDD Order History block would show the same output as `[edd_receipt]` shrortcode.

### Steps to reproduce the behavior
1) Create page.
2) Add EDD Confirmation block.
3) Save page.
4) Create another page with EDD Order History block.
5) Publish a page and open it.
6) Click View Details and Downloads.

### Information (if a specific version is affected):
PHP Version: 7.4.1

EDD Version (or branch): 3.1.0.3

WordPress Version: 6.1.1

Any other relevant information:
Testing on local environment, using [Local](https://localwp.com/)

**Comment by robincornett** [comment]
The confirmation block is a new block and is not intended as a 1:1 replacement for the `[edd_receipt]` shortcode. In EDD 3.1, with blocks being introduced, there are now two possible pages/blocks to use for showing order data:
1. The Confirmation page is a new page and is optional and should be used with the **EDD Confirmation** block. It relies on the current purchasing session to show data. It is only displayed upon successfully completing an order and may not show all of the same content as the receipt block.
2. The Receipt page should be used with the **EDD Receipt** block. It will show full order information and does not rely on the current purchase session.

Not everyone will have a use case for the confirmation page/block, but we do have users who like to have different information/scripts on the confirmation screen than a receipt, so this makes that much easier for them.

An [overview of all our blocks](https://easydigitaldownloads.com/docs/easy-digital-downloads-blocks/) is available on our site.
