### ISSUE TITLE
"Download Categories" / "Download Tags" blocks do not work.

### ISSUE THREAD

**Issue by leewillis77** [awesomemotive/easy-digital-downloads#9616]
### Expected behavior
I set up a new site running the latest version of EDD. I created a page, and added the "Download Categories" block, and I expected it to show a list of the categories I have on my site in some form, however, on the public page it shows nothing (no HTML output for the block at all), and when editing the post it just shows "No categories". 

The Download Tags block has the same issue. 

### Actual behavior
When I add the "Download categories", or "Download tags" blocks I expect them to output a list of categories/tags.

### Steps to reproduce the behavior
1) Install EDD
2) Go to Downloads » Categories and create some categories
3) Go to Downloads » Tags and create some categories
4) Go to Downloads and create a download, assigning it to the categories and tags you've created (in case "empty" terms are hidden)
5) Create a page, and insert the "Download categories" block, and the "Download tags" block.

### Information (if a specific version is affected):
PHP Version: 8.0.27
EDD Version (or branch): 3.1.0.5
WordPress Version: 6.1.1

Any other relevant information:
Screenshot showing categories created in the store:
![Screenshot 2023-01-31 at 13 11 20](https://user-images.githubusercontent.com/1097338/215768996-f3d8e3b1-2b08-4956-9835-427cfc2eb429.png)

Screenshot of editing the page:
![Screenshot 2023-01-31 at 13 12 12](https://user-images.githubusercontent.com/1097338/215769139-8e8c6235-93ee-485b-b18f-3af4e0e323a3.png)

Screenshot of the rendered page:
![Screenshot 2023-01-31 at 13 13 00](https://user-images.githubusercontent.com/1097338/215769362-1fe1fefb-920f-4aa0-8743-50af6dc8db42.png)

**Comment by robincornett** [comment]
HI @leewillis77! Those are core WordPress blocks, not registered by EDD. Can you try the "EDD Download Terms" block instead, which is one of our blocks? The controls should look like this:

![image](https://user-images.githubusercontent.com/4853066/215797727-5a72ea70-ad92-4eaa-b18f-37b6df78ad90.png)

The [EDD blocks](https://wordpress.org/plugins/easy-digital-downloads/#blocks-header) are all registered with EDD as part of the name.

**Comment by leewillis77** [comment]
Ah, great. So, those work, so I guess this bug report should be "Categories and Tags are registered with WordPress in such a way as to create broken core blocks"?

**Comment by leewillis77** [comment]
PS. Thanks for the quick reply :)

**Comment by leewillis77** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/45553
