### ISSUE TITLE
If the license status is renewal then the "Upgrade paths" is not showing on the license details page.

### ISSUE THREAD

**Issue by Rajat1192** [awesomemotive/easy-digital-downloads#9620]
EDD Version (or branch): 3.1.0.5
Wordpress 6.1.1
PHP 7.4

I have fixed the bug myself. you can see the below my code.

**function edd_get_deliverable_order_item_statuses() {
	      $deliverable_order_item_statuses = array( 'complete', 'edd_subscription', 'partially_refunded' );
	      return (array) apply_filters( 'edd_deliverable_order_item_statuses', $deliverable_order_item_statuses );
}**

**Comment by robincornett** [comment]
Thank you for the report, @Rajat1192. This is an issue we are resolving in our Recurring Payments extension in version 2.11.9. In the meantime, instead of editing the EDD files directly, you can use the filter to make sure that order items marked as `edd_subscription` are considered deliverable:

```php
add_filter( 'edd_deliverable_order_item_statuses', 'prefix_add_subscriptions_deliverable_order_item_statuses' );
/**
 * Defines edd_subscription as a deliverable order item status.
 * Order items should not have this status, so this is really a fallback filter in case something went sideways.
 */
function prefix_add_subscriptions_deliverable_order_item_statuses( $statuses ) {
	$statuses[] = 'edd_subscription';
	
	return $statuses;
}
```

**Comment by Rajat1192** [comment]
Hello @robincornett , 

Thank you so much for your quick reply, I will use this filter. again thank you for your advice.
