### ISSUE TITLE
changing a category assigns random categories

### ISSUE THREAD

**Issue by matt70** [awesomemotive/easy-digital-downloads#9627]
### Expected behavior
When I'm trying to change a category of a download file, I select the new category and deselect the old category.
After this the download should be assigned to one category.

### Actual behavior
When I save my category selection my new category is saved, BUT there are random assigned some more (3-4) random categories???
Even deslecting these random categories and save the entry again, does not work.

### Steps to reproduce the behavior
1) Change a category
2) Save the entry
3) Check the assigned categories

**My workaround at the moment:**
I can change or deselect the random categories with quickedit...

**Comment by mihaijoldis** [comment]
Closing as the issue was tracked down via support ticket. We determined that this behavior is not a bug, but is a feature provided by the Mayosis Core plugin
