### ISSUE TITLE
Pro Upgrade Tooltip

### ISSUE THREAD

**Issue by flowdee** [awesomemotive/easy-digital-downloads#9629]
<img width="549" alt="Bildschirm­foto 2023-03-15 um 15 57 38" src="https://user-images.githubusercontent.com/2278756/225349841-9565d4c9-a323-4344-aa20-71a740de9dea.png">

### Typo
I assume `You're Pro Upgrde is waiting!` should be `Your Pro Upgrade is waiting!`

**Comment by robincornett** [comment]
@flowdee thank you for reporting! We have this on our list and it will be fixed in the next release.
