### ISSUE TITLE
Stripe Payment issue

### ISSUE THREAD

**Issue by jatindv** [awesomemotive/easy-digital-downloads#9632]
### Expected behavior
Be able to complete the payment process.

### Actual behavior
When I select `Downloads -> Payments -> Stripe -> Elements Mode -> Card Element`
It's throwing below error:
**Screenshot link ::** https://www.screenpresso.com/=VBxUe

When I select `Downloads -> Payments -> Stripe -> Elements Mode -> Payment Element`
**Screenshot link ::** https://www.screenpresso.com/=mTH1b

### Steps to reproduce the behavior

Goto `Downloads -> Payments -> Stripe -> Elements Mode` select any element and do checkout process.

### Information (if a specific version is affected):
PHP Version:
7.4

EDD Version (or branch):
3.1.1.3

WordPress Version:: 
6.2

Any other relevant information:
NO

**Comment by robincornett** [comment]
@jatindv can you reach out to our [support team](https://easydigitaldownloads.com/support/) for help with this issue please, and confirm that you've included the [fields required by Stripe](https://stripe.com/docs/india-accept-international-payments)? Including your system info file will help expedite your support request.

**Comment by rosinghal** [comment]
@robincornett For the `Payment Element` I think the `name` field is not being sent with API requests.

**Comment by jatindv** [comment]
@robincornett 

Thanks for you suggestions. I have raised the support ticket. With the help of the support team we have tested the pre release version and it's working fine.
