### ISSUE TITLE
Allow additional data to be stored with fees in the database

### ISSUE THREAD

**Issue by davidsherlock** [awesomemotive/easy-digital-downloads#9641]
### Explain your enhancement (please be detailed)

Currently, when a fee is added with additional arguments (data) using the `EDD()->fees->add_fee()` function, it is not saved to the database when the order is "built". The issue lies in the code that stores order item fees as adjustments. This should store anything additional as meta data, like the order items and the like.

Here is an example of additional data not saved:

```
EDD()->fees->add_fee( array(
  'id'            => $points_type . '_fee',
  'label'         => sprintf( __( 'Pay with %s (%s)', 'edd' ), $points_type, edd_currency_filter( edd_format_amount( $points_fee ) ) ),
  'amount'        => $points_fee,
  'no_tax'        => true,
  'type'          => 'fee',
  'download_id'   => 0,
  'price_id'      => NULL,
  'points_type'   => $points_type,
  'points'        => $points_used,
  'money'         => edd_format_amount( $points_value ), // Pass the points value as the money parameter
) );
```

The points_type, points and money are not saved. I believe they were saved in 2.9x EDD, but I would need to confirm that.
	         
### Justification or use case

Easier third-party development.

**Comment by cklosowski** [comment]
Thanks @davidsherlock, this was fixed in EDD 3.2.0.
