### ISSUE TITLE
post__not_in argument for EDD_Payments_Query not working

### ISSUE THREAD

**Issue by webzunft** [awesomemotive/easy-digital-downloads#9643]
I was trying to query payments and excluding one using the `post__not_in` argument in edd_get_payments(). It didn’t work, so I looked into `EDD_Payments_Query` and noticed that `post__not_in` is handled like `post__in`.

https://github.com/awesomemotive/easy-digital-downloads/blob/8f2c1301134a382e9f00dda56155a6ea773256c5/includes/payments/class-payments-query.php#L694-L700

**Comment by robincornett** [comment]
Thank you @webzunft-- we do have this logged as a bug and will fix it. However, we do recommend, if you can, moving to use `edd_get_orders` instead of `edd_get_payments`, and set the `id__not_in` parameter as you need. It will be more performant because of not having to account for backwards compatibility with old payment objects.

**Comment by webzunft** [comment]
Thanks, @robincornett. I found this being used in EDD_Recurring and there was no comment about a better alternative in the code. I will look into the alternatives now.

**Comment by robincornett** [comment]
Yes, once Recurring does not have to support older versions of EDD, it will be updated to use `edd_get_orders` over `edd_get_payments`.

**Comment by webzunft** [comment]
Thanks. I gave `edd_get_orders` a try, but it somehow gives me cached values. Is that possible? Any trick on how to get uncached results?

**Comment by robincornett** [comment]
Can you share a sample of the code you're using to query? You should be able to add a parameter to `edd_get_orders` to `'update_item_cache' => true,` to ensure you are not getting cached values, but that should be set to `true` by default, except when doing a count.

The unexpected thing here is that `edd_get_payments` calls up the `EDD_Payments_Query` class, which uses `edd_get_orders` to get the list of orders, so using the latter is really just taking a shortcut to get directly to that function.

**Comment by robincornett** [comment]
Oh, yep, that makes sense--thanks for letting me know! You may also want to explicitly set the `type` in the query to `sale`, depending on your usage, to ensure that refunds are not included, as they are in the same database table.

**Comment by robincornett** [comment]
This has been fixed in the 3.1.2 release.
