### ISSUE TITLE
Increase number of returned tax rates

### ISSUE THREAD

**Issue by webzunft** [awesomemotive/easy-digital-downloads#9648]
I just ran into an issue with some custom code that came back to `edd_get_tax_rates()` being limited to 30 tax rates by default. This is neither expected from the function's name nor documented.

https://github.com/awesomemotive/easy-digital-downloads/blame/8f2c1301134a382e9f00dda56155a6ea773256c5/includes/tax-functions.php#L57

I found the same function used in third-party plugin’s code so I am not the only one who ever ran into this problem. Maybe, you could increase the limit by default?

Thanks

**Comment by cklosowski** [comment]
This was fixed in the EDD 3.1.3 release.
