### ISSUE TITLE
EDD interfering with admin CSS of core Media & Text block

### ISSUE THREAD

**Issue by smerriman** [awesomemotive/easy-digital-downloads#9657]
### Expected behavior

The EDD plugin should not alter the styling of the Media & Text block.

### Actual behavior

The EDD plugin changes the display of the Media & Text block.

It appears this is due to the EDD stylesheet changing some CSS values on the generic .components-placeholder div, which is used by other parts of the admin.

### Steps to reproduce the behavior
1) Without EDD activated, insert a Media & Text block to a page. You'll see it displaying normally, with the words 'Media area' on the left, , and Upload + Media Library buttons on the left.
2) Activate EDD. You'll now see those items centered and looking odd.

### Information (if a specific version is affected):
EDD Version (or branch): 3.1.3

WordPress Version: 6.2.2

**Comment by cklosowski** [comment]
@robincornett let's take a look at this and confirm. If we can replicate let's get this on our board to see if we can fix.

**Comment by cklosowski** [comment]
Thanks for the report @smerriman This was fixed in EDD 3.2.0
