### ISSUE TITLE
PHP Fatal ERROR: Uncaught ArgumentCountError: 3 arguments are required  1 given in easy-digital-downloads-pro/includes/admin/tools.php:844 

### ISSUE THREAD

**Issue by sultann** [awesomemotive/easy-digital-downloads#9663]
### Expected behavior
When I go to the admin tools page, it should render it without error.

### Actual behavior
When I go to the admin tools page, it shows an error.
PHP Fatal ERROR: Uncaught ArgumentCountError: 3 arguments are required  1 given in easy-digital-downloads-pro/includes/admin/tools.php:844 

### Steps to reproduce the behavior
1) log in to the admin end
2) Navigate to tools -> Import/Export
3)
etc., etc

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.1.5

WordPress Version: 6.2.2

**Comment by cklosowski** [comment]
Thank you for the report @sultann This has been resolved in EDD 3.2.0.
