### ISSUE TITLE
Product Type Options selector breaks metaboxes

### ISSUE THREAD

**Issue by arraypress** [awesomemotive/easy-digital-downloads#9671]
### Expected behavior
When I change the product type to "Bundle" or "Service" I expect to be able to go back and see the bundle or file metaboxes.

### Actual behavior
Due a JS issue, when you switch back to the other types are being on "service" the bundles (nor file) metaboxes reappear.

### Steps to reproduce the behavior
1) Add a new product.
2) Change to "Service" for product type. 
3) Change back to "Bundle" or "Single Product"
4) The metaboxes do not reappear.

### Information (if a specific version is affected):
PHP Version: 8.0.2

EDD Version (or branch): 3.2.0

WordPress Version: 6.3.1

Any other relevant information:

**Comment by davidsherlock** [comment]
On a related note, the descriptive text under the select should (ideally) change and explain what each product type is. Alternatively this might look better as a tooltip as it feels a bit crowded at the minute.
