### ISSUE TITLE
Trying to get `EDD_Download`'s type with property instead of using `get_type()`

### ISSUE THREAD

**Issue by goncalovf** [awesomemotive/easy-digital-downloads#9686]
## Bug Report
`EDD_Download`'s `$type` property is not set when the class is instantiated. The `$type` property is only set when `EDD_Download->get_type()` is first called. So, we need to make sure that we always try to retrieve the download's type by using the appropriate method, instead of trying `EDD_Download->type` directly. The issue is that this is not done in `edd_get_download_type()` ([see here](https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/download-functions.php#L625))

### Information (if a specific version is affected):
EDD Version (or branch): 3.2.3

WordPress Version:

Any other relevant information:
Happens in the Pro plugin as well.

**Comment by cklosowski** [comment]
@goncalovf The `EDD_Download` class sets the property of `type` to private, and we have a magic getter method `__get()`. So while the value is not set while instantiating it, it is retrieved and set when using `$download->type` as a private property will run through the `__get` method, which then looks up the type via a `get_meta` call.

**Comment by goncalovf** [comment]
@cklosowski You're absolutely right, thank you for pointing that out. I must have found an issue on my end and wrongly attributed to how `edd_get_download_type()` got the type, I'm sorry. I'm going ahead and closing this issue.
