### ISSUE TITLE
EDD Amazon S3 Errors on PHP 8.1+

### ISSUE THREAD

**Issue by WildeWebMarketing** [awesomemotive/easy-digital-downloads#9697]
EDD Amazon S3 throws loads of errors on PHP 8.1+

Looks like it's related to the included Amazon SDK. It's been updated, but not in the EDD Amazon S3 plugin.

**Comment by robincornett** [comment]
Thank you for the report! We are actively working on a release for our S3 extension. The release will include an update for the SDK.

**Comment by robincornett** [comment]
Version 2.4.0 of our Amazon S3 extension updated the SDK.
