### ISSUE TITLE
Misleading Site Health Information

### ISSUE THREAD

**Issue by sanzeeb3** [awesomemotive/easy-digital-downloads#9703]
## Bug Report

In the Site Health test, if at least one gateway is enabled, the labels and description for the passed and failed test are the same causing information to mislead.

### Expected behavior
The label & description for the passed vs failed tests should be different.

### Actual behavior
There's critical issue and description saying:

`Fantastic! You have enabled a gateway and can accept orders.`

### Steps to reproduce the behavior
1) Go to Tools > Site Health.
2) Make sure you have no gateways enabled. 
3) See "Critical" issue label and description.

### Information (if a specific version is affected):
PHP Version: 8.1

EDD Version (or branch): latest

WordPress Version: 6.4

Any other relevant information:
![screenshot-2](https://github.com/awesomemotive/easy-digital-downloads/assets/16817248/4d77ae42-02a7-4a03-a7fe-29611c5e880b)

**Comment by robincornett** [comment]
@sanzeeb3 thank you for the report and the proposed fix! I've added this to our roadmap.

**Comment by mihaijoldis** [comment]
This should be fixed as of version 3.2.7
