### ISSUE TITLE
EDD_SL_Plugin_Updater not working properly

### ISSUE THREAD

**Issue by bilal-ahmed-wpb** [awesomemotive/easy-digital-downloads#9713]
Whenever there is an update for the plugin, there is an update notification but the update now button disappears and following appears **update not available**

I am using EDD_SL_Plugin_Updater.php file.

The update now button reappears as I delete all the transients of the site specifically update_plugins

How to fix the issue?

**Comment by cklosowski** [comment]
Github is for development tracking only of Easy Digital Downloads Core. For issues related to our Software Licensing extension and integrating it with your Plugin, please contact our support team here:
https://easydigitaldownloads.com/support
