### ISSUE TITLE
Creation of dynamic property EDD_Auto_Register::$basename is deprecated

### ISSUE THREAD

**Issue by henrywright** [awesomemotive/easy-digital-downloads#9719]
I just installed the EDD Auto Register plugin and got this PHP notice:

> Deprecated: Creation of dynamic property EDD_Auto_Register::$basename is deprecated in wp-content/plugins/edd-auto-register/edd-auto-register.php on line 127

**Comment by henrywright** [comment]
Some notes and suggestions:

- The notice is related to PHP >= 8.2
- The notice can be fixed by making the class opt in. For this use the `#[\AllowDynamicProperties]` attribute. Note this is only supported in newer PHP
- If old PHP needs to be supported, declare the property in the class

**Comment by slaFFik** [comment]
Isn't this issue duplicates #9712?

**Comment by henrywright** [comment]
Hey @slaFFik yes it does seem to be. My apologies
