### ISSUE TITLE
`resource_missing` check isn't firing

### ISSUE THREAD

**Issue by tomusborne** [awesomemotive/easy-digital-downloads#9720]
## Bug Report

This line is not working as expected: https://github.com/awesomemotive/easy-digital-downloads/blob/main/includes/gateways/stripe/includes/card-actions.php#L490

If a customer cannot be found (Stripe API has changed, for example), the user gets a "No customer found" error in the checkout.

The code above should catch this issue and attempt to create a new customer for the user.

However, the type in the `catch` is incorrect, so the code never fires.

### Expected behavior
If no customer exists, a new one should be created.

### Actual behavior
The user is faced with a "No customer found" error and cannot checkout.

### Steps to reproduce the behavior
1) Purchase something with a new user.
2) Delete the customer in Stripe.
3) Try to purchase something with the same user.

**Comment by robincornett** [comment]
Thank you for the report, @tomusborne--we've confirmed and are logging this for a fix.

**Comment by tomusborne** [comment]
Thanks, @robincornett! Any chance of an update when a fix is intended to make it into a release? I'm going to have to patch my EDD version for now, so would be great to know when I'm safe to update/not re-add the patch.

**Comment by robincornett** [comment]
I don't know a date, I'm sorry, but this is a priority bug for us to fix, so I've slated it for our next release.

**Comment by tomusborne** [comment]
No worries, that's all I needed to know. Thanks!

**Comment by tomusborne** [comment]
Just confirming that this wasn't patched in 3.2.12.

Happy to make a PR if needed.

**Comment by mihaijoldis** [comment]
Wrong click. This will be resolved in the 3.3.0 release of EDD.
