### ISSUE TITLE
Order "Number" is different to "id"

### ISSUE THREAD

**Issue by henrywright** [awesomemotive/easy-digital-downloads#9723]
![order](https://github.com/awesomemotive/easy-digital-downloads/assets/1963288/73f386f7-cc0d-4a54-b642-aa7dbdbd123e)

The screen grab above was taken from the Downloads > Orders list table in the wp-admin area.

As you can see the order "Number" 4 is different to the "id" of 11.

Is this expected? It feels like a bug because both 4 and 11 refer to the same order.

**Comment by henrywright** [comment]
I noticed this because in the list table I have duplicate "Numbers". For example, 4 appears twice. See the screen grab below.

![numbers](https://github.com/awesomemotive/easy-digital-downloads/assets/1963288/8dadeea5-5378-4c9f-abb1-fcbdfe83cc72)

**Comment by mihaijoldis** [comment]
It is possible that you enabled Sequential Order numbers and set a custom start number of 1. That is why after the ID 7 in your screenshot it starts again from 1. You can check if you have that enabled under Downloads > Settings > Payments > Accounting.

**Comment by henrywright** [comment]
Thank you @mihaijoldis for explaining. I do indeed have Sequential Numbering enabled. My guess is I enabled it recently which may be why the numbers have restarted from 1.

I will close this issue because it clearly isn't a bug
