### ISSUE TITLE
Customers can no longer purchase subscription and non-subscription downloads at the same time

### ISSUE THREAD

**Issue by paulminors** [awesomemotive/easy-digital-downloads#9748]
I've been an EDD customer for the last 9 years and I sell subscription and non-subscription products. Until recently, customers have been able to purchase both types of products simultaneously. 

The other day, a customer informed us they could not purchase a sub and non-sub product and the checkout error says:
"Subscriptions and non-subscriptions may not be purchased at the same time. Please purchase each separately".

I opened a ticket with EDD support and Amir informed me that:
_"I'd like to clarify that this is not a bug, but an added feature designed to enhance the management of subscription and non-subscription products. While it was possible to purchase both types of products together in the past, this change has been implemented to streamline the process and improve the overall experience with Easy Digital Downloads (EDD)."_

Can you please explain to me how taking AWAY functionality and making it harder for customers to pay for products is “improving the overall experience”? This is without a doubt going to result in lower sales for us. Surely it would be better to make this a setting that can be turned on/off.

**Comment by robincornett** [comment]
The change in this behavior is due in part to how Stripe handles subscriptions vs. one time products, but it is possible to override this limitation with a filter:

```php
add_filter( 'edd_gateway_supports', 'prefix_maybe_add_mixed_cart_support', 999, 2 );
/**
 * Allow Stripe Payment Elements to support mixed carts.
 */
function prefix_maybe_add_mixed_cart_support( $supports, $gateway ) {
	if ( 'stripe' === $gateway ) {
		$supports[] = 'mixed_cart';
	}

	return $supports;
}
```

The Stripe gateway is the only one which has historically supported mixed carts, and the legacy Card Elements still does, but this filter should allow the new Payment Elements integration to support mixed carts. It does require a minimum version of EDD 3.2.7. Please note that mixed cart support for Payment Elements is not formally supported by our team, so I would test this on a staging site, but it should allow your store to sell a subscription with a non-subscription product again.

**Comment by paulminors** [comment]
Thanks for the fast response @robincornett. Would you or someone on your team be able to add this filter to the correct place on my website as I don't have the expertise to do this?

**Comment by robincornett** [comment]
@paulminors please [contact our support team](https://easydigitaldownloads.com/support/) and they can help you set that up.

**Comment by paulminors** [comment]
Will do. Thanks @robincornett
