### ISSUE TITLE
Software Licensing renewal reminders not being sent

### ISSUE THREAD

**Issue by tomusborne** [awesomemotive/easy-digital-downloads#9750]
Originally reported here: https://wordpress.org/support/topic/software-licensing-emails-are-broken/

Thought I should mention it here as well.

Since the latest EDD and EDD Software Licensing updates, renewal emails are not being sent out.

From what I can see, this is due to two separate bugs.

In the `edd_sl_scheduled_reminders` function, you have this condition:

```
if (edd_software_licensing()->notices->is_enabled($notice) ) {
    continue;
}
```

I believe the condition is wrong. Shouldn’t you only continue if the notice is NOT enabled?

Second, this function is not always working for me:

`$send_period = edd_software_licensing()->notices->get_notice_period($notice);`

The `period` is empty.

I temporarily fixed this using the following:

`$send_period = edd_get_email_meta($notice->id, 'period', true);`

This is a pretty major bug. Users haven’t been receiving renewal reminders since we updated EDD Software Licensing a week ago.

**Comment by mihaijoldis** [comment]
This will be fixed in the next Software Licensing release. We posted a change fix on the WordPress.org topic.
Will mark this as closed for now.
