### ISSUE TITLE
Paypal Test Mode "Re-Check Payment Status" button is broken

### ISSUE THREAD

**Issue by stergosz** [awesomemotive/easy-digital-downloads#9767]
### Expected behavior
On a local test site (tested also on a live test site), I have Test Mode enabled, went to Payments > PayPal and clicked to connect a sandbox account for testing purposes. After connecting my account, I was presented with this screen:

![Image](https://github.com/user-attachments/assets/0d759fcf-8673-40c9-9879-b6ebc8058eb4)

When I click "Re-Check Payment Status", I see this in my Developer Console > Network Tab > AJAX request:
![Image](https://github.com/user-attachments/assets/237e9e6b-9117-41ba-bbaa-75b39c430c66)

### Actual behavior
It should let me connect to my sandbox business account, on any site I desire.

### Steps to reproduce the behavior
1) Install EDD
2) Go to Downloads > Payments > enable "Enable Test Mode" > hit "Save Changes"
3) Go to Downloads > Payments > PayPal > click on "Connect with PayPal in sandbox mode" and connect with your Sandbox business account
4) Upon connecting, you should be presented with the first screen on this issue.
4) Clicking "Re-Check Payment Status" does nothing

### Information (if a specific version is affected):
PHP Version: 7.4.33

EDD Version (or branch): 3.3.4

WordPress Version: 6.6, and 6.7-RC3

Any other relevant information:

**Comment by mihaijoldis** [comment]
Hey @stergosz 

This issue was fixed in the latest update 3.3.5 which was released yesterday. Please update to the latest version give it another test and let us know if it's fixed for you.

**Comment by stergosz** [comment]
I can confirm that it's fixed, thanks!
